// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'state.dart';
part 'config.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

/// The reference sync servers for `network` — PUBLIC servers only, with no
/// key: on mainnet `zec.rocks`, on testnet the `zec.rocks` testnet rail.
/// To offer servers of your own (gated or not), append them and pass the list
/// as `WalletConfig.syncServers`:
/// `[...referenceSyncServers(network: n), SyncServer(id: 'mine', label: 'My
/// server', url: 'https://…', authHeader: 'x-api-key', authValue: key)]`,
/// with `key` from a `--dart-define` — never a committed file.
List<SyncServer> referenceSyncServers({required Network network}) =>
    ZecWalletRustLib.instance.api.crateApiConfigReferenceSyncServers(
      network: network,
    );

/// Validate a [WalletConfig] without opening anything — for settings-form
/// UX. Runs the SAME Rust-side validation that `create`/`open` will run
/// (endpoint rules, bounds); throws the same typed
/// [crate::api::error::WalletApiError].
void validateWalletConfig({required WalletConfig config}) => ZecWalletRustLib
    .instance
    .api
    .crateApiConfigValidateWalletConfig(config: config);

@freezed
sealed class JitterPolicy with _$JitterPolicy {
  const JitterPolicy._();

  /// No delay — an honest opt-out.
  const factory JitterPolicy.none() = JitterPolicy_None;

  /// Uniform random delay in `0..=maxMs` before each tx broadcast. The
  /// documented default window is 0..=10 s. `maxMs` above 30 000 (30 s) is
  /// refused with `broadcastJitterTooLong` by create, open and
  /// `validateWalletConfig` alike, never clamped. (`u32`, so Dart gets a
  /// plain `int`.)
  const factory JitterPolicy.uniform({required int maxMs}) =
      JitterPolicy_Uniform;
}

/// Consensus network. A runtime parameter — one binary serves both networks.
enum Network { main, test }

/// Where the seed lives between launches.
enum SeedPersistence {
  /// The SDK seals seed + mnemonic under a keychain-held key (XChaCha20-
  /// Poly1305, versioned envelope). Default for Dart-path consumers:
  /// enables `revealMnemonic` after restart. At-rest honesty: protection =
  /// the OS keychain ACL + device lock — there is no passphrase KDF.
  sealedKeychain,

  /// Nothing persisted: every launch must re-supply the seed. The host
  /// owns the recovery story.
  none,
}

/// A sync server a host OFFERS (the picker, P3-13).
class SyncServer {
  /// Stable, host-chosen id — what the wallet remembers. Lowercase ascii
  /// letters, digits, `-`; at most 32 bytes. Never shown; the label is.
  final String id;

  /// Display name. Printable, at most 64 bytes.
  final String label;

  /// `https://host[:port]` (loopback `http://` for development), like
  /// `endpointUrl`.
  final String url;

  /// The auth header a GATED entry sends on every request, e.g.
  /// `x-api-key`. `null` for a public server. On the list a HANDLE
  /// returns, this says whether the entry is gated; the value is never
  /// returned.
  final String? authHeader;

  /// The header's value — the same §5.4 framing as `endpointAuthValue`:
  /// never logged, wrapped `Zeroizing` in Rust, ONE key for every install
  /// (a rate-limit handle, never an authorization boundary), prefer a
  /// `--dart-define` over anything that lands in a file. Both-or-neither
  /// with `authHeader`: one without the other is refused at the door.
  /// NEVER persisted by the wallet: the choice row stores the id. On the
  /// list a HANDLE returns it is always `null`.
  final String? authValue;

  const SyncServer({
    required this.id,
    required this.label,
    required this.url,
    this.authHeader,
    this.authValue,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      url.hashCode ^
      authHeader.hashCode ^
      authValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncServer &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          url == other.url &&
          authHeader == other.authHeader &&
          authValue == other.authValue;
}

@freezed
sealed class SyncServerChoice with _$SyncServerChoice {
  const SyncServerChoice._();

  /// One of the offered entries, by id.
  const factory SyncServerChoice.predefined({required String id}) =
      SyncServerChoice_Predefined;

  /// A URL the user typed, and the key they gave for it (`null` = none).
  /// The URL is validated at the door like `endpointUrl`, and bounded
  /// (2048 bytes) before the validator sees it.
  const factory SyncServerChoice.custom({
    required String url,
    SyncServerKey? key,
  }) = SyncServerChoice_Custom;

  /// Clear the choice: back to `endpointUrl`.
  const factory SyncServerChoice.default_() = SyncServerChoice_Default;

  /// Forward-compatibility arm (never accepted as input).
  const factory SyncServerChoice.unknown() = SyncServerChoice_Unknown;
}

@freezed
sealed class SyncServerFallback with _$SyncServerFallback {
  const SyncServerFallback._();

  /// The remembered id is one this app no longer offers; `id` names it.
  const factory SyncServerFallback.choiceNotOffered({required String id}) =
      SyncServerFallback_ChoiceNotOffered;

  /// The remembered choice could not be read (a malformed row). The wallet
  /// is usable on the default; pick again.
  const factory SyncServerFallback.choiceUnreadable() =
      SyncServerFallback_ChoiceUnreadable;

  /// The remembered custom server uses an unencrypted (`http://`) address,
  /// which the wallet's private path (a host-registered dialer) cannot
  /// carry: the default is in use, the choice is kept (FR-29 E12). Pick an
  /// `https://` server, or run the wallet with `TorPolicy.off` to use it.
  const factory SyncServerFallback.choiceRefusedByTransport() =
      SyncServerFallback_ChoiceRefusedByTransport;

  /// Forward-compatibility arm.
  const factory SyncServerFallback.unknown() = SyncServerFallback_Unknown;
}

/// A key the USER gives for their own custom server (ADR-0568): the header
/// name their server expects and its value. A plain struct ON PURPOSE — the
/// generated Dart class has no `toString` that renders fields (a freezed
/// enum variant's would print the value), so `'$choice'` never shows the key.
///
/// On input, the header is at most 64 bytes, must be a valid header name and
/// not one the transport owns or `grpc-…`; the value is at most 4096 bytes of
/// printable ASCII with no surrounding whitespace. A refusal is
/// `WalletErrorKind.invalidEndpointAuth`. A key is refused on an `http://`
/// server. The wallet STORES it (encrypted, with the choice) so the server
/// keeps working across launches, erases it when another server is chosen,
/// and never logs it. On a value the SDK RETURNS (a status), `value` is
/// ALWAYS the empty string — the header says a key is saved; the key itself
/// never leaves Rust — so a returned keyed choice cannot be passed back in.
/// The user's key identifies them to that server (the picker says so).
class SyncServerKey {
  final String header;
  final String value;

  const SyncServerKey({required this.header, required this.value});

  @override
  int get hashCode => header.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncServerKey &&
          runtimeType == other.runtimeType &&
          header == other.header &&
          value == other.value;
}

/// The reachability probe's answer ([WalletHandle.probeSyncServer]): the
/// server answered under the wallet's own Tor policy and claims this wallet's
/// network. A fact about reachability and identity, never about honesty —
/// the sync guards judge that pass by pass.
class SyncServerProbe {
  /// The server's claimed tip. Untrusted; a bare height.
  final int tip;

  const SyncServerProbe({required this.tip});

  @override
  int get hashCode => tip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncServerProbe &&
          runtimeType == other.runtimeType &&
          tip == other.tip;
}

/// Which server the wallet dials, which choice produced it, and whether a
/// fallback is in force ([WalletHandle.syncServerStatus]). A URL that names
/// an offered server is spelled as that entry's `url`, so comparing strings
/// against `syncServers()` finds its row (`https://zec.rocks` and
/// `https://zec.rocks:443` are one server).
class SyncServerStatus {
  /// The endpoint every request goes to right now. Render its HOST, never
  /// the whole URL.
  final String effectiveUrl;

  /// `endpointUrl` — "App default" when it is not among the offered entries.
  final String defaultUrl;

  /// The persisted choice; `null` = no choice ever made (the default by
  /// absence, not by fallback).
  final SyncServerChoice? choice;

  /// Non-null = the choice could not be honoured; `effectiveUrl` is then
  /// `defaultUrl`.
  final SyncServerFallback? fallback;

  const SyncServerStatus({
    required this.effectiveUrl,
    required this.defaultUrl,
    this.choice,
    this.fallback,
  });

  @override
  int get hashCode =>
      effectiveUrl.hashCode ^
      defaultUrl.hashCode ^
      choice.hashCode ^
      fallback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncServerStatus &&
          runtimeType == other.runtimeType &&
          effectiveUrl == other.effectiveUrl &&
          defaultUrl == other.defaultUrl &&
          choice == other.choice &&
          fallback == other.fallback;
}

@freezed
sealed class TorPolicy with _$TorPolicy {
  const TorPolicy._();

  /// Direct connections.
  const factory TorPolicy.off() = TorPolicy_Off;

  /// Tor when reachable; falls back to clearnet WITH a visible
  /// `TorState.fellBack` — degradation is never silent.
  const factory TorPolicy.preferred({required TorRuntimeConfig runtime}) =
      TorPolicy_Preferred;

  /// Fail-closed: runtime unreachable ⇒ ZERO packets, sync `Stalled`.
  /// Covers swap API calls too — there is no independent clearnet path.
  const factory TorPolicy.required_({required TorRuntimeConfig runtime}) =
      TorPolicy_Required;
}

@freezed
sealed class TorRuntimeConfig with _$TorRuntimeConfig {
  const TorRuntimeConfig._();

  /// Host-side Tor speaking SOCKS5 (Orbot, system Tor, a sidecar), e.g.
  /// `"127.0.0.1:9050"`. REFUSED at the config door (T0-6, ADR-0543) —
  /// use [`TorRuntimeConfig::HostDialer`].
  const factory TorRuntimeConfig.externalSocks5({required String addr}) =
      TorRuntimeConfig_ExternalSocks5;

  /// The dialer the host's native library registered (FR-29, the C contract
  /// `include/zec_wallet_net_dialer.h`). No payload: the registration lives
  /// in the wallet library's process-global registry, not in this value.
  /// `TorState.active(runtime: hostDialer(name, isolation, exposure))` then
  /// reports what the host declared: its OWN name for the transport
  /// (ADR-0547 — the SDK has no list of kinds), whether the path keeps the
  /// wallet's connections apart, and whether it hides the device's address.
  const factory TorRuntimeConfig.hostDialer() = TorRuntimeConfig_HostDialer;
}

/// Wallet configuration.
///
/// `Clone` is derived so a host-seed provisioning flow (FR-15) can build the
/// validated core config TWICE from one DTO (create then reopen-with-seed-port —
/// the core `WalletConfig` is not `Clone` because of the optional injected dialer).
/// It is a plain value DTO; the derive is additive and FRB-irrelevant.
class WalletConfig {
  /// Host-owned data directory (platform app dir). MUST be an ABSOLUTE
  /// path — empty/relative is rejected typed (`InvalidDbDir`, RW-CFG-003)
  /// at create/open/validate, because a relative dir would resolve against
  /// the process working directory and strand the wallet (worst on
  /// desktop, where the cwd changes between launches). The host owns
  /// backup-exclusion for this dir (iOS `isExcludedFromBackup`, Android
  /// `no_backup/`).
  final String dbDir;
  final Network network;

  /// lightwalletd-protocol (Zaino-compatible) gRPC endpoint URL.
  /// `https://host[:port]` anywhere; `http://` only for loopback (local
  /// development) — plaintext to a remote host is a leak, not a
  /// configuration. URLs with userinfo (`user:pass@`) are rejected.
  final String endpointUrl;

  /// OPTIONAL name of an auth header sent on EVERY light-server request, for
  /// an endpoint behind a proxy that gates access. `null` (the common case)
  /// sends no auth header. Must be paired with [`Self::endpoint_auth_value`];
  /// supplying one without the other is a typed refusal at construction, not
  /// a silently unauthenticated wallet.
  final String? endpointAuthHeader;

  /// OPTIONAL value for [`Self::endpoint_auth_header`]. A §5.4 NEVER-log
  /// value: wrapped `Zeroizing` in Rust at the boundary, marked sensitive on
  /// the wire so it is never HPACK-indexed, and never logged. Dart memory
  /// cannot be zeroized — the documented §10 exposure, the same framing as the
  /// swap JWT; keep it minimal-residency host-side and prefer
  /// `--dart-define` over anything that lands in a file.
  ///
  /// **What this buys, so it is not over-trusted:** a key shipped in a
  /// distributed app is extractable from the binary. This is abuse control —
  /// it gives the proxy a handle for per-key rate-limits — not access control
  /// against a determined party.
  ///
  /// **USE ONE KEY FOR EVERY INSTALL.** A per-user or per-install key defeats
  /// the SDK's broadcast unlinkability: it mints a fresh Tor circuit per send
  /// so the endpoint cannot tie a broadcast to the syncing wallet, and a
  /// distinct constant header re-joins them on the first request. One shared
  /// key is a rate-limit handle; a per-user key is a tracking identifier.
  final String? endpointAuthValue;

  /// REQUIRED: what must happen to wallet traffic.
  final TorPolicy tor;

  /// Where the seed lives between launches.
  final SeedPersistence seedPersistence;

  /// Restore-from height; `null` on create (= current tip). Above-tip is
  /// rejected typed at first sync; below-activation is clamped.
  final int? birthdayHeight;

  /// Broadcast-timing decorrelation (delays tx broadcast by a random
  /// in-window amount so sends don't timestamp-correlate with other
  /// host-app traffic).
  final JitterPolicy broadcastJitter;

  /// FR-27 — the OPT-IN machine-memo read scope: the leading bytes an
  /// on-chain `0xFF` memo must carry for [WalletHandle.machineMemos] to
  /// return it. EMPTY by default, and empty means that verb stays CLOSED
  /// (it refuses typed rather than answering with an empty list).
  ///
  /// **A prefix bounds VOLUME, not intent.** Forging one costs an attacker
  /// nothing, so this keeps unrelated envelopes out of your parser — it is
  /// not evidence that what arrives is yours. And it does NOT mean "written
  /// by this device": the memos worth reading were written by whoever paid
  /// you.
  ///
  /// Each prefix must be non-empty and at most 32 bytes; at most 8 may be
  /// registered. A scope that could never work is refused at create/open
  /// ([WalletErrorKind.machineMemoScopeInvalid]) rather than silently
  /// reading nothing forever.
  final List<Uint8List> machineMemoPrefixes;

  /// The sync servers this host OFFERS the user (the picker, P3-13). `null`
  /// or empty = none offered: the picker shows `endpointUrl` and a custom
  /// entry only. `endpointUrl` is the DEFAULT — a wallet with no persisted
  /// choice dials it, and a choice that can no longer be honoured falls back
  /// to it with the reason on [WalletHandle.syncServerStatus]. A persisted
  /// choice WINS at open. Validated like the endpoint (bounded list, unique
  /// ids, every URL through the same door). `referenceSyncServers` gives the
  /// public reference servers; a host appends its OWN servers — gated ones
  /// with `authHeader`/`authValue` — to that list (ADR-0568).
  final List<SyncServer>? syncServers;

  const WalletConfig({
    required this.dbDir,
    required this.network,
    required this.endpointUrl,
    this.endpointAuthHeader,
    this.endpointAuthValue,
    required this.tor,
    required this.seedPersistence,
    this.birthdayHeight,
    required this.broadcastJitter,
    required this.machineMemoPrefixes,
    this.syncServers,
  });

  @override
  int get hashCode =>
      dbDir.hashCode ^
      network.hashCode ^
      endpointUrl.hashCode ^
      endpointAuthHeader.hashCode ^
      endpointAuthValue.hashCode ^
      tor.hashCode ^
      seedPersistence.hashCode ^
      birthdayHeight.hashCode ^
      broadcastJitter.hashCode ^
      machineMemoPrefixes.hashCode ^
      syncServers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletConfig &&
          runtimeType == other.runtimeType &&
          dbDir == other.dbDir &&
          network == other.network &&
          endpointUrl == other.endpointUrl &&
          endpointAuthHeader == other.endpointAuthHeader &&
          endpointAuthValue == other.endpointAuthValue &&
          tor == other.tor &&
          seedPersistence == other.seedPersistence &&
          birthdayHeight == other.birthdayHeight &&
          broadcastJitter == other.broadcastJitter &&
          machineMemoPrefixes == other.machineMemoPrefixes &&
          syncServers == other.syncServers;
}
