// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'state.dart';
part 'error.freezed.dart';

/// Why a swap destination was refused.
enum DestinationInvalidReason {
  /// Swapping OUT of ZEC requires a foreign destination address.
  missing,

  /// Swapping INTO ZEC must NOT carry one (delivery goes to the wallet's
  /// own fresh address).
  notAllowedForDirection,

  /// A ZEC→ZEC "swap" is a fee-burning provider round-trip — refused.
  zcashAddressNotAllowed,

  /// Exceeds the SDK's provider-string bound.
  oversized,

  /// Forward-compatibility arm.
  unknown,
}

/// Lifecycle phase, as carried by [WalletErrorKind.walletBusy] /
/// [WalletErrorKind.invalidState] so a host can render "what is the wallet
/// doing" instead of a bare failure.
enum LifecyclePhase {
  /// create/restore in progress.
  provisioning,

  /// Resuming from an interrupted provisioning.
  repairing,
  open,

  /// `rescanFrom` is rebuilding the data DB at an earlier birthday (ADR-0534); a
  /// concurrent call gets a retryable [WalletErrorKind.walletBusy] carrying this
  /// phase, never a torn read.
  rescanning,

  /// `switchSyncServer` is swapping the session onto another server; a
  /// concurrent call gets a retryable [WalletErrorKind.walletBusy] carrying
  /// this phase, never a torn read. Rescanning's sibling (no data rebuild).
  switchingServer,

  /// `close()` in progress; in-flight calls resolve with this phase.
  closing,

  /// Terminal: the store was crypto-shredded.
  wiped,

  /// Forward-compatibility arm (see [WalletErrorKind.unknown]).
  unknown,
}

/// How a provider response broke the contract — typed so the host can render
/// an honest "provider misbehaved" without the SDK leaking the payload.
enum ProviderProtocolReason {
  /// The echoed refund address differs from the one the SDK sent —
  /// aborted before any deposit.
  refundAddressMismatch,

  /// A provider string exceeded its bound.
  oversizedField,

  /// An amount field was not a finite, in-range decimal.
  malformedAmount,

  /// Unknown status value.
  unknownStatus,

  /// The deposit address failed validation (parseable, transparent, right
  /// network — checked before any signing path).
  depositAddressInvalid,

  /// A field the flow requires was absent from the provider response.
  missingField,

  /// HTTP-level contract break (unexpected status, or a redirect — a
  /// funds path never silently follows one).
  unexpectedHttpStatus,

  /// The provider response exceeded the SDK's size cap for that call.
  oversizedBody,

  /// The provider response was not in the documented shape.
  undecodableResponse,

  /// The provider asked for a deposit memo the wallet cannot honor —
  /// refused, because depositing without it would lose the funds.
  depositMemoUnsupported,

  /// The provider no longer knows this swap.
  swapNotFound,

  /// The provider's swap id collided with a wallet-reserved internal key
  /// namespace and was refused at the quote door (#368) — get a new quote.
  reservedId,

  /// The provider's echo of the quote request named different terms from
  /// the ones the SDK sent (a different recipient, asset, amount, exact side
  /// or slippage) — refused before any review or deposit; get a new quote.
  requestEchoMismatch,

  /// Forward-compatibility arm.
  unknown,
}

/// Which quote side broke the user-anchored bound.
enum QuoteBoundSide {
  zec,
  foreign,

  /// Forward-compatibility arm.
  unknown,
}

/// #390 — why a "Check older swap addresses" deep scan was refused (the payload of
/// [WalletErrorKind.swapAddressCheckRefused]). Branch on it for the honest host copy.
enum SwapAddressCheckRefusal {
  /// Swap is turned OFF at this instance (a host kill switch reached the SDK) — the
  /// check depends on the swap polling a kill stops, so it would register nothing.
  /// Render "swap is unavailable right now"; not an error to retry once swap is back.
  swapDisabled,

  /// A prior check is still outstanding — its range is still registering, OR its watch
  /// window has not yet closed (at most ONE check per settlement window). Render "still
  /// checking the last range — try again later"; NOTHING was widened this call.
  checkOutstanding,

  /// Forward-compatibility arm (see [WalletErrorKind.unknown]).
  unknown,
}

/// A swap operation failed. Same contract as [WalletApiError]: catch by
/// type, branch on `kind`, log `code`.
class SwapApiError implements FrbException {
  /// Stable, append-only `RW-SWAP-*` code.
  final String code;

  /// Static, payload-free description (safe to log).
  final String message;
  final SwapErrorKind kind;

  const SwapApiError({
    required this.code,
    required this.message,
    required this.kind,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapApiError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          kind == other.kind;
}

@freezed
sealed class SwapErrorKind with _$SwapErrorKind {
  const SwapErrorKind._();

  /// Requested tolerance above the hard SDK ceiling — a wider window is a
  /// drain surface, not a preference.
  const factory SwapErrorKind.slippageToleranceTooHigh({
    required int requestedBps,
    required int maxBps,
  }) = SwapErrorKind_SlippageToleranceTooHigh;

  /// Quote side outside [user request ± tolerance] — rejected BEFORE
  /// anything is signed; a deposit is never anchored to provider numbers
  /// alone.
  const factory SwapErrorKind.quoteOutOfBounds({required QuoteBoundSide side}) =
      SwapErrorKind_QuoteOutOfBounds;

  /// The quote is no longer executable — its deadline lapsed, OR (since
  /// #367) its single-use claim is gone (already executed, or swept as
  /// never-issued/lapsed). No signing past it, ever. Re-quote.
  const factory SwapErrorKind.quoteExpired() = SwapErrorKind_QuoteExpired;

  /// Destination rejected (see `reason`).
  const factory SwapErrorKind.destinationInvalid({
    required DestinationInvalidReason reason,
  }) = SwapErrorKind_DestinationInvalid;

  /// Request shape inconsistent (e.g. exact side names the wrong asset
  /// family); `reason` is a static description.
  const factory SwapErrorKind.requestInvalid({required String reason}) =
      SwapErrorKind_RequestInvalid;

  /// Provider unreachable / 5xx — retryable; the wallet is unaffected.
  const factory SwapErrorKind.providerUnavailable() =
      SwapErrorKind_ProviderUnavailable;

  /// Provider response violated the protocol contract — typed, never
  /// trusted further.
  const factory SwapErrorKind.providerProtocol({
    required ProviderProtocolReason reason,
  }) = SwapErrorKind_ProviderProtocol;

  /// Swap is turned OFF at this instance (the host's regulatory kill switch
  /// reached the SDK). Render "swap unavailable" and hide the swap surface;
  /// it is not an error to retry. New quotes/executes are refused; any
  /// in-flight swap settles or refunds provider-side regardless.
  const factory SwapErrorKind.swapDisabled() = SwapErrorKind_SwapDisabled;

  /// OUR side could not queue the §4.4 deposit leg after the provider registered
  /// the swap intent (the wallet was tearing down / wiped, or its store errored).
  /// Honest-degradation: the swap does NOT proceed — no ZEC left the pool — so
  /// re-quote; the provider refunds an un-deposited quote after its deadline.
  /// Distinct from [SwapErrorKind.providerUnavailable] (that is the PROVIDER's side).
  const factory SwapErrorKind.depositSendFailed() =
      SwapErrorKind_DepositSendFailed;

  /// OUR side could not produce a fresh transparent refund address for an
  /// OutOfZec quote (the QUOTE-time counterpart of [SwapErrorKind.depositSendFailed]):
  /// the wallet is tearing down / wiped, its index store errored, or it
  /// structurally cannot serve OutOfZec refunds (no seed at rest, or an exotic
  /// seed length). Honest-degradation: NO quote was returned — nothing left the
  /// pool. Render "swap unavailable" and let the user retry; a structurally
  /// incapable wallet stays so until reconstructed.
  const factory SwapErrorKind.refundAddressUnavailable() =
      SwapErrorKind_RefundAddressUnavailable;

  /// IntoZec quote (the destination-mint counterpart of [SwapErrorKind.refundAddressUnavailable]):
  /// the wallet could not mint the FRESH per-swap ZEC receive address 1Click is handed as the
  /// recipient (§3.3b D1 / ADR-0530) — the engine DB was locked, the sealed store errored, or no
  /// account is provisioned yet. Honest-degradation: NO quote was returned — nothing is in flight.
  /// Render "swap unavailable" and let the user retry.
  const factory SwapErrorKind.destinationAddressUnavailable() =
      SwapErrorKind_DestinationAddressUnavailable;

  /// OUR side could not maintain its durable in-flight issued-quote state (the
  /// store that makes a crash-then-requote double-deposit observable to recovery):
  /// the wallet was tearing down / wiped or its sealed store errored. Fail-closed —
  /// a quote is not issued, or an execute does not register intent, so nothing left
  /// the pool; re-quote. Render "swap unavailable" and let the user retry.
  const factory SwapErrorKind.swapStateUnavailable() =
      SwapErrorKind_SwapStateUnavailable;

  /// OUR side's durable swap store was momentarily BUSY (#367) at a site where
  /// NOTHING was consumed — the quote persist or the execute claim. RETRYABLE:
  /// a plain retry of the SAME action genuinely succeeds once the contending
  /// writer finishes. Render "the wallet is busy for a moment — try again";
  /// for an execute specifically the quote is UNCONSUMED and still valid, so
  /// do NOT force a re-quote (that would needlessly burn it).
  const factory SwapErrorKind.swapStateBusy() = SwapErrorKind_SwapStateBusy;

  /// A swap deposit is ALREADY in flight — the SDK's one-deposit-in-flight guard
  /// refused a second while the first is queued/signing/sending. The REMEDY is the
  /// opposite of every other execute failure: do **NOT** re-quote (a re-quote is the
  /// double-deposit door this guard closes) — render "a swap is already in progress"
  /// and point the user at the tracked swap / activity surface. Self-clears when the
  /// in-flight deposit mines or its quote deadline lapses. The refusing execute
  /// consumed its quote and registered provider intent — fail-safe (an un-deposited
  /// quote refunds provider-side after its deadline; nothing left the pool).
  const factory SwapErrorKind.swapAlreadyInFlight() =
      SwapErrorKind_SwapAlreadyInFlight;

  /// The wallet is WATCH-ONLY — it holds no spending keys, so swap is
  /// STRUCTURALLY unavailable (#397 §3.7 D3; surfaced when the host attempts
  /// `enableNearSwap`, before any service is wired). NEVER retryable: unlike
  /// [SwapErrorKind.providerUnavailable] this is not a transient outage — no
  /// retry, timeout, or transport change ever clears it. Render the
  /// view-only framing ("this wallet can't swap — it can only watch") and
  /// keep the whole swap surface hidden/disabled; only a spending wallet can
  /// swap. The swap-taxonomy mirror of the wallet-level watch-only refusal.
  const factory SwapErrorKind.watchOnly() = SwapErrorKind_WatchOnly;

  /// The `SwapQuote` passed to `swapExecute` names a quote this wallet issued but
  /// carries DIFFERENT terms from the record it kept (deposit address, amount,
  /// foreign amount, memo, refund target or binding). Refused BEFORE the quote's
  /// single-use claim and before any provider or deposit call: nothing was consumed,
  /// nothing left the wallet, and the quote stays executable by the DTO `swapQuote`
  /// returned. Pass that DTO back unchanged; if you cannot, re-quote. The differing
  /// values are never surfaced (they are render-never-log).
  const factory SwapErrorKind.quoteTermsDiffer() =
      SwapErrorKind_QuoteTermsDiffer;

  /// Forward-compatibility arm (see [WalletErrorKind.unknown]). KEEP LAST:
  /// inserting a variant above renumbers this arm's generated wire tag —
  /// safe ONLY while the Rust cdylib and the generated Dart ship from one
  /// checkout (cargokit source builds, no precompiled channel). If a
  /// precompiled-binary channel is ever added, wire tags become ABI and
  /// "Unknown always last" turns every append into a silent renumber —
  /// revisit the layout policy then (reliability NIT).
  const factory SwapErrorKind.unknown() = SwapErrorKind_Unknown;
}

/// A wallet operation failed. `message` is the core's STATIC, payload-free
/// display line (amounts/addresses/txids never appear in it — safe to log);
/// the typed payload for rendering lives in `kind`.
class WalletApiError implements FrbException {
  /// Stable, greppable, append-only code (`RW-SEED-001`, `RW-STORE-005`,
  /// …) — the support/log identifier.
  final String code;

  /// Static description; safe to log, NOT for end users (render from
  /// `kind` and localize host-side).
  final String message;
  final WalletErrorKind kind;

  const WalletApiError({
    required this.code,
    required this.message,
    required this.kind,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletApiError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          kind == other.kind;
}

@freezed
sealed class WalletErrorKind with _$WalletErrorKind {
  const WalletErrorKind._();

  /// Seed bytes outside the supported 32..=252 length window.
  const factory WalletErrorKind.invalidSeedLength({required BigInt len}) =
      WalletErrorKind_InvalidSeedLength;

  /// BIP39 checksum/word failure. Index of the first bad word when known —
  /// NEVER the word itself.
  const factory WalletErrorKind.invalidMnemonic({int? wordIndex}) =
      WalletErrorKind_InvalidMnemonic;

  /// `revealMnemonic` on a wallet created from raw seed bytes — that
  /// wallet structurally has no phrase; recovery is the host's own story.
  const factory WalletErrorKind.noMnemonic() = WalletErrorKind_NoMnemonic;

  /// The operation needs the seed re-supplied (persistence is `none`).
  const factory WalletErrorKind.seedRequired() = WalletErrorKind_SeedRequired;

  /// Supplied seed does not match the existing wallet at this `dbDir`.
  const factory WalletErrorKind.seedMismatch() = WalletErrorKind_SeedMismatch;

  /// Upstream key derivation failed (unreachable for a bounds-valid seed).
  const factory WalletErrorKind.keyDerivation() = WalletErrorKind_KeyDerivation;

  /// A spend-class operation (send/shield/swap/reveal/backup) on a
  /// WATCH-ONLY wallet (#397 §3.7 D3). STRUCTURAL, not retryable — no seed
  /// will ever arrive; render an explanation ("this wallet holds no
  /// spending keys"), never a retry affordance.
  const factory WalletErrorKind.watchOnly() = WalletErrorKind_WatchOnly;

  /// A supplied viewing key failed to decode for this wallet's network
  /// (garbage, truncated, or a wrong-network `uview…`). The value is never
  /// echoed.
  const factory WalletErrorKind.invalidViewingKey() =
      WalletErrorKind_InvalidViewingKey;

  /// Endpoint URL rejected; `reason` says which rule (https-only,
  /// userinfo, path, …).
  const factory WalletErrorKind.invalidEndpoint({required String reason}) =
      WalletErrorKind_InvalidEndpoint;

  /// Restore birthday above the chain tip — a too-high birthday would
  /// silently never find the user's notes.
  const factory WalletErrorKind.birthdayInFuture() =
      WalletErrorKind_BirthdayInFuture;

  /// Wallet data directory rejected (`reason`: empty / not absolute).
  /// `dbDir` MUST be an absolute platform path — a relative one would
  /// resolve against the process working directory and strand the wallet
  /// (worst on desktop, where the cwd changes between launches).
  /// NON-RETRYABLE: a host configuration bug, not a user or environment
  /// condition — fix the path the host passes.
  const factory WalletErrorKind.invalidDbDir({required String reason}) =
      WalletErrorKind_InvalidDbDir;

  /// An endpoint auth header or value rejected (ADR-0568) — a host's
  /// `endpointAuth*` / `SyncServer.auth*`, or a user's `SyncServerKey`: a
  /// half pair, a header that is not a valid name, one the transport owns or
  /// `grpc-…`, over 64 bytes, a value that is empty, over 4096 bytes, not
  /// printable ASCII or padded with whitespace, or any key for an `http://`
  /// server. `reason` names the rule; the value is NEVER echoed. Its own
  /// kind so a picker tells a bad key from a bad URL without reading text.
  const factory WalletErrorKind.invalidEndpointAuth({required String reason}) =
      WalletErrorKind_InvalidEndpointAuth;

  /// `broadcastJitter` is `uniform(maxMs)` above the ceiling (`ceilingMs`,
  /// 30 000): a longer wait before a broadcast could outlast a transaction's
  /// validity. NON-RETRYABLE: a host configuration bug, refused at
  /// create/open rather than clamped. RW-CFG-005.
  const factory WalletErrorKind.broadcastJitterTooLong({
    required BigInt maxMs,
    required BigInt ceilingMs,
  }) = WalletErrorKind_BroadcastJitterTooLong;

  /// Amount negative or beyond max supply. Payload-free on purpose:
  /// amounts are never-log material.
  const factory WalletErrorKind.amountOutOfRange() =
      WalletErrorKind_AmountOutOfRange;

  /// Memo exceeds its ZIP-302 bound.
  const factory WalletErrorKind.memoTooLong({
    required BigInt len,
    required BigInt max,
  }) = WalletErrorKind_MemoTooLong;

  /// ZIP-302 reserved-range memos are receivable but never sendable.
  const factory WalletErrorKind.reservedMemoNotSendable() =
      WalletErrorKind_ReservedMemoNotSendable;

  /// Memos require a shielded recipient (the protocol cannot carry one to
  /// a transparent address) — rejected at construction, honestly.
  const factory WalletErrorKind.memoRequiresShieldedRecipient() =
      WalletErrorKind_MemoRequiresShieldedRecipient;

  /// Address failed to parse for the configured network. The value is
  /// never echoed back.
  const factory WalletErrorKind.addressInvalid() =
      WalletErrorKind_AddressInvalid;

  /// Memo bytes failed ZIP-302 classification (a text-lead memo whose
  /// payload is not valid UTF-8). Payload-free: memo bytes are content.
  const factory WalletErrorKind.memoInvalid() = WalletErrorKind_MemoInvalid;

  /// A payment leg carried BOTH a text memo and machine bytes — one memo per
  /// payment. **This is a CALLER bug, not a user-fixable condition:** neither
  /// memo is individually invalid, so do NOT render "that memo can't be sent"
  /// at the user. Fix the code that built the request.
  const factory WalletErrorKind.memoConflict() = WalletErrorKind_MemoConflict;

  /// Zero-valued output to a transparent-only recipient — disallowed by
  /// consensus; rejected at construction.
  const factory WalletErrorKind.zeroValuedTransparentOutput() =
      WalletErrorKind_ZeroValuedTransparentOutput;

  /// ZIP-321 payment URI rejected: oversized, structurally malformed, or
  /// requesting nothing. Payload-free on purpose — URIs carry addresses
  /// and amounts.
  const factory WalletErrorKind.paymentUriInvalid() =
      WalletErrorKind_PaymentUriInvalid;

  /// A txid string was not 64 hex characters. Payload-free: txids are
  /// never-log material, so the offending value is never echoed back.
  /// Pass back the `txidHex` a history row handed you, verbatim.
  const factory WalletErrorKind.txidInvalid() = WalletErrorKind_TxidInvalid;

  /// FR-27 — the machine-memo READ scope cannot be used. Either no prefix
  /// is registered on the config (the verb is opt-in and CLOSED by
  /// default — an empty answer would read as "this transaction carries
  /// nothing"), or a registered prefix is empty / over-long / one too
  /// many. `reason` is an SDK-authored static string; it never echoes
  /// host input.
  const factory WalletErrorKind.machineMemoScopeInvalid({
    required String reason,
  }) = WalletErrorKind_MachineMemoScopeInvalid;

  /// Keychain locked / transiently unreachable, OR the key store did not
  /// answer within the SDK's bound (FR-47; then `code` is `RW-KEY-008`).
  /// Retryable. A wedged key store clears only when its stuck call returns,
  /// which may take a restart. Distinct from missing.
  const factory WalletErrorKind.keystoreUnavailable() =
      WalletErrorKind_KeystoreUnavailable;

  /// Keychain item genuinely absent or permanently invalidated while the
  /// wallet DB exists — surfaced, NEVER silently treated as a fresh
  /// wallet. `permanentlyInvalidated` = a biometric/PIN reset destroyed
  /// the key; recovery is the mnemonic.
  const factory WalletErrorKind.keystoreInconsistent({
    required bool permanentlyInvalidated,
  }) = WalletErrorKind_KeystoreInconsistent;

  /// Sealed seed carries an unknown version byte — likely an app
  /// downgrade reading a newer seal.
  const factory WalletErrorKind.sealVersionUnsupported({required int found}) =
      WalletErrorKind_SealVersionUnsupported;

  /// Sealed seed failed validation/decryption. Truncation, tamper and
  /// wrong-key collapse to this ONE kind on purpose (no oracle).
  const factory WalletErrorKind.sealInvalid() = WalletErrorKind_SealInvalid;

  /// No platform key vault exists at all (no Keystore tier / no keyring), OR
  /// the app's link bound the wallet to a SQLite without SQLCipher, where the
  /// database key would do nothing (FR-5 D-24 — a BUILD defect: check the
  /// host's linkage, e.g. a static link that also pulls the system sqlite;
  /// retrying cannot help). FAIL-CLOSED: the wallet will not custody a seed
  /// without a vault nor store its database unencrypted. Permanent for this
  /// device/build — distinct from the retryable `keystoreUnavailable`.
  const factory WalletErrorKind.vaultAbsent() = WalletErrorKind_VaultAbsent;

  /// The wrap artifact failed validation or authenticated unwrap against
  /// THIS wallet's sealed seed (substitution or corruption — collapsed,
  /// but attributed to the wrap layer, never reported as `sealInvalid`).
  const factory WalletErrorKind.wrapArtifactInvalid() =
      WalletErrorKind_WrapArtifactInvalid;

  /// Wrap artifact carries an unknown version byte — likely an app
  /// downgrade reading a newer artifact.
  const factory WalletErrorKind.wrapVersionUnsupported({required int found}) =
      WalletErrorKind_WrapVersionUnsupported;

  /// `open()` with no wallet at `dbDir`.
  const factory WalletErrorKind.notFound() = WalletErrorKind_NotFound;

  /// The wallet DB belongs to a different network than the config.
  const factory WalletErrorKind.networkMismatch() =
      WalletErrorKind_NetworkMismatch;

  /// Provisioning was interrupted; reopen to resume the repair.
  const factory WalletErrorKind.provisioningIncomplete() =
      WalletErrorKind_ProvisioningIncomplete;

  /// `create`/`restore` against a location that ALREADY holds a completed
  /// wallet — the typed non-clobber (§6.3). Open the existing wallet instead.
  const factory WalletErrorKind.walletAlreadyExists() =
      WalletErrorKind_WalletAlreadyExists;

  /// Storage corruption — fail-closed, never auto-wiped.
  const factory WalletErrorKind.storeCorrupt() = WalletErrorKind_StoreCorrupt;

  /// Disk full — "free space and retry"; NOT corruption.
  const factory WalletErrorKind.diskFull() = WalletErrorKind_DiskFull;

  /// The wallet store lost a write race to a concurrent engine write
  /// (typically a scan-batch commit mid-sync) past its internal wait AND the
  /// SDK's own bounded retry — TRANSIENT and RETRYABLE, never corruption:
  /// nothing was written, the wallet is unchanged, the same action succeeds
  /// once the store frees up. Render the `walletBusy` copy family ("busy —
  /// try again in a moment"), NEVER the corruption remedy.
  const factory WalletErrorKind.storeBusy() = WalletErrorKind_StoreBusy;

  /// Another instance (this process or another) holds the wallet open —
  /// rejected IS the contract.
  const factory WalletErrorKind.walletAlreadyOpen() =
      WalletErrorKind_WalletAlreadyOpen;

  /// Transient lifecycle phase; retry when it completes.
  const factory WalletErrorKind.walletBusy({required LifecyclePhase phase}) =
      WalletErrorKind_WalletBusy;

  /// Call on a handle in a terminal/wrong lifecycle state.
  const factory WalletErrorKind.invalidState({required LifecyclePhase phase}) =
      WalletErrorKind_InvalidState;

  /// `wipe()` refused while an instance holds the wallet open.
  const factory WalletErrorKind.walletOpen() = WalletErrorKind_WalletOpen;

  /// [SyncServerChoice.predefined] named an id `WalletConfig.syncServers`
  /// does not offer — a host bug, never a user state (the picker renders
  /// only offered entries).
  const factory WalletErrorKind.syncServerNotOffered() =
      WalletErrorKind_SyncServerNotOffered;

  /// The picker's reachability probe could not dial the server, or it did
  /// not answer within the probe budget (15 s) — the transport class,
  /// distinct from `SyncStatus.stalled`. A gated server refusing the key
  /// lands here too. The switch that carried the probe changed NOTHING:
  /// the handle, the loop and the remembered choice are as they were.
  const factory WalletErrorKind.syncServerUnreachable() =
      WalletErrorKind_SyncServerUnreachable;

  /// `wipe()` would destroy `count` non-terminal swap records — surfaced
  /// BEFORE proceeding (third-party wallets stay HD-recoverable from the
  /// phrase).
  const factory WalletErrorKind.wipeWithPendingSwap({required int count}) =
      WalletErrorKind_WipeWithPendingSwap;

  /// `rescanFrom` refused while an OUTBOX send is IN FLIGHT (a queued or
  /// swap-deposit send that has broadcast-committed but not yet settled) —
  /// rebuilding the data DB under it could re-sign the
  /// same payment over different notes (2× pay). Retryable within hours
  /// WHILE SYNC RUNS: the in-flight send resolves by mining (+ ~2 h burial)
  /// or by tx expiry, both observed only by completed sync passes — so the
  /// honest host cue is "a send is still settling; try again in a couple of
  /// hours (keep the app online)", never a moments-scale retry. Like
  /// every rescan fault the handle is consumed (seals + DBs intact) — the
  /// host recovers by re-opening, exactly the existing recover-by-reopen
  /// path. (An INTERACTIVE send's broadcast-but-unmined tx keeps no outbox
  /// row and is NOT fenced — the §4.4 documented residual; a corrupt outbox
  /// row surfaces its own [WalletErrorKind.storeCorrupt] here instead.)
  const factory WalletErrorKind.rescanWithInFlightSend() =
      WalletErrorKind_RescanWithInFlightSend;

  /// #390 — the user-triggered "Check older swap addresses" deep scan was REFUSED,
  /// never run as a silent no-op. `reason` says why (see [SwapAddressCheckRefusal]):
  /// swap is turned off, or a prior check is still outstanding (at most one per
  /// settlement window). The op moved nothing and widened nothing — render the reason
  /// honestly and let the user retry later; NEVER a corruption/dead-end remedy.
  const factory WalletErrorKind.swapAddressCheckRefused({
    required SwapAddressCheckRefusal reason,
  }) = WalletErrorKind_SwapAddressCheckRefused;

  /// A sync/provisioning step could not reach the endpoint (§3.2f). `stall`
  /// is the host-renderable next step: `torUnavailable` (fail-closed under
  /// `TorPolicy.required`) vs `endpointUnreachable`.
  const factory WalletErrorKind.sync_({required StallReason stall}) =
      WalletErrorKind_Sync;

  /// The Zcash network runs consensus rules this build does not implement —
  /// or this endpoint is not on the chain we think it is. The SDK cannot tell
  /// those apart from inside, so there is one kind for both
  /// (`ironwood-nu63-support.md` §2).
  ///
  /// **Signing is refused; reading is not.** Balance, history, receive, seed
  /// backup and viewing-key export all keep working — render "this version
  /// can't send until it's updated, your funds are safe and you can still
  /// receive", never a dead end and never a claim that money is at risk.
  ///
  /// The two branch ids are public protocol constants for a diagnostics or
  /// support surface, not the main path; `endpointBranchId` is null when the
  /// server would not say which network it is on.
  const factory WalletErrorKind.networkUpgradeUnsupported({
    required int expectedBranchId,
    int? endpointBranchId,
    required int judgedAtHeight,
  }) = WalletErrorKind_NetworkUpgradeUnsupported;

  /// This server will not say which network it is on, and the grace the
  /// wallet extends such a server has run out — `by` says how: a day of
  /// blocks, a day on the device clock, or it never began. NOT a network
  /// upgrade and NOT [WalletErrorKind.networkUpgradeUnsupported]'s copy:
  /// nothing is known to have changed, an app update fixes nothing, and the
  /// next step is SWITCH SERVERS (plus "check the device's date and time"
  /// for [GraceExpiry.clock]). `blocksSinceLastCurrent` is the count the
  /// blocks copy names ("…for N blocks"); null for `neverConfirmed`.
  ///
  /// **Signing is refused; reading is not.** Composing and queueing keep
  /// working — a queued send drains on the first pass against a server that
  /// reports its network. Render "your funds are safe and you can still
  /// receive", never a dead end.
  const factory WalletErrorKind.consensusGraceExpired({
    required GraceExpiry by,
    int? blocksSinceLastCurrent,
  }) = WalletErrorKind_ConsensusGraceExpired;

  /// This wallet has not completed a sync pass yet, so it has never checked
  /// which network the server is on — signing is refused until it has (the
  /// first completed pass resolves it). Render the "not synced yet — wait
  /// for sync, or queue this to send later" story, NEVER an update prompt:
  /// nothing is known to be wrong, and composing and queueing keep working.
  const factory WalletErrorKind.consensusNotEvaluated() =
      WalletErrorKind_ConsensusNotEvaluated;

  /// `syncFor` refused: a sync is already running on this handle — the
  /// background loop `startSync` spawned, or another `syncFor`. Nothing ran.
  /// Retryable: call `stopSync` first, or wait for the other `syncFor` to
  /// return. A host bug more often than a user state; never render it as a
  /// network fault.
  const factory WalletErrorKind.syncRunning() = WalletErrorKind_SyncRunning;

  /// Not enough spendable value to fund the send (§3.2h). `available`/`required`
  /// are the audited note-selector's figures; `pendingIncoming` is what is still
  /// confirming — the host renders "you have X spendable, Y arriving, you need Z".
  /// All zatoshis (Dart `int`); never logged (§5.4) — the static `message` is.
  const factory WalletErrorKind.insufficientFunds({
    required PlatformInt64 availableZat,
    required PlatformInt64 requiredZat,
    required PlatformInt64 pendingIncomingZat,
  }) = WalletErrorKind_InsufficientFunds;

  /// A send leg carried no amount (the ZIP-321 donation form) — the host fills the
  /// amount in between parse and confirm.
  const factory WalletErrorKind.sendAmountRequired() =
      WalletErrorKind_SendAmountRequired;

  /// The one-shot proposal token was already consumed (a double-tap on send) — the
  /// notes are never broadcast twice.
  const factory WalletErrorKind.proposalAlreadyUsed() =
      WalletErrorKind_ProposalAlreadyUsed;

  /// The proposal's chain anchor went stale (its TTL elapsed, or the wallet was not
  /// synced far enough) — re-`propose` to show a fresh fee.
  const factory WalletErrorKind.proposalStale() = WalletErrorKind_ProposalStale;

  /// Propose could not prepare a transaction for a reason with no finer mapping
  /// that is deterministic on the input (retrying unchanged re-fails) — the host
  /// renders "couldn't prepare this payment; check the details and try again".
  /// The retryable class is [WalletErrorKind.proposeTransient].
  const factory WalletErrorKind.proposeFailed() = WalletErrorKind_ProposeFailed;

  /// Propose could not prepare a transaction because of a condition the wallet's
  /// own state will clear without the user changing anything — a note whose
  /// witness the scan has not completed, an anchor not yet recorded, an input a
  /// concurrent proposal holds (INC-018 (b)). The host renders "couldn't prepare
  /// this payment just now; try again in a moment" — never "check the details".
  const factory WalletErrorKind.proposeTransient() =
      WalletErrorKind_ProposeTransient;

  /// Create+sign could not complete the transaction — a proving/build fault, or a
  /// spending key the account does not own (a loud catch, never a silent wrong-key
  /// sign). The host renders "couldn't complete this payment". A stale/pruned anchor
  /// folds to [WalletErrorKind.proposalStale] (re-`propose`) instead.
  const factory WalletErrorKind.signFailed() = WalletErrorKind_SignFailed;

  /// A durably-queued send (offline-first) could no longer be funded when the
  /// resubmission machinery tried to re-propose it — the funds it would have spent have
  /// moved. The host drops/redoes it rather than retrying.
  const factory WalletErrorKind.queuedSendStale() =
      WalletErrorKind_QueuedSendStale;

  /// The durable queued-send store is at its cap — let the pending queue drain (sync) before
  /// queueing more. A defensive bound, never a silent drop of a real send.
  const factory WalletErrorKind.queuedSendsFull() =
      WalletErrorKind_QueuedSendsFull;

  /// Too many one-time addresses are in use — the ZIP-320 (TEX) gap-limit ceiling. An
  /// availability bound that moved NO money, and DUAL-NATURED (#315): slots held by transfers
  /// that are still confirming free on their own as they confirm, but slots consumed by sends
  /// that never confirmed do NOT clear by waiting — so the copy must promise neither "just
  /// wait" nor doom ("some may free up as transfers confirm, but this may not clear on its
  /// own; your funds are safe"). The host MUST render this as an ORANGE form-fault, NEVER the
  /// RED "send failed" dead-end (a ceiling spent nothing, so a red failure risks a double-pay
  /// or panic), and NEVER auto-retry it as a fresh send (retries of a one-time-address send
  /// are capped per intent — see [ParkedSend.paused]); any "recover" affordance scopes to
  /// OTHER prior transfers' recoverable funds, never implying THIS send stranded. Reachable now
  /// that TEX two-step signing runs in production (gate-removal, 2e-2b-v-5): a TEX send that
  /// exceeds the one-time-address gap-limit window surfaces this typed ceiling (§3.2i-2
  /// 2e-2b-iii/v-5/vi).
  const factory WalletErrorKind.texSendLimitReached() =
      WalletErrorKind_TexSendLimitReached;

  /// Underlying IO failure not better classified.
  const factory WalletErrorKind.io() = WalletErrorKind_Io;

  /// Forward-compatibility arm: a kind this binding does not know. The
  /// real stable code still rides [WalletApiError.code].
  const factory WalletErrorKind.unknown() = WalletErrorKind_Unknown;
}
