// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `install_device_log`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// SDK version (core + bridge build in lockstep — one workspace version).
/// For host support/diagnostics logging; carries no user or wallet data.
String sdkVersion() => ZecWalletRustLib.instance.api.crateApiMetaSdkVersion();

/// How long after its `deadlineMs` a `WalletHandle.severCustody` call may take
/// to ANSWER, in whole milliseconds: the hard bound on the whole call is
/// `deadlineMs + severAnswerGraceMs()`. A host budgets its duress sequence
/// with it (a constant of this build).
int severAnswerGraceMs() =>
    ZecWalletRustLib.instance.api.crateApiMetaSeverAnswerGraceMs();

/// Set how much the SDK writes to the DEVICE LOG — the HOST's switch (FR-35),
/// reflecting a choice the host's user can see. **OFF until the host calls
/// this**: a host that says nothing gets no device log. Call it right after
/// `RustLib.init()`, before anything touches the wallet, with the user's current
/// choice, and again whenever that choice changes — it takes effect for the next
/// event, with no re-init, is idempotent, and is safe from any thread.
///
/// What is written is this SDK's own `tracing` events, events only, to the
/// platform log — Android logcat, tags `zec_wallet_core` and `zec_wallet`
/// (`adb logcat -s zec_wallet_core:V zec_wallet:V`); Apple's unified log,
/// subsystem `zec_wallet` with those two as categories (`log stream --level
/// info --predicate 'subsystem == "zec_wallet"'`, or Console.app), where the
/// lines are PERSISTED to disk for days; Linux and Windows, the process's
/// stderr, one `<LEVEL> <line>` per event — with the §5.4 never-log
/// policy ENFORCED PER FIELD AT RUNTIME: a field outside the allowlist is
/// withheld and the line says so (`withheld=<n>`). It carries connectivity —
/// never wallet contents, never a server's name, and never a dependency
/// crate's events. What it DOES say, and a host's consent copy should too: that
/// a private transport is in use, how ready and healthy it reports itself, and
/// which arm — `private` or `clearnet` — performed each dial.
///
/// RETURNS the EFFECTIVE level after the call: the one asked for where
/// something here can write it, otherwise [`DeviceLogLevel::Off`] — a platform
/// with no sink (anything but Android, Apple, Linux and Windows), or a process
/// whose global `tracing` default another library already owns. Render THIS in
/// a settings row, not the setting, so the row cannot claim a log that does not
/// exist.
///
/// It does not govern a debug or measurement BUILD's own louder layer: that is a
/// developer's build-time door, never a distributed artifact.
DeviceLogLevel setDeviceLog({required DeviceLogLevel level}) =>
    ZecWalletRustLib.instance.api.crateApiMetaSetDeviceLog(level: level);

/// The EFFECTIVE device-log level right now — what [`set_device_log`] last
/// asked for, where it can actually be written; otherwise
/// [`DeviceLogLevel::Off`]. Changes nothing.
///
/// `Off` means THIS switch writes nothing. It does not describe a debug or
/// measurement BUILD's own louder layer, which logs whatever this reports — a
/// developer's build-time door, never a distributed artifact.
DeviceLogLevel deviceLogLevel() =>
    ZecWalletRustLib.instance.api.crateApiMetaDeviceLogLevel();

/// Stream the SDK's device-log lines to the host: the same lines, under the
/// same [`set_device_log`] switch, that the platform log gets — nothing while
/// it is `Off`, WARN and above at `Errors`, INFO and above at `Detailed`. Call
/// it after `RustLib.init()`, beside `setDeviceLog`, and KEEP DRAINING the
/// stream: the SDK keeps no queue of its own, and sends at most 60 lines a
/// minute to the host (a line over that still reaches the platform log, and
/// leaves a gap in `seq`).
///
/// ONE subscriber per process: a second call replaces the first, whose stream
/// closes. That is how a hot restart or a re-subscribe after unlock takes over;
/// a host with two consumers fans out on its own side.
///
/// Any `wipe`, `wipeForce` or `severCustody` call — a failed one included —
/// closes this stream and sets the device log `Off` before it does anything
/// else, and no line is sent after that. Nothing re-opens it on its own: the
/// host re-arms with `setDeviceLog` and `watchDeviceLog`, except on a duress
/// path, where it must not.
///
/// The stream never errors, even when nothing can feed it. So after
/// `setDeviceLog`, read `deviceLogLevel()`. If it answers `Off` although you
/// asked for more, no layer is installed (no platform sink, or another
/// library took the process's `tracing` default first), and this stream will
/// stay silent.
Stream<DeviceLogLine> watchDeviceLog() =>
    ZecWalletRustLib.instance.api.crateApiMetaWatchDeviceLog();

/// How much of the SDK's own diagnostics the HOST lets reach the device log
/// (FR-35). The three settings are the maintainer's (2026-09-19): *"'Off' /
/// 'Errors only' / 'Detailed logging'"*. Which of them is the DEFAULT in a
/// debug build, in production, or for a given user is the HOST's decision and
/// lives in a setting its user can see; this SDK's own default is [`Off`].
///
/// There is no level above [`Detailed`]: a setting a host could raise further
/// would be a second road to DEBUG on a user's phone, and the measurement
/// build is already the developer's door for that.
///
/// [`Off`]: DeviceLogLevel::Off
/// [`Detailed`]: DeviceLogLevel::Detailed
enum DeviceLogLevel {
  /// Nothing is written. What a host that says nothing gets.
  off,

  /// WARN and above: something went wrong and the wallet carried on — a
  /// private path that would not connect, a fall-back to clearnet, a stalled
  /// sync. Not the routine lines.
  errors,

  /// INFO and above: `Errors`, plus the connectivity narrative — the host
  /// transport's lifecycle and one `wallet.dial` line per dial.
  detailed,
}

/// One line of the SDK's device log, as [`watch_device_log`] delivers it.
///
/// `text` is exactly the line the platform log is handed for the same event,
/// before any per-platform prefix: printable ASCII, at most 512 bytes (then
/// `...`), with every field outside the §5.4 allowlist withheld and counted
/// (`withheld=<n>`). No timestamp: stamp it on receipt.
///
/// `text` and `tag` are CONTROL-safe, not DELIMITER-safe: they hold no newline
/// or other control character, so they cannot forge a second line in a
/// line-oriented log, but they can hold `"`, `\`, `,`, `|`, `=` and spaces. A
/// host that puts them into JSON, CSV or any other structured format must
/// escape them for that format.
class DeviceLogLine {
  /// Counts every line the log produced while it was on, delivered or not,
  /// so within one subscription a gap is a line this stream did not get (the
  /// host budget, or no stream registered at that moment). Restarts at 0 when
  /// a wipe begins. It cannot show lines posted to an isolate that died
  /// before reading them.
  final BigInt seq;
  final DeviceLogSeverity severity;

  /// `zec_wallet_core` or `zec_wallet` — which half of the SDK emitted it.
  final String tag;
  final String text;

  const DeviceLogLine({
    required this.seq,
    required this.severity,
    required this.tag,
    required this.text,
  });

  @override
  int get hashCode =>
      seq.hashCode ^ severity.hashCode ^ tag.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceLogLine &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          severity == other.severity &&
          tag == other.tag &&
          text == other.text;
}

/// How serious one device-log line is — the event's own level.
enum DeviceLogSeverity {
  /// An ERROR event.
  error,

  /// A WARN event: something went wrong and the wallet carried on.
  warn,

  /// An INFO event: the connectivity narrative (`Detailed` only).
  info,
}
