// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Estimate the restore birthday HEIGHT from an approximate wallet-creation
/// time (UNIX SECONDS, UTC). CONSERVATIVE FLOOR over the bundled checkpoints —
/// never returns a height past the given time, so a restore can never silently
/// skip the user's notes (spec §3.6). Clamped to [Sapling activation, last
/// bundled checkpoint]; a pre-1970 (negative) input clamps to activation.
///
/// At the bridge this is the primitive (network + unix seconds → height); the
/// Dart facade (§3.3, W3) wraps it with a `DateTime` and the async surface.
int estimateBirthday({
  required Network network,
  required PlatformInt64 approxUnixSecs,
}) => ZecWalletRustLib.instance.api.crateApiRestoreEstimateBirthday(
  network: network,
  approxUnixSecs: approxUnixSecs,
);
