// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'state.dart';
import 'swap.dart';

// These functions are ignored because they are not marked as `pub`: `sample_quote`, `sample_submit_results`, `sample_swap_record`, `sample_swap_statuses`, `sample_sync_statuses`, `sample_tor_states`, `sample_tx_rows`, `sample_txid`, `sample_wallet_state`, `zat`

/// Build the bundle. Pure constants; safe to call anywhere, any time.
SelftestBundle selftestBundle() =>
    ZecWalletRustLib.instance.api.crateApiSelftestSelftestBundle();

/// Always throws `RW-LIFE-001` (`walletAlreadyOpen`) — Dart asserts
/// catch-BY-TYPE on [WalletApiError] and reads the stable code.
void selftestThrowWalletError() =>
    ZecWalletRustLib.instance.api.crateApiSelftestSelftestThrowWalletError();

/// Always throws `RW-SWAP-003` (`quoteExpired`) — same contract for
/// [SwapApiError].
void selftestThrowSwapError() =>
    ZecWalletRustLib.instance.api.crateApiSelftestSelftestThrowSwapError();

/// Inbound crossing: a [QuoteRequest] built in Dart runs through the REAL
/// bridge→core conversion (including the zatoshi bounds check) and reports
/// the typed outcome. Proves Dart→Rust DTO integrity without touching any
/// provider.
void selftestQuoteRequestRoundtrip({required QuoteRequest request}) =>
    ZecWalletRustLib.instance.api.crateApiSelftestSelftestQuoteRequestRoundtrip(
      request: request,
    );

/// Run the §4.3a custody round-trip against THIS device's real vault
/// (selftest-scoped identities; production custody untouched). Async —
/// real Keystore/keychain I/O rides the FRB worker pool, not the Dart
/// thread. Diagnostic surface like everything in this module: hosts must
/// not ship UX on it — and must NOT call it concurrently (the selftest
/// alias scan races; one caller reports a false FAIL; see the core fn).
Future<CustodyReport> selftestSeedCustody() =>
    ZecWalletRustLib.instance.api.crateApiSelftestSelftestSeedCustody();

/// §4.3a device-E2E custody report (the FRB face of
/// `zec_wallet_core::CustodySelftestReport`). Non-secret by construction:
/// booleans + the measured tier label.
class CustodyReport {
  /// Measured vault tier: "strongbox" | "tee" | "software_keystore" |
  /// "apple_keychain" | "apple_secure_enclave" | "unknown" (forward arm — a
  /// newer core may add tiers; the LABEL is diagnostic, the `degraded` bool is
  /// the load-bearing predicate). `apple_secure_enclave` is the FR-14 chunk 2
  /// hardware-key tier; `apple_keychain` is the best-effort raw fallback.
  final String tier;

  /// §4.3a degraded-custody predicate, surfaced as data.
  final bool degraded;
  final bool roundtripOk;
  final bool bindingRejectsTamperedBlob;
  final bool wipeSevers;

  const CustodyReport({
    required this.tier,
    required this.degraded,
    required this.roundtripOk,
    required this.bindingRejectsTamperedBlob,
    required this.wipeSevers,
  });

  @override
  int get hashCode =>
      tier.hashCode ^
      degraded.hashCode ^
      roundtripOk.hashCode ^
      bindingRejectsTamperedBlob.hashCode ^
      wipeSevers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustodyReport &&
          runtimeType == other.runtimeType &&
          tier == other.tier &&
          degraded == other.degraded &&
          roundtripOk == other.roundtripOk &&
          bindingRejectsTamperedBlob == other.bindingRejectsTamperedBlob &&
          wipeSevers == other.wipeSevers;
}

/// Everything outbound, one call: a full DTO tree built Rust-side and
/// crossed in a single hop. Dart asserts shape + values; the integration
/// test is "did every field survive".
class SelftestBundle {
  /// A populated snapshot (balance / scanning sync / active-Tor state).
  final WalletState walletState;

  /// Every sync-status arm this binding knows, including `unknown`.
  final List<SyncStatus> syncStatuses;

  /// Every Tor-state arm.
  final List<TorState> torStates;

  /// History rows covering every REAL tx-status arm (the `Unknown`
  /// arm's bridge crossing is proven by the status vectors above).
  final List<TxSummary> txRows;

  /// Every per-tx submit outcome, including the `unknown` arm.
  final List<TxSubmitResult> submitResults;

  /// A quote with a fully-populated privacy disclosure.
  final SwapQuote quote;

  /// Every swap-status arm.
  final List<SwapStatus> swapStatuses;

  /// A swap history row.
  final SwapRecord swapRecord;

  const SelftestBundle({
    required this.walletState,
    required this.syncStatuses,
    required this.torStates,
    required this.txRows,
    required this.submitResults,
    required this.quote,
    required this.swapStatuses,
    required this.swapRecord,
  });

  @override
  int get hashCode =>
      walletState.hashCode ^
      syncStatuses.hashCode ^
      torStates.hashCode ^
      txRows.hashCode ^
      submitResults.hashCode ^
      quote.hashCode ^
      swapStatuses.hashCode ^
      swapRecord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelftestBundle &&
          runtimeType == other.runtimeType &&
          walletState == other.walletState &&
          syncStatuses == other.syncStatuses &&
          torStates == other.torStates &&
          txRows == other.txRows &&
          submitResults == other.submitResults &&
          quote == other.quote &&
          swapStatuses == other.swapStatuses &&
          swapRecord == other.swapRecord;
}
