// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'swap.freezed.dart';

/// Provider-namespaced asset identifier (e.g. chain `"eth"`, symbol
/// `"usdc"`).
class AssetId {
  final String chain;
  final String symbol;

  const AssetId({required this.chain, required this.symbol});

  @override
  int get hashCode => chain.hashCode ^ symbol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetId &&
          runtimeType == other.runtimeType &&
          chain == other.chain &&
          symbol == other.symbol;
}

/// One thing the provider learns. Render every item; the list is the
/// disclosure.
enum DisclosureItem {
  /// The provider links the two assets to one user intent.
  crossAssetLink,

  /// Amounts on both sides.
  amounts,

  /// The destination address.
  destinationAddress,

  /// The source address.
  sourceAddress,

  /// The caller's IP address — unless the request rides Tor.
  ipUnlessTor,

  /// Forward-compatibility arm — render as a generic disclosure line.
  unknown,
}

@freezed
sealed class ExactSide with _$ExactSide {
  const ExactSide._();

  /// "I will pay exactly this much in."
  const factory ExactSide.in_({required SwapAmount amount}) = ExactSide_In;

  /// "I want exactly this much out."
  const factory ExactSide.out({required SwapAmount amount}) = ExactSide_Out;
}

/// Quote request.
class QuoteRequest {
  final SwapDirection direction;
  final ExactSide exact;

  /// Basis points; requests beyond the SDK's hard ceiling are rejected
  /// typed. The SDK default is 200 (2%).
  final int slippageToleranceBps;

  /// OutOfZec: the foreign receive address (REQUIRED; a Zcash address is
  /// rejected — a ZEC→ZEC "swap" is a fee-burning provider round-trip).
  /// IntoZec: must be `null` (delivery goes to the wallet's own fresh
  /// address).
  final String? destination;

  /// IntoZec: source-chain refund target. OutOfZec: IGNORED — the SDK
  /// always supplies a fresh wallet transparent address as the refund
  /// target (single-use, never recycled).
  final String? refundAddress;

  const QuoteRequest({
    required this.direction,
    required this.exact,
    required this.slippageToleranceBps,
    this.destination,
    this.refundAddress,
  });

  @override
  int get hashCode =>
      direction.hashCode ^
      exact.hashCode ^
      slippageToleranceBps.hashCode ^
      destination.hashCode ^
      refundAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuoteRequest &&
          runtimeType == other.runtimeType &&
          direction == other.direction &&
          exact == other.exact &&
          slippageToleranceBps == other.slippageToleranceBps &&
          destination == other.destination &&
          refundAddress == other.refundAddress;
}

@freezed
sealed class SwapAmount with _$SwapAmount {
  const SwapAmount._();

  /// ZEC side, zatoshis.
  const factory SwapAmount.zec({required PlatformInt64 zat}) = SwapAmount_Zec;

  /// Foreign side, decimal string (provider precision preserved).
  const factory SwapAmount.foreign({required String amount}) =
      SwapAmount_Foreign;
}

@freezed
sealed class SwapDirection with _$SwapDirection {
  const SwapDirection._();

  /// other asset → ZEC. Ends shielded ONLY because the SDK proposes the
  /// final shield step — delivery lands on a fresh transparent address
  /// first, and that leg is on-chain-visible.
  const factory SwapDirection.intoZec({required AssetId from}) =
      SwapDirection_IntoZec;

  /// ZEC → other asset. DE-SHIELDS by construction: the deposit send is a
  /// shielded→transparent tx; amount + destination are exposed to the
  /// provider network.
  const factory SwapDirection.outOfZec({required AssetId to}) =
      SwapDirection_OutOfZec;

  /// Forward-compatibility arm — keep a default arm when switching.
  const factory SwapDirection.unknown() = SwapDirection_Unknown;
}

/// Terminal failure classification.
enum SwapFailureCode {
  /// Provider reported failure.
  providerFailure,

  /// Provider response violated the protocol contract.
  providerProtocol,

  /// Deposit window lapsed before a deposit confirmed.
  expired,

  /// The provider no longer recognizes this swap (#367): a definitive
  /// not-found answered several consecutive status polls — the order was
  /// most likely cleaned up provider-side after it expired. SYNTHESIZED by
  /// the SDK's poll policy, never provider-sent. Copy note: a deposit that
  /// DID land on such an order still refunds provider-side to the recorded
  /// refund address — do not assert loss.
  notFound,

  /// Forward-compatibility arm.
  unknown,
}

/// The §3.5 monotonic-toward-off kill severity a host may DECLARE at swap
/// construction (e.g. lowered from its signed network manifest). Ordering is
/// `Live` < `WindDown` < `Hard`; the SDK only ever escalates toward off (a
/// forged/replayed "on" can only make it MORE-off, never resurrect swap).
enum SwapKill {
  /// Normal operation — quote/execute/poll all run.
  live,

  /// New quotes/executes are refused; any in-flight swap keeps POLLING to a
  /// terminal status (observational; funds settle/refund provider-side).
  windDown,

  /// Zero swap traffic — new AND in-flight polling stop, no synthetic terminal
  /// (the host renders "tracking unavailable" from its own state).
  hard,

  /// Forward-compatibility arm (G2 policy). An UNRECOGNIZED declared kill is a
  /// host bug; the SDK treats it as the strongest kill it understands (`Hard`,
  /// fail-safe) — an unknown directive must never resurrect swap.
  unknown,
}

/// The observed TERMINAL a host pins into a record via `recordSwapOutcome`
/// (#367) — the coarse terminal arms only, no payloads (txids/amounts stay
/// live-polled, never durable). A pinned outcome is what the home row renders
/// after the tracking stream saw the terminal while the user was away.
enum SwapOutcome { success, refunded, failed }

/// Honest per-direction privacy surfacing AS DATA.
class SwapPrivacyDisclosure {
  /// Funds end in the shielded pool (via the final shield step).
  final bool endsShielded;

  /// The deposit de-shields funds.
  final bool deshields;

  /// Provider-side legs are PUBLIC chain data.
  final bool providerLegsTransparent;

  /// What the provider learns.
  final List<DisclosureItem> providerSees;

  const SwapPrivacyDisclosure({
    required this.endsShielded,
    required this.deshields,
    required this.providerLegsTransparent,
    required this.providerSees,
  });

  @override
  int get hashCode =>
      endsShielded.hashCode ^
      deshields.hashCode ^
      providerLegsTransparent.hashCode ^
      providerSees.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapPrivacyDisclosure &&
          runtimeType == other.runtimeType &&
          endsShielded == other.endsShielded &&
          deshields == other.deshields &&
          providerLegsTransparent == other.providerLegsTransparent &&
          providerSees == other.providerSees;
}

/// Live-provider construction config for the NEAR Intents adapter — the
/// `enableNearSwap` entry (spec §3.5; the `swap-near` feature). `endpoint` is
/// the 1Click base URL (validated at construction, not at first dial).
class SwapProviderConfig {
  /// Provider base URL (e.g. `https://1click.chaindefuser.com`).
  final String endpoint;

  /// OPTIONAL provider auth token. A §5.4 NEVER-log value: wrapped in a
  /// `Zeroizing` buffer in Rust at the boundary and never logged. Dart memory
  /// cannot be zeroized — the documented §10 exposure, identical framing to
  /// the mnemonic crossing; keep it minimal-residency host-side.
  final String? jwt;

  const SwapProviderConfig({required this.endpoint, this.jwt});

  @override
  int get hashCode => endpoint.hashCode ^ jwt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapProviderConfig &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          jwt == other.jwt;
}

/// A bounds-checked quote. `expiresAt` is unix seconds DISPLAY-ONLY;
/// deadline enforcement happens Rust-side against monotonic + wall clocks
/// (either says expired ⇒ rejected), so neither a regressed wall clock nor a
/// suspend-paused monotonic clock can revive a dead quote.
///
/// **#367:** `expiresAt` is the ACTIONABLE deadline — already clamped to the
/// wall window the SDK itself enforces, minus the execute margin: the exact
/// instant `swapExecute` starts refusing `QuoteExpired`. Render the countdown
/// from it directly; it cannot disagree with the execute gate (the raw
/// provider echo — hours past the real window — never reaches this DTO).
class SwapQuote {
  /// The SDK-minted swap id (opaque, bounded; ADR-0555 — never the deposit address).
  final String id;

  /// Provider deposit address (quote-generated, single-use).
  final String depositAddress;

  /// A destination tag / memo the provider REQUIRES on the deposit when the
  /// source chain has one (XRP tag, Cosmos/Stellar/EOS memo). IntoZec only —
  /// the user attaches it to their external deposit; render it on the deposit
  /// screen so the deposit isn't lost. `None` for chains without the concept.
  /// A §5.4 NEVER-log value, like `deposit_address`.
  final String? depositMemo;

  /// Unix seconds, display-only (see type docs).
  final PlatformInt64 expiresAt;

  /// Decimal string — what goes in.
  final String amountIn;

  /// Decimal string — the minimum that comes out.
  final String minAmountOut;

  /// Whichever side is ZEC, exact (zatoshis).
  final PlatformInt64 zecSideZat;

  /// The provider's echo of the refund address the SDK sent (verified to
  /// match before anything downstream).
  final String? refundTo;

  /// Render this — it expresses everything the user must acknowledge.
  final SwapPrivacyDisclosure disclosure;

  /// FR-17 (#396): the SDK-minted spend-binding nonce for this quote (32 opaque
  /// bytes, random, NOT key material) — always set on a quote returned by
  /// `swapQuote`; the nullability is a WIRE ARTIFACT of the core type (network
  /// adapters populate null and the service overwrites at issue), never an
  /// expected runtime state for a served quote.
  ///
  /// FR-17 ENFORCEMENT PREREQUISITE: recording this only protects the OutOfZec
  /// deposit if the host registered the BOUND C-ABI seed supplier
  /// (`zec_wallet_register_seed_port_bound`) with a comparing callback; a v1
  /// supplier drops the binding (silent no-op). Do not log it. A host with external seed custody records it at its
  /// execute-authorize bracket; the OutOfZec deposit's native seed pull presents
  /// the same value, so the host's supplier fail-closes a sign for anything the
  /// user did not review. Hosts without a native seed port can ignore it. Do
  /// not log it.
  final Uint8List? binding;

  const SwapQuote({
    required this.id,
    required this.depositAddress,
    this.depositMemo,
    required this.expiresAt,
    required this.amountIn,
    required this.minAmountOut,
    required this.zecSideZat,
    this.refundTo,
    required this.disclosure,
    this.binding,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      depositAddress.hashCode ^
      depositMemo.hashCode ^
      expiresAt.hashCode ^
      amountIn.hashCode ^
      minAmountOut.hashCode ^
      zecSideZat.hashCode ^
      refundTo.hashCode ^
      disclosure.hashCode ^
      binding.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapQuote &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          depositAddress == other.depositAddress &&
          depositMemo == other.depositMemo &&
          expiresAt == other.expiresAt &&
          amountIn == other.amountIn &&
          minAmountOut == other.minAmountOut &&
          zecSideZat == other.zecSideZat &&
          refundTo == other.refundTo &&
          disclosure == other.disclosure &&
          binding == other.binding;
}

/// One durable in-flight swap (W-swap-5, #366) — the home row written at
/// execute and listed by `listInFlightSwaps` after a process restart, screen
/// re-entry, or session swap. Lives in the wallet's encrypted store, in its
/// own table — records stay READABLE even when swap is disabled or killed
/// (local reads are not swap traffic, §3.5). The row asserts exactly "an
/// order was registered at execute" — plus, since #367, at most one PINNED
/// observed terminal (`outcome`): feed `id` to `watchSwapStatus` for live
/// provider truth, call `recordSwapOutcome` when the stream observes a
/// TERMINAL status, and call `dismissSwapRecord` only on USER intent (the
/// terminal card's Done after the outcome rendered, or an explicit Remove).
class SwapRecord {
  /// The SDK-minted swap id — THE re-attach handle for `watchSwapStatus`.
  /// §5.4 render-never-log by policy; since S8 it is NEVER the provider's
  /// deposit address (ADR-0555: that is data inside the record).
  final String id;
  final SwapRecordDirection direction;

  /// Unix seconds, display-only.
  final PlatformInt64 createdAt;

  /// When the DEPOSIT must land (OutOfZec: the wallet's own clamped send
  /// window; IntoZec: the window the USER must beat). Unix seconds,
  /// display-only; absent if the recording build predates it.
  final PlatformInt64? depositDeadline;

  /// The record's self-lapse bound (execute-time + the settlement
  /// ceiling): past this the row stops listing on its own. Unix seconds,
  /// display-only.
  final PlatformInt64 expiresAt;

  /// The PINNED observed terminal (#367) — `null` while in flight (and for
  /// a pin written by a newer SDK this build doesn't recognize: fail-honest,
  /// the live poll re-reveals truth). Render the terminal row state from it.
  final SwapOutcome? outcome;

  const SwapRecord({
    required this.id,
    required this.direction,
    required this.createdAt,
    this.depositDeadline,
    required this.expiresAt,
    this.outcome,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      direction.hashCode ^
      createdAt.hashCode ^
      depositDeadline.hashCode ^
      expiresAt.hashCode ^
      outcome.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          direction == other.direction &&
          createdAt == other.createdAt &&
          depositDeadline == other.depositDeadline &&
          expiresAt == other.expiresAt &&
          outcome == other.outcome;
}

/// Direction arm of a durable in-flight swap record — COARSE by design: the
/// record stores no asset names or amounts (data minimization; the host polls
/// provider truth live via `watchSwapStatus`). Distinct from [SwapDirection]
/// (whose arms carry the quoted [AssetId]) precisely because the durable row
/// has no assets to carry.
enum SwapRecordDirection {
  /// Other asset → ZEC: the USER deposits externally.
  intoZec,

  /// ZEC → other asset: the WALLET sends the deposit.
  outOfZec,

  /// Forward-compatibility arm — render as a generic in-flight swap.
  unknown,
}

@freezed
sealed class SwapStatus with _$SwapStatus {
  const SwapStatus._();

  /// Waiting for the deposit; `expiresAt` unix seconds, display-only.
  const factory SwapStatus.pendingDeposit({required PlatformInt64 expiresAt}) =
      SwapStatus_PendingDeposit;

  /// Partial deposit landed: top up by `deadline` or the provider
  /// refunds. Decimal strings (foreign side).
  const factory SwapStatus.underDeposited({
    required String received,
    required String missing,
    required PlatformInt64 deadline,
  }) = SwapStatus_UnderDeposited;
  const factory SwapStatus.depositDetected() = SwapStatus_DepositDetected;
  const factory SwapStatus.processing() = SwapStatus_Processing;

  /// Terminal success. `realizedSlippageBps` when the provider reports it.
  const factory SwapStatus.success({
    String? outTxid,
    int? realizedSlippageBps,
  }) = SwapStatus_Success;

  /// Terminal: refunded — a NAMED outcome with its own UX row, not an
  /// error.
  const factory SwapStatus.refunded({String? refundTxid}) = SwapStatus_Refunded;

  /// Terminal failure.
  const factory SwapStatus.failed({required SwapFailureCode code}) =
      SwapStatus_Failed;

  /// Forward-compatibility arm — render as "status unavailable".
  const factory SwapStatus.unknown() = SwapStatus_Unknown;
}

/// One pickable source asset for the host's IntoZec token picker (§3.3b D5 / ADR-0530, IZ-2) — the
/// flat bridge mirror of the core `TokenInfo`. The host renders `(chain, symbol)` with a BUNDLED
/// icon + a display label (never CDN-fetched, §5.2) and threads `(chain, symbol)` back as the
/// `QuoteRequest` asset; `provider_asset_id` is the stable unique list key, `decimals` the foreign-
/// amount precision, `price_usd` display-only (sort/label, NEVER funds math). §5.4: no token field
/// is ever logged.
class SwapToken {
  final String chain;
  final String symbol;
  final int decimals;
  final String providerAssetId;
  final double? priceUsd;

  const SwapToken({
    required this.chain,
    required this.symbol,
    required this.decimals,
    required this.providerAssetId,
    this.priceUsd,
  });

  @override
  int get hashCode =>
      chain.hashCode ^
      symbol.hashCode ^
      decimals.hashCode ^
      providerAssetId.hashCode ^
      priceUsd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapToken &&
          runtimeType == other.runtimeType &&
          chain == other.chain &&
          symbol == other.symbol &&
          decimals == other.decimals &&
          providerAssetId == other.providerAssetId &&
          priceUsd == other.priceUsd;
}

/// The result of `swapListTokens` (§3.3b D5/L6, IZ-2): the filtered picker list + a freshness flag.
/// `fresh == false` ⇒ the live fetch failed and these are the LAST good tokens served from cache —
/// the host shows a "couldn't refresh, showing cached" banner (honest degradation), never a blank
/// picker. An empty `tokens` with `fresh == true` is the honest "no assets available right now."
class SwapTokenList {
  final List<SwapToken> tokens;
  final bool fresh;

  const SwapTokenList({required this.tokens, required this.fresh});

  @override
  int get hashCode => tokens.hashCode ^ fresh.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapTokenList &&
          runtimeType == other.runtimeType &&
          tokens == other.tokens &&
          fresh == other.fresh;
}
