// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'config.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'payments.dart';
import 'state.dart';
import 'swap.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WalletHandle>>
abstract class WalletHandle implements RustOpaqueInterface {
  /// **AUTHORIZE a parked send NOW** (FR-23-b) — sign a send the user already committed, at this
  /// user-present moment, instead of waiting for a background pass to sign it. Pass BOTH the `id`
  /// AND the `createdAt` from the [`ParkedSend`] the user acted on.
  ///
  /// **Call this INSIDE your authorize-spend bracket** (`WalletSendAuthorizer.authorizeSpend`),
  /// with your per-spend credential staged — that is the whole point: a custody model with no
  /// standing signing capability (per-spend passphrase, biometric-per-send, external signer)
  /// cannot sign at an unattended background drain, so its offline queue could never drain. This
  /// is the SDK's answer, and it is what makes `walletOfflineQueueSupportedProvider = true`
  /// honest at host custody. Hosts with a BOUND native seed port must stage the seed for THIS
  /// row's `ParkedSend.binding` (FR-17) — a stage recorded for any other row is refused and the
  /// send stays parked (funds safe), never wrongly signed.
  ///
  /// ONE ROW PER CALL, ONE CALL PER BRACKET: the row's own binding rides the seed pull, so one
  /// staged credential serves exactly one row. An "authorize all" affordance is a LOOP over
  /// brackets host-side — never one prompt covering N rows.
  ///
  /// Contrast `retryParkedSend`, which only re-arms the retry budget of a `paused` one-time-address
  /// row and signs NOTHING. They compose: re-arm a paused row first, then authorize it.
  ///
  /// MONEY-SAFE: it moves only the TIMING of the signature — the payment itself was committed when
  /// the user queued it. Nothing new is decided here, the wallet's double-send guard is unchanged
  /// (the wallet's own background pass and this call can never both sign one send), and a wrong
  /// staged seed is refused before any transaction exists. Returns a
  /// [`ParkedAuthorization`] — read its HOST CONTRACT:
  /// only `signed` may be phrased as "sending now", and `stillQueued` is NOT a failure.
  /// §5.4: ids/timestamps only — no amount or address crosses. Throws
  /// [WalletErrorKind.invalidState] on a closed handle; a watch-only wallet throws
  /// [WalletErrorKind.watchOnly] (structurally seedless — it can never sign).
  Future<ParkedAuthorization> authorizeParkedSend({
    required PlatformInt64 id,
    required PlatformInt64 createdAt,
  });

  /// The account birthday height — the scan floor a rescan rebuilds from and
  /// the lowest useful `rescanFrom` target. Clamp a rescan date-picker's
  /// DEFAULT with this instead of a blind "one year ago": map the default
  /// date to a height with `estimateBirthday` and take the max of the two —
  /// on any wallet younger than a year the blind default silently costs
  /// hours of scanning. Do NOT max-clamp a date the USER picked: an
  /// explicitly earlier pick is the post-restore recovery path (this height
  /// may itself be a too-recent restore estimate, and rescan exists
  /// precisely to go below it), so clamping it up to this floor silently
  /// no-ops that recovery. `null` before the account is provisioned (first
  /// sync hasn't run). A height, never money.
  /// [WalletErrorKind.invalidState] if the handle is closed.
  Future<int?> birthdayHeight();

  /// CANCEL a parked (queued) send the host listed via `listParkedSends` — the user-facing escape
  /// hatch to discard a TEX send waiting for the multi-step path (which would otherwise AUTO-BROADCAST
  /// once that path is enabled — see the [`ParkedSend`] DOUBLE-PAY
  /// CAUTION; cancel is the SAFE counter-affordance, never a re-send). Pass BOTH the `id` AND the
  /// `createdAt` from the [`ParkedSend`] the user is cancelling. Returns `true` if it was removed,
  /// `false` if it was already gone / began sending (post-multi-step-enable) / its rowid was reused
  /// (idempotent). On `false`, re-read `listParkedSends` — but do NOT present it as definitively
  /// "cancelled" nor invite a re-send: a send that began sending has LEFT the parked surface, so the
  /// payment may be IN-FLIGHT (direct the user to the activity list; a re-send risks a DOUBLE-PAY).
  /// IRREVERSIBLE + UNCONFIRMED — it discards the committed intent immediately; the host MUST confirm
  /// before calling (the confirm dialog is v-4b). MONEY-SAFE: only a still-`Queued` intent is deleted
  /// (no note reserved, nothing signed, no tx on-chain — cancel cannot strand funds), and the `createdAt`
  /// identity pin makes a reused id cancel NOTHING. §5.4: ids/timestamps only — no amount or address
  /// crosses. Throws [WalletErrorKind.invalidState] on a closed handle.
  Future<bool> cancelParkedSend({
    required PlatformInt64 id,
    required PlatformInt64 createdAt,
  });

  /// #390 — "Check older swap addresses": widen the range the wallet watches so the
  /// normal sync surfaces older swap deposits/refunds a SEED-ONLY RESTORE left unchecked
  /// (a wallet with a long swap history restored from its phrase). It does NOT itself
  /// find funds — it WIDENS, then any older swap money appears in the balance over the
  /// next minutes of sync. Returns a counts-only [SwapAddressCheckReport] — render
  /// "checking older swap addresses as your wallet syncs; anything found appears in your
  /// balance", NEVER "found X". Rerunnable (each accepted run goes deeper).
  ///
  /// SURFACE IT in an overflow entry ADJACENT to Rescan — but NOT behind the rescan
  /// package-custody gate: this runs entirely over the live session (the one-time-address
  /// check class). Throws [WalletErrorKind.swapAddressCheckRefused] (branch on
  /// `reason`): `swapDisabled` (swap is off — retry when back), `checkOutstanding` (a
  /// prior check is still running — one per settlement window, try later);
  /// [WalletErrorKind.invalidState] on a closed handle. Being elective, prefer to run it
  /// when the transport is healthy (not degraded-Tor). It moves NO money and needs no
  /// authorizer.
  Future<SwapAddressCheckReport> checkOlderSwapAddresses();

  /// Close the wallet: stop and join the sync loop, QUIESCE any straggling
  /// scan-batch section (a bounded wait — v-5c finding #2), then release the
  /// single-writer lock and close storage on a background thread — all
  /// before this future resolves, so a subsequent `open` at the same
  /// `dbDir` never observes a half-closed DB. BOUNDED residual: a wedged
  /// straggler past the quiesce budget can keep the lock alive briefly
  /// after this resolves (integrity still holds; the lock frees the moment
  /// it ends — an immediate re-`open` should tolerate a transient
  /// `WalletAlreadyOpen` with a short retry). The chain is the source of
  /// truth, so closing loses nothing. Idempotent: a second call is a no-op.
  ///
  /// A registered host dialer's outstanding operations are closed with the
  /// wallet (FR-39): every one still waiting on the host is marked closed,
  /// and a connection the host delivers to one afterwards is handed back to
  /// the host's `close`. Nothing the host still holds is freed early. The
  /// operation table is process-wide — with two wallets open at once, this
  /// also fails the other wallet's in-flight dials (typed, retryable).
  Future<void> close();

  /// Create a BRAND-NEW wallet — a fresh 24-word seed is generated in Rust
  /// (`OsRng`), sealed per `config.seedPersistence`, and used entirely
  /// Rust-side; the seed NEVER crosses this bridge. The wallet is then
  /// opened and returned ready to sync.
  ///
  /// Throws [WalletErrorKind.walletAlreadyExists] if a completed wallet is
  /// already provisioned at `config.dbDir` (never a silent clobber — open it
  /// instead), and the usual config-validation errors (endpoint rules, …).
  /// To RESTORE an existing wallet from its recovery phrase, use the restore
  /// entry point (a separate, key-material-bearing call).
  static Future<WalletHandle> createGenerated({required WalletConfig config}) =>
      ZecWalletRustLib.instance.api.crateApiWalletWalletHandleCreateGenerated(
        config: config,
      );

  /// Create a WATCH-ONLY wallet from an exported viewing key (#397, spec
  /// §3.7 D2 / ADR-0538 — the consumer half of `exportUfvk`). Full read
  /// path (sync, balance, history, receive addresses); every spend-class
  /// surface — send, shield, swap, `revealMnemonic`, rescan — throws the
  /// STRUCTURAL [WalletErrorKind.watchOnly] (nothing to retry: this wallet
  /// holds no spending keys, by design). Reopen later with the plain
  /// `open`; a pre-#397 binary refuses the store typed instead of
  /// half-opening it.
  ///
  /// `ufvk` must be the standard unified encoding for `config.network`
  /// (`uview1…` / `uviewtest1…`): garbage, truncation and a wrong-network
  /// key all throw [WalletErrorKind.invalidViewingKey] BEFORE anything is
  /// written. `birthdayHeight` is REQUIRED — use the exporting wallet's
  /// birthday (or `estimateBirthday` from a date); too high silently hides
  /// older history (the same contract as a seed restore), too low only
  /// scans longer. `config.seedPersistence` is ignored (there is no seed).
  static Future<WalletHandle> createWatchOnly({
    required WalletConfig config,
    required String ufvk,
    required int birthdayHeight,
  }) => ZecWalletRustLib.instance.api.crateApiWalletWalletHandleCreateWatchOnly(
    config: config,
    ufvk: ufvk,
    birthdayHeight: birthdayHeight,
  );

  /// Provision a NEW host-custodied-seed wallet at `config.dbDir` (FR-15), pulling
  /// the seed from the C-ABI seed port the HOST registered (in its own native
  /// library) via `zec_wallet_register_seed_port`. The seed crosses
  /// native-to-native from the host lib into this one and NEVER through Dart — use
  /// this INSTEAD of `createGenerated`/`restore` for the keys-in-host integration
  /// (Relim ADR-0031): there is no mnemonic and no Dart-side seed. The SDK PINS
  /// `config.seedPersistence` to `none` (a host-custodied seed is never sealed at
  /// rest) — any other value is enforced to `none`, not an error.
  ///
  /// The returned handle ALREADY has the port attached (account import + signing
  /// pull it on demand), so no host-side close/reopen dance is needed.
  ///
  /// `freshlyGenerated` (FR-24, default `false`/omitted): pass `true` ONLY when
  /// the supplied seed was minted BRAND-NEW in this same onboarding flow — no
  /// address of it ever derived or shared, so it can have NO chain history — and
  /// has NEVER existed anywhere else before. (The load-bearing property is
  /// "no prior chain history", NOT elapsed seconds — a fresh seed created a few
  /// minutes before this call, after a backup/consent step, still qualifies.
  /// A restore, migration, reinstall, or any re-derivation of an identity that
  /// existed before ⇒ pass `false`; it is a restore.)
  ///
  /// With `true` the account imports AT CREATE, fully offline: the receive address
  /// works from second zero with no network, and the host may CLEAR its staged seed
  /// the moment this returns (no create→first-sync staging window). TWO narrow
  /// exceptions keep the import lazy despite the flag — keep the staging contract
  /// there: a `config.birthday` ABOVE the bundled checkpoint tail (the config-typo
  /// guard needs a live tip; don't combine the flag with an above-tail birthday if
  /// you clear at return), and a retry over a create that previously crashed
  /// BEFORE its stamp landed (first sync then imports via the port — the
  /// re-stage contract; typed [WalletErrorKind.seedRequired] if nothing is
  /// staged, never fund loss).
  ///
  /// ⚠️ THE FLAG IS A MONEY-VISIBILITY ATTESTATION: marking a seed with prior chain
  /// history fresh pins the wallet's scan floor at ~now — pre-existing funds and
  /// swap refunds become INVISIBLE (recoverable by `rescanFrom` with an EXPLICIT
  /// lower height through the registered seed port, or by wiping and re-creating
  /// with `false`; a `rescanFrom(null)` re-floors at the creation stamp and does
  /// NOT go deeper).
  ///
  /// When in doubt pass `false` — always money-SAFE. Its costs are a full history
  /// scan at first sync, no offline receive address until that sync completes (the
  /// FR-24 gap itself: `currentAddress` is typed [WalletErrorKind.seedRequired]
  /// until import), and the FR-12 staging window staying open (the host stages the
  /// seed for this provisioning scope and clears it once first sync completes). A
  /// configured ≤-bundle-tail `config.birthday` also imports at create and allows
  /// clearing at return, for either flag value.
  ///
  /// Throws [WalletErrorKind.seedRequired] if no seed port is registered or the host
  /// supplies none; [WalletErrorKind.walletAlreadyExists] on a completed store — if
  /// a previous freshly-generated create FAILED after provisioning, recover via
  /// `openWithHostSeed`, never re-create (note: the surviving creation stamp keeps
  /// the ~creation scan floor on that reopen — for a wallet MIS-attested fresh,
  /// deeper history needs `rescanFrom` with an explicit lower height or the wipe +
  /// re-create-with-`false` path above); the usual config-validation errors
  /// (endpoint rules, …).
  static Future<WalletHandle> createWithHostSeed({
    required WalletConfig config,
    bool? freshlyGenerated,
  }) => ZecWalletRustLib.instance.api
      .crateApiWalletWalletHandleCreateWithHostSeed(
        config: config,
        freshlyGenerated: freshlyGenerated,
      );

  /// The wallet's default receive address — a Unified Address with Orchard +
  /// Sapling receivers (no transparent receiver), encoded for display/QR.
  /// Deterministic per seed.
  Future<String> currentAddress();

  /// The wallet's transparent RECEIVE address (Recv-2 / ADR-0528): the account's
  /// canonical external-scope (`m/44'/coin'/0'/0/0`) P2PKH t-address, surfaced ALONGSIDE
  /// the shielded UA behind the receive screen's address-type toggle (default shielded).
  /// PUBLIC + reused-address-linkable (visible on-chain) — the host labels it as such and
  /// keeps the shielded UA the recommended default. Deterministic per seed; the spending
  /// key never leaves Rust (§4.1). Returns the bare t-address string (no librustzcash type
  /// crosses the bridge). A wallet whose stored UFVK predates `transparent-inputs` (pre-GA)
  /// surfaces the typed key-derivation error, never a panic.
  Future<String> currentTransparentAddress();

  /// The PRODUCTION custody disclosure (FR-14 H1) for the wallet at
  /// `config.dbDir` — render an HONEST pre-`wipe` confirmation (a hardware-held
  /// key deleted vs best-effort removal) and an ambient custody badge from it.
  /// An ACTIVE probe of the measured vault tier; reads NO seed and unseals
  /// nothing. A `Self`-less static so it works before/independent of an open
  /// handle. `VaultAbsent` (headless desktop) ⇒ `tier: "none"`,
  /// `eraseAssurance: bestEffort`.
  ///
  /// Distinct from the diagnostic `selftestSeedCustody`: that one provisions
  /// selftest identities and must not drive shipped UX; THIS is the shippable
  /// query.
  static Future<CustodyDisclosure> custodyDisclosure({
    required WalletConfig config,
  }) => ZecWalletRustLib.instance.api
      .crateApiWalletWalletHandleCustodyDisclosure(config: config);

  /// The wallet's DELIVERY OBLIGATION for one transaction it created — the
  /// same value a history row carries on [TxSummary.delivery], for a caller
  /// that holds a `txidHex` (the one `send` returned in its
  /// [TxSubmitResult]s, passed back verbatim). Read it right after a `send`
  /// whose result was not all-success: `null` or anything but
  /// [DeliveryState.retryPending] means the wallet is NOT promising to send
  /// it on a later sync, so do not say so. `null` for a transaction this
  /// wallet did not create, one that has expired (its `TxStatus` says so) or
  /// one it holds no row for. Reads the aux connection off the engine lock,
  /// so it never blocks sync. Throws [WalletErrorKind.txidInvalid] for a
  /// `txidHex` that is not 64 hex characters; [WalletErrorKind.invalidState]
  /// on a closed handle.
  Future<DeliveryState?> deliveryState({required String txidHex});

  /// How many connections each arm served, by outcome, since this wallet
  /// opened — the numbers to show beside the transport state (the network
  /// panel's "N private, M direct"). One connection is one dial; the count
  /// is exactly what the SDK's own `wallet.dial` log line records, so the
  /// two never disagree. In memory only: a reopen starts at zero. Readable
  /// in every lifecycle phase, cheap, no I/O. Never logged by the SDK — it
  /// crosses only on this call.
  /// [WalletErrorKind.invalidState] if the handle is closed.
  Future<DialCounts> dialCounts();

  /// Remove one in-flight swap record. USER-INTENT only since #367: call from the
  /// terminal card's Done (the outcome rendered full-screen = seen) or the home
  /// row's explicit Remove — a terminal OBSERVATION pins via `recordSwapOutcome`
  /// instead, so an away-at-terminal outcome is never erased unseen.
  /// Display-only state: this never touches the deposit outbox, the in-flight
  /// guard, or detection (money in motion keeps moving; only the home row goes).
  /// Idempotent — returns `false` for an already-absent id, so a raced
  /// double-dismiss is harmless. A never-dismissed record self-lapses out of
  /// `listInFlightSwaps` at [SwapRecord.expiresAt].
  Future<bool> dismissSwapRecord({required String swapId});

  /// Construct the NEAR Intents swap provider over THIS wallet's own transport
  /// and turn the swap on-ramp ON (spec §3.5; the `swap-near` feature). The
  /// composition entry behind the `swapQuote`/`swapExecute`/`watchSwapStatus`
  /// surface — until it succeeds, [WalletHandle.swap] is conceptually `null`
  /// (kill layer 2) and those three throw [SwapErrorKind.swapDisabled].
  ///
  /// Swap rides the wallet's CONFIGURED transport (the same host-provided dialer
  /// and Tor policy sync uses, ADR-0526 — no independent egress; internal Tor is
  /// optional, the host may supply its own). [config.jwt] is an OPTIONAL provider
  /// auth token (a §5.4 NEVER-log value): it is wrapped in a zeroizing buffer in
  /// Rust at this boundary and never logged; Dart memory cannot be zeroized (the
  /// documented §10 exposure, same as the mnemonic crossing) — keep it minimal.
  /// `swapEnabled` + `declaredKill` are the host's §3.5 layer-3 kill state (e.g.
  /// lowered from a signed manifest); they are applied MONOTONIC-TOWARD-OFF, so a
  /// forged/replayed "on" can only ever make swap MORE off, never resurrect it.
  ///
  /// Set-once, first-wins: a second call is a no-op (re-enabling swap is host
  /// RECONSTRUCTION of the wallet, never an in-place provider swap; §3.5). On any
  /// failure NO provider is attached — the wallet stays at kill layer 2, zero swap
  /// surface. Throws a [SwapApiError]: [SwapErrorKind.watchOnly] on a WATCH-ONLY
  /// wallet (#397 §3.7 D3 — STRUCTURAL and NEVER retryable, checked FIRST so it
  /// outranks any config-shaped failure; render the view-only framing, not a
  /// retry), [SwapErrorKind.providerUnavailable] when the wallet's transport
  /// cannot be resolved (the on-ramp has no network to ride — retryable),
  /// [SwapErrorKind.swapStateUnavailable] on a closed handle, and
  /// [SwapErrorKind.swapDisabled] in a build compiled WITHOUT the `swap-near`
  /// adapter (§3.5 kill layer 1 — the method stays present so the Dart surface is
  /// STABLE across feature flavors, but honestly reports swap is off).
  Future<void> enableNearSwap({
    required SwapProviderConfig config,
    required bool swapEnabled,
    SwapKill? declaredKill,
  });

  /// How close the wallet is to the one-time-address (ZIP-320 ephemeral) gap-limit ceiling — a
  /// [`ReservationPressure`] (COUNTS-only). ⚠ `outstanding`
  /// is a LOWER BOUND (#315 slice-2 proof discovery): the underlying engine read is BLIND to slots
  /// held by sends CREATED then never confirmed (their output row exists from create-persist), so
  /// it can read `0` while the window is actually full — treat it as "at least N in use", never as
  /// proof the window is clear. Surface it as a proactive hint; the real gate is the engine's
  /// `TexSendLimitReached` at send time, and the #315 reclaim (`reclaimEphemeralSlots`) gates on
  /// its own wide reservation read, never on this gauge. An INDICATOR for display, NEVER a money
  /// gate. `0` outstanding in the common case (no TEX send has reserved an address). Throws
  /// [WalletErrorKind.invalidState] on a closed handle.
  Future<ReservationPressure> ephemeralReservationPressure();

  /// THE ONE SANCTIONED UFVK EGRESS (#397, spec §3.7 D1 / ADR-0538; §5.4
  /// HARD-D re-cast: "never leaves the device SILENTLY"). Returns the
  /// wallet's full viewing key in the standard unified encoding.
  ///
  /// **HOST CONTRACT (LOUD):** the returned string grants TOTAL HISTORY
  /// VISIBILITY — every incoming AND outgoing payment, past and future —
  /// to anyone who ever holds it. It cannot spend and cannot reach the
  /// seed. Gate it behind a deliberate user action at the SAME bar as the
  /// backup-phrase reveal (re-auth + screenshot protection + the §3.7 D9
  /// warning copy — the reference UI export screen is the normative
  /// example); never call it implicitly; never log or persist the value
  /// beyond the user's explicit share. The only un-share is moving funds
  /// to a new wallet. Works at every custody tier including watch-only
  /// (identity operation — the host supplied the key).
  Future<String> exportUfvk();

  /// Is this a WATCH-ONLY wallet (#397 §3.7 D4/D5)? SYNC + lock-free (the
  /// kind is immutable after open). The reference UI keys its chrome on
  /// this — the watch-only badge, hidden Send/Shield/Swap affordances, the
  /// no-backup security screen; the typed [WalletErrorKind.watchOnly]
  /// refusals stand regardless, so a host ignoring it only ever sees
  /// honest errors.
  Future<bool> isWatchOnly();

  /// The IN-FLIGHT two-step (TEX/ZIP-320) sends: first leg signed + broadcast, send not yet
  /// complete — the user's money is IN MOTION through a wallet-controlled one-time address. The
  /// host renders a DURABLE "on its way — don't send it again" cue from this list (see
  /// [`InFlightSend`] for the lifecycle + the DOUBLE-PAY
  /// CAUTION): the post-send result screen's caution is dismissible, and without this surface an
  /// in-flight two-step reads as an ordinary pending send exactly when a worried user is most
  /// tempted to re-pay. DISJOINT from `listParkedSends` (parked = queued, nothing signed yet;
  /// in-flight = signed + broadcast) — a send is in at most one. Read-only PULL, cheap + LOCAL
  /// (a SQLite read; no network, no money movement); call it on the same edges as
  /// `listParkedSends` (sync ticks / resume / after a send completes). Empty when nothing is
  /// mid-flight — the common case. Amount-only (§5.4; no recipient/txid/address). Throws
  /// [WalletErrorKind.invalidState] on a closed handle. HOST CONTRACT on a THROW: the call
  /// fails LOUD on a corrupt store row (fail-closed — a broken row must never silently hide a
  /// possibly-in-motion send); prefer SURFACING that failure over hiding the cue, because a
  /// swallowed error removes the double-pay caution for EVERY in-flight send at once (a host
  /// may fall back to hiding only because the pending tx stays visible in `transactions`).
  Future<List<InFlightSend>> listInFlightSends();

  /// The durable IN-FLIGHT SWAP surface (W-swap-5, #366): every swap whose order was
  /// registered at execute and has neither been dismissed nor self-lapsed. THE
  /// kill→relaunch re-attach: after a process restart the home screen lists these and
  /// re-opens live tracking by feeding [SwapRecord.id] to `watchSwapStatus` — without
  /// this list an armed OutOfZec deposit was invisible everywhere while the
  /// one-swap-in-flight guard refused new swaps. NOT gated on swap being enabled or
  /// the §3.5 kill state (a local read is not swap traffic — records stay readable so
  /// the user never loses sight of money in motion). Read-only, cheap + LOCAL (a
  /// SQLite read); call it on the same edges as `listParkedSends` (sync ticks /
  /// resume / after an execute). Empty when nothing is in flight — the common case.
  /// §5.4: [SwapRecord.id] is render-never-log. Throws [WalletApiError] only for a
  /// closed handle / store fault.
  Future<List<SwapRecord>> listInFlightSwaps();

  /// EVERY queued send sitting in `Queued` that has NOT completed yet — a one-time-address (TEX)
  /// two-step awaiting its drain pass / ceiling-parked, or (since #331) a plain single-step send
  /// waiting in the offline queue; the DTO `kind` says which (presentation-only). They have NO
  /// on-chain transaction yet (INVISIBLE in the activity / transaction list), so this surfaces
  /// them "saved & pending" instead of silence — across an app relaunch it is the ONLY place the
  /// committed spend exists (hidden, a queued send is a DOUBLE-PAY window). Each is amount + id +
  /// kind + `paused` ([`ParkedSend`]); the recipient address NEVER
  /// crosses the bridge. A read-only PULL the host calls on demand; cause-agnostic copy (never
  /// "blocked"/"stuck"). A HEALTHY row auto-broadcasts once it can drain — present it per the
  /// [`ParkedSend`] DOUBLE-PAY CAUTION (never invite a re-send) and EARMARK its amount over the
  /// balance (it stays in spendable). A `paused` row does NOT auto-broadcast (#315 — the wallet
  /// gave up auto-retrying it; it waits for `retryParkedSend` or `cancelParkedSend` and MUST be
  /// phrased as paused, never "will send when ready"). To DISCARD either, pass its
  /// `(id, createdAt)` to `cancelParkedSend` (the SDK cancel — the SAFE counter-affordance, landed v-4a,
  /// kind-agnostic; the host UI button/confirm is v-4b). Throws [WalletErrorKind.invalidState] on a
  /// closed handle.
  Future<List<ParkedSend>> listParkedSends();

  /// FR-27 — the MACHINE-MEMO bytes of one transaction, scoped to the
  /// prefixes registered on [WalletConfig.machineMemoPrefixes]. Returns them
  /// in output order; `txidHex` is the `txidHex` a history row gave you,
  /// passed back verbatim.
  ///
  /// **THESE BYTES ARE ATTACKER-CONTROLLABLE.** They came off a public chain,
  /// and anyone can put anything in a memo attached to a payment they send
  /// you. Parse them with something that fails closed — validate your own
  /// framing before you use any of it, reject trailing bytes and a length
  /// that lies, and treat an unknown value as hostile rather than as a
  /// default. This SDK does none of that for you, by design: it never parses
  /// the envelope, so its layout stays yours rather than becoming a format
  /// this SDK would have to version.
  ///
  /// **PREFIX MATCHING IS NOT A SECURITY BOUNDARY.** Forging a prefix costs
  /// an attacker nothing — your magic bytes are visible on-chain to anyone
  /// who looks — so the scope cuts the VOLUME reaching your parser, never the
  /// INTENT behind what arrives. Your parser is on the hostile path by
  /// default, not as defence in depth. A prefix also does not mean "written
  /// by this device": the memos worth reading were written by whoever paid
  /// you.
  ///
  /// Scope, exactly: `Arbitrary` (`0xFF`) memos only — a ZIP-302 `Reserved`
  /// memo NEVER returns bytes here and a text memo has its own lane — each
  /// bounded at 511 bytes, and only for a transaction this wallet can
  /// decrypt (the same entitlement the history read already has: outputs
  /// this wallet sent or received). Memos arrive with transaction
  /// ENHANCEMENT, not compact scan, so a freshly received transaction
  /// returns nothing until its enhancement pass has run.
  ///
  /// WIRE REALITY, and a host that ignores it will read padding as data: the
  /// `0xFF` field carries no length framing, so a memo shorter than 511 bytes
  /// was zero-padded on the wire and comes back as the full 511. Frame your
  /// own length INSIDE the bytes.
  ///
  /// WHAT THE LIST POSITION IS NOT: it is not an output index (empty and
  /// out-of-scope memos are filtered out before you see it), and this verb
  /// alone cannot tell you whether a memo was one this wallet WROTE or one a
  /// payer wrote to it — both are readable and both are returned. Join
  /// against the history row if you need direction.
  ///
  /// One output whose memo the audited ZIP-302 classifier rejects does NOT
  /// deny the rest: that row is skipped and the readable memos still come
  /// back. The sender of a transaction picks every byte of every memo in it,
  /// so a strict read would let a hostile counterparty suppress the envelope
  /// they were paying you with.
  ///
  /// Throws [WalletErrorKind.machineMemoScopeInvalid] when no prefix is
  /// registered — the verb is opt-in and CLOSED by default, and an empty list
  /// would read as "this transaction carries nothing" over a memo that is
  /// there. Throws [WalletErrorKind.txidInvalid] for a `txidHex` that is not
  /// 64 hex characters.
  Future<List<Uint8List>> machineMemos({required String txidHex});

  /// Mint the NEXT public diversified receive address (FR-8 / Recv-4, ADR-0537): a fresh
  /// unlinkable Unified Address for a contact/invoice that still credits the one wallet
  /// account. Payments to it are detected by the normal shielded scan — including after a
  /// seed-only restore — with no extra host work. Same receiver set as `currentAddress`
  /// (Orchard + Sapling, no transparent). Every call returns a NEW address from the
  /// never-recycle counter, which survives restore: each seed-only restore starts
  /// minting in a fresh RANDOM band (~2048 mints wide), so no prior life's addresses
  /// are re-issued — deterministic for lives up to ~2048 mints, ≤ ~2^-18 per-restore
  /// band-overlap chance beyond (attribution/linkage caveat, never a fund
  /// risk). Local + offline + cheap (no network, no sync
  /// requirement). Deterministic per index — keep [MintedDiversifiedAddress.diversifierIndex]
  /// as the durable attribution key, and treat it as WALLET-INTERNAL (never share it with
  /// a counterparty — it is a sequential mint ordinal). Throws
  /// [WalletErrorKind.keyDerivation] before any account is provisioned (exotic —
  /// accounts import eagerly at create), [WalletErrorKind.invalidState] on a closed
  /// handle. §5.4: render/store the fields, never log them.
  Future<MintedDiversifiedAddress> mintDiversifiedAddress();

  /// Open an EXISTING wallet at `config.dbDir`.
  ///
  /// Throws [WalletErrorKind.notFound] if nothing is provisioned there,
  /// [WalletErrorKind.networkMismatch] if `config.network` disagrees with
  /// the stored wallet, [WalletErrorKind.walletAlreadyOpen] if another
  /// instance already holds it, and [WalletErrorKind.provisioningIncomplete]
  /// for an interrupted create — open does NOT repair a remnant; `create`
  /// resumes the repair from the sealed seed, so the host's boot fork routes a
  /// remnant (`walletExists` == false) to create, never here.
  static Future<WalletHandle> open({required WalletConfig config}) =>
      ZecWalletRustLib.instance.api.crateApiWalletWalletHandleOpen(
        config: config,
      );

  /// Open an EXISTING host-custodied-seed wallet at `config.dbDir` (FR-15),
  /// attaching the registered C-ABI seed port so signing + fresh-refund-address
  /// derivation can pull the seed on demand. For a wallet whose account is ALREADY
  /// imported (the steady state), balance, history, and the receive address need
  /// NO seed and never call the port; the host stages narrowly and clears per the
  /// FR-12 contract (take-once for a send). This only transports the pull
  /// native-to-native, never through Dart.
  ///
  /// EXCEPTION — a wallet reopened BEFORE its account import: a restore-shaped
  /// `createWithHostSeed` create whose first sync hasn't completed, OR the
  /// failed-freshly-generated-create recovery `createWithHostSeed` routes here.
  /// There, first sync imports the account THROUGH the port — keep the FR-12
  /// staging contract until it completes, and until then `currentAddress` is a
  /// typed [WalletErrorKind.seedRequired] (not a hang, and never fund loss).
  ///
  /// Throws [WalletErrorKind.seedRequired] if no port is registered;
  /// [WalletErrorKind.notFound]/`networkMismatch`/`walletAlreadyOpen` as `open`.
  static Future<WalletHandle> openWithHostSeed({
    required WalletConfig config,
  }) => ZecWalletRustLib.instance.api
      .crateApiWalletWalletHandleOpenWithHostSeed(config: config);

  /// Dial `choice` under THIS wallet's Tor policy and ask the server who it
  /// is (one `GetLightdInfo`, 15 s budget). Refuses typed —
  /// [WalletErrorKind.syncServerUnreachable] (could not dial, timed out, or
  /// the server refused), [WalletErrorKind.networkMismatch] (the server is
  /// on another Zcash network), [WalletErrorKind.syncServerNotOffered] —
  /// and NEVER switches. Use it for the picker's "Check server" step; a
  /// switch probes again on its own. `default` probes `endpointUrl`.
  Future<SyncServerProbe> probeSyncServer({required SyncServerChoice choice});

  /// Prepare a send from a ZIP-321 payment URI — propose (the FIRST half of the
  /// propose→confirm→send flow, inc-2d-ffi). Runs the audited note-selection + fee +
  /// change over the wallet DB and returns a [SendProposal]: the EXACT numbers
  /// (total/fee/change, per-recipient pool + amount, the §5.1 de-shield disclosure) the
  /// user confirms before signing. DETERMINISTIC — no spending keys, no proofs, no
  /// network, no DB writes; NOTHING is sent. The opaque proposal token is retained
  /// Rust-side; `send` consumes it by `proposalId`.
  ///
  /// `requestUri` is the ZIP-321 URI the host composed from its send form (via
  /// `encodePaymentUri`) or scanned from a QR — the §2.4 lossless request token. It is
  /// lowered with THIS wallet's network (a cross-network URI is
  /// [WalletErrorKind.networkMismatch]); a malformed/oversized URI is
  /// [WalletErrorKind.paymentUriInvalid]; a leg with no amount (the donation form) is
  /// [WalletErrorKind.sendAmountRequired]; not enough confirmed funds is
  /// [WalletErrorKind.insufficientFunds] (carrying available / required / pending-incoming,
  /// so the host can say "wait for confirmations" honestly); a not-yet-anchorable wallet is
  /// [WalletErrorKind.proposalStale] (re-propose after sync). No amount or address is ever
  /// logged (§5.4); [WalletErrorKind.invalidState] on a closed handle.
  Future<SendProposal> propose({required String requestUri});

  /// Propose shielding the wallet's detected transparent funds into its shielded pool —
  /// the Recv-3 companion to the transparent receive address (exchange withdrawals and
  /// swap-in deliveries land TRANSPARENT, §1.7; this is the privacy-positive "move them
  /// shielded" action). Wraps the audited `propose_shielding` (Rule Zero), gated at the
  /// 0.001-ZEC shielding threshold:
  /// - returns a [SendProposal] (`isShield == true`) when ≥ the threshold is shieldable —
  ///   confirm it, then pass its `proposalId` to `send` (the SAME one-shot token the send
  ///   path consumes; the shield reuses the send pipeline WHOLE), and
  /// - returns `null` when there is nothing worth shielding yet (below the threshold or no
  ///   transparent funds) — the host hides the "shield now" action.
  ///
  /// DETERMINISTIC, like `propose`: no spending keys, no proofs, no network, no DB writes;
  /// NOTHING is sent. No amount is ever logged (§5.4); [WalletErrorKind.invalidState] on a
  /// closed handle, [WalletErrorKind.proposalStale] on a not-yet-anchorable wallet.
  Future<SendProposal?> proposeShield();

  /// Queue a send for OFFLINE-first delivery (inc-2d-ffi). Durably persists the send INTENT
  /// (the ZIP-321 URI) and returns its opaque id IMMEDIATELY — NO network, NO signing, NO
  /// money movement. The §6.2 "queued is a normal state" path: tap send with zero
  /// connectivity and it survives a process kill, then proposes→signs→broadcasts on the next
  /// online sync pass (the resubmission machinery) — proposing at SEND time, not queue time,
  /// is exactly what stops a long-queued send from ever carrying a stale anchor.
  ///
  /// `requestUri` is the same lossless ZIP-321 token `propose` takes (same network /
  /// donation-form / oversize validation, same typed errors). The returned String is the
  /// OPAQUE queued-send id — do not parse it. Throws [WalletErrorKind.queuedSendsFull] when
  /// the durable queue is at capacity (a real send is never silently dropped). No amount or
  /// address is ever logged (§5.4); [WalletErrorKind.invalidState] on a closed handle.
  Future<String> queueSend({required String requestUri});

  /// RECLAIM a one-time-address (TEX) send window bricked by LEAKED reservations — sends that
  /// reserved a one-time address but never confirmed, which the wallet cannot free on its own
  /// (#315). Self-mints a small amount from your SHIELDED balance to the highest provably-abandoned
  /// one-time address; mining it reopens the WHOLE window at once. MONEY-MOVING + EXPLICIT: gate it
  /// behind the #327 authorizer with an honest-cost disclosure (the mint + a later recovery are TWO
  /// transactions, ~4 network fees; the minted principal returns to your wallet).
  ///
  /// Returns a [ReclaimOutcome]: `NothingToReclaim` when no reservation is provably abandoned (the
  /// window is transient — never mint on a maybe-live one, which could cancel a real payment);
  /// `Minted` on a signed+accepted mint (INITIATED — the window reopens once it confirms, and the
  /// moved amount returns via `sweepEphemeralFunds`); `NotBroadcast` on a transport miss (money-safe
  /// — it expires and frees the funds; try again). It unblocks the WINDOW only — it NEVER re-sends a
  /// paused/queued payment (no double-pay). Throws [WalletErrorKind.seedRequired] with no signing
  /// key, [WalletErrorKind.insufficientFunds] when the shielded balance can't fund the mint,
  /// [WalletErrorKind.invalidState] on a closed handle. Live now that TEX two-step sends run in
  /// production (gate-removal, 2e-2b-v-5); a wallet that has made no TEX send has nothing to reclaim.
  ///
  /// ⚠ HOST GATING (money-relevant): surface this ONLY behind the #327 authorizer + the honest-cost
  /// disclosure, and ONLY when a send is actually parked/paused. The SDK cannot tell a bricked
  /// window from a healthy one (the engine exposes no occupancy read — the owed upstream FR), so a
  /// call on a wallet with only OLD completed one-time-address sends still mints uselessly (a few
  /// network fees; the principal returns via `sweepEphemeralFunds`; no benefit). Fee-waste only,
  /// never fund-loss — but do NOT auto-invoke, loop, or offer it without the parked/paused trigger.
  Future<ReclaimOutcome> reclaimEphemeralSlots();

  /// Pin an OBSERVED terminal outcome into an in-flight swap record (#367): call
  /// when the tracking stream reports a TERMINAL status (success / refunded /
  /// failed) so the home row renders the truth even if the user was away at
  /// observation time — deleting on observation (the pre-#367 contract) erased
  /// outcomes the user never saw, durably if the process died in the gap.
  /// FIRST-WINS (a terminal is forever; a later conflicting pin no-ops) and
  /// idempotent — returns `false` for an absent / lapsed / already-pinned id.
  /// Display-only state; never touches the deposit outbox, the in-flight guard,
  /// or detection. §5.4: `swapId` is render-never-log.
  Future<bool> recordSwapOutcome({
    required String swapId,
    required SwapOutcome outcome,
  });

  /// Funds recoverable on wallet-controlled *one-time* (ephemeral) transparent addresses — a TEX
  /// transfer whose forwarding step expired, or an exchange that returned a deposit to that
  /// single-use address. A read-only PULL the host calls on demand (e.g. to render a "recover" row
  /// on the balance). Each entry is amount + welded reorg-finality
  /// ([`RecoverableEphemeralFunds`]); the one-time
  /// address never crosses the bridge. **PRESENTATION: the amount is a SUBSET of the displayed
  /// balance — render it as part of the balance, NEVER as additional funds.** Live now that TEX
  /// two-step sends run in production (gate-removal, 2e-2b-v-5); empty on a wallet that has made no
  /// TEX send (no one-time address has ever held a return).
  Future<List<RecoverableEphemeralFunds>> recoverableEphemeralFunds();

  /// Rescan from an EARLIER birthday to recover funds an over-high restore
  /// birthday skipped (ADR-0534 — the in-app fix for the ADR-0533 "balance reads
  /// zero, sync says done" gap). Rebuilds ONLY the data DB at `fromHeight` — NO
  /// recovery-phrase re-entry, and NO key material crosses this bridge (the only
  /// argument is a bare block height). A SEALED-KEYCHAIN wallet re-imports from
  /// the seed that stays sealed in the keychain. A HOST-CUSTODIED
  /// (`SeedPersistence.none`) wallet opened through `openWithHostSeed` re-imports
  /// through its registered seed port at the FIRST sync after the rescan — the
  /// same pull its first-ever sync made, native-to-native, so the host must have
  /// the seed STAGED for that sync (until it runs, the rebuilt wallet honestly
  /// reads "account not yet provisioned", balance zero, history empty); a port
  /// answering the WRONG seed is refused [WalletErrorKind.seedMismatch] before a
  /// note is derived, and the next sync asks again. A host-custodied wallet with
  /// NO seed port registered is a typed up-front [WalletErrorKind.seedRequired]
  /// (nothing can serve the re-import). Pass `null` to scan the FULL history
  /// (floors to Sapling activation, a slower but money-SAFE scan, NEVER ~tip —
  /// except a freshly-generated wallet, whose durable creation stamp re-floors
  /// `null` at ~creation: money-equivalent and hours faster; pass an explicit
  /// height to go deeper). Pair with `estimateBirthday` for a date-picker UX.
  ///
  /// The durable money state (pending queued sends, the refund-address index, and
  /// in-flight swap detection) is PRESERVED across the rebuild; the seed seal +
  /// keychain vault are never touched, so a crash mid-rescan can never lose the
  /// seed (the wallet re-opens at the old OR the new birthday, never bricked).
  ///
  /// Stops + joins sync first, then rebuilds under the single-writer lock — a
  /// concurrent call observes a retryable [WalletErrorKind.walletBusy] carrying the
  /// `rescanning` phase. CONSUMES the handle's wallet: on success the rebuilt wallet
  /// REPLACES it (call `startSync` to scan from the lower birthday, and re-subscribe
  /// EVERY live stream — a rescan is a whole new session, so `watchSyncStatus`,
  /// `watchTorState` and `watchIncomingFunds` all complete, unlike a
  /// `switchSyncServer`); on ANY error
  /// (e.g. [WalletErrorKind.seedRequired] for a portless host-custodied wallet) the
  /// handle is left closed but the seals + data DB are intact, so the host
  /// re-`open`s. [WalletErrorKind.invalidState] if the handle is already closed.
  Future<void> rescanFrom({int? fromHeight});

  /// Restore an existing wallet from its BIP39 recovery phrase — the ONE
  /// sanctioned INBOUND key-material crossing (spec §3.3; the outbound
  /// counterpart is `revealMnemonic`). `mnemonicWords` are
  /// the recovery words in order (a `List<String>`, the symmetric counterpart to
  /// `revealMnemonic` — never a single joined string in Dart). Pass each word
  /// LOWERCASED (and trimmed): the audited BIP39 validator does NOT case-fold, so
  /// a soft keyboard's autocapitalized first word would otherwise reject a
  /// CORRECT backup. A mis-cased/unknown word is a typed [WalletErrorKind.invalidMnemonic]
  /// carrying its INDEX (never silently a different wallet); inter-word and
  /// surrounding whitespace IS tolerated. They are
  /// BIP39-validated (checksum + word list) and turned into a sealed seed
  /// ENTIRELY Rust-side, then the wallet is provisioned at `config.dbDir` and
  /// opened. The words live in Dart memory only as long as the restore screen
  /// holds them — Dart memory cannot be zeroized (the documented §10 inbound
  /// exposure, identical framing to the outbound `revealMnemonic`). Once Rust
  /// owns the words (as a `SeedSource`), the seed + phrase ride zeroizing
  /// buffers and wipe on drop; the brief inbound word-list copy itself is
  /// un-wiped (FRB cannot marshal a zeroizing type) — the same minimal,
  /// documented residue as the outbound reveal, minimised not eliminated.
  ///
  /// `passphrase` is the OPTIONAL BIP39 passphrase (the "25th word") — pass
  /// `null` for the common case (wallets created by this SDK / Zashi / Zodl use
  /// none). It is itself part of the secret: a user who set one MUST supply it
  /// or their funds are unreachable, and a wrong/omitted passphrase silently
  /// derives a DIFFERENT, empty wallet (this is BIP39, not an SDK choice).
  ///
  /// Set `config.birthdayHeight` to the wallet's creation height (or via
  /// `estimateBirthday`) so the scan starts there; `null` floors the scan to
  /// Sapling activation — a full, slower but money-SAFE scan that finds the
  /// whole history, NEVER ~tip (which would silently skip older funds).
  ///
  /// Throws [WalletErrorKind.invalidMnemonic] (carrying the offending word
  /// INDEX, never the word) for a phrase that fails BIP39 validation;
  /// [WalletErrorKind.walletAlreadyExists] if a completed wallet is already
  /// provisioned at `config.dbDir`. That rejection is STRUCTURAL — the existing
  /// sealed seed is never overwritten regardless of whether the host probed
  /// `walletExists` first (the boot fork normally does, so a host rarely sees
  /// it). Throws [WalletErrorKind.seedMismatch] if a DIFFERENT phrase is
  /// restored over an interrupted-create remnant of another wallet; plus the
  /// usual config-validation errors (endpoint rules, …).
  static Future<WalletHandle> restore({
    required WalletConfig config,
    required List<String> mnemonicWords,
    String? passphrase,
  }) => ZecWalletRustLib.instance.api.crateApiWalletWalletHandleRestore(
    config: config,
    mnemonicWords: mnemonicWords,
    passphrase: passphrase,
  );

  /// RETRY a `paused` parked send the host listed via `listParkedSends` — resume the SAME queued
  /// intent after the wallet gave up auto-retrying it (see [`ParkedSend::paused`]
  /// (crate::api::state::ParkedSend)). The wallet caps auto-retries of a one-time-address send
  /// because every retry permanently uses up one of a small number of address slots; when the
  /// user believes conditions changed (back online, the recipient service reachable again),
  /// THIS is the resume path — NOT cancel + re-enter, which re-pays the retry budget on a fresh
  /// send and MUST NOT be offered while the paused row exists (double-pay + cap evasion). Pass
  /// BOTH the `id` AND the `createdAt` from the [`ParkedSend`]. Returns `true` if the send was
  /// re-armed (it attempts again on the next background pass — not instantly); `false` if it
  /// was already gone / began sending / its rowid was reused / it had nothing to reset — an
  /// untouched (never-retried) row is refused, never silently refilled (idempotent — re-read
  /// `listParkedSends`). MONEY-SAFE: this only re-arms the existing queued intent's retry
  /// budget — nothing is signed or sent by the call itself. §5.4: ids/timestamps only. Throws
  /// [WalletErrorKind.invalidState] on a closed handle.
  Future<bool> retryParkedSend({
    required PlatformInt64 id,
    required PlatformInt64 createdAt,
  });

  /// Reveal this wallet's BIP39 recovery phrase — word by word, in index order —
  /// so the user can back it up. The ONE sanctioned outbound key-material crossing
  /// (spec §3.3). The words ARE the wallet's whole secret: show them ONCE on a
  /// secure screen the host marks FLAG_SECURE, never log / persist / screenshot /
  /// transmit them, and prompt the user to write them down offline. Returns the
  /// words as a Dart `List<String>` (24 for a generated wallet; a restored phrase
  /// reveals its own length) — Dart memory cannot be zeroized (the documented §10
  /// exposure); the Rust side holds the words in zeroizing buffers and wipes its
  /// own copies when this call returns.
  ///
  /// Throws [WalletErrorKind.noMnemonic] for a wallet with no stored phrase — one
  /// opened from raw seed bytes (a host-custodied-seed integration recovers from
  /// its OWN master secret, never a wallet-local phrase) — and
  /// [WalletErrorKind.invalidState] on a closed handle.
  Future<List<String>> revealMnemonic();

  /// Sign + broadcast a prepared proposal — the SECOND half of the send flow (inc-2d-ffi).
  /// `proposalId` is the opaque one-shot token from the [SendProposal] `propose` returned;
  /// pass back ONLY that id — the host cannot mutate what gets signed (the retained proposal
  /// is the sole source of truth, so a tampered id is just a registry miss, never a
  /// wrong-amount sign). The transient spending key is derived, used to sign inside a
  /// blocking proving task, and zeroized — it NEVER crosses this bridge. Each resulting tx
  /// is PERSISTED before broadcast (§6.3), then broadcast over a FRESH per-tx Tor circuit
  /// (§2.3) after a §5.3 jitter.
  ///
  /// Returns a per-tx [TxSubmitResult] list (a proposal can mint several txs when crossing
  /// pools — §1.7): a broadcast failure is first-class DATA here, NEVER a thrown error, and
  /// every persisted tx is a DELIVERY OBLIGATION (ADR-0556, stage S8): the same bytes go out
  /// again on every later sync pass and after a reopen until they confirm or expire — so
  /// even a TOTAL broadcast failure loses no funds, only immediacy. (Before S8 this sentence
  /// was true of outbox rows only; a single-step send kept no row and was never retried —
  /// the 2026-09-20 review's R02.) Read the live state per tx from [TxSummary.delivery] or
  /// [WalletHandle.deliveryState] — persisted / retryPending / accepted / confirmed. Throws
  /// [WalletErrorKind.proposalAlreadyUsed] on a re-send/double-tap (the token was consumed —
  /// the notes are never broadcast twice, §6.3) or [WalletErrorKind.signFailed]. No txid/amount
  /// is ever logged (§5.4); [WalletErrorKind.invalidState] on a closed handle.
  ///
  /// ORDERING (the per-tx → leg contract): the list is in BROADCAST order, which is also mine
  /// order. For a ZIP-320 TEX two-step ([SendProposal.isTwoStepTex]) it is EXACTLY two entries:
  /// `[0]` is tx0 — the unshield that funds a wallet-controlled one-time (ephemeral) address —
  /// and `[1]` is tx1 — the forward from that address to the TEX recipient. tx1 SPENDS tx0's
  /// output, so it can only mine after tx0. Only a TRANSPORT failure latches the tail as
  /// [TxSubmitResult.notAttempted] (the endpoint never saw the predecessor, so the tail cannot
  /// propagate this call); a mempool REJECT of tx0 does NOT stop tx1 — tx0 may simply be
  /// already known (the wallet's own background re-broadcast can race this call and land it
  /// first), and a genuinely-invalid tx0 just makes tx1 a harmless reject. So a two-step list
  /// holding ANY success but not ALL — `[Success, non-Success]` or `[non-Success, Success]`
  /// (the latter implies an HONEST endpoint already knew tx0) — is the "funds in motion on the
  /// ephemeral" state: the host renders the honest in-motion partial (do-not-resend;
  /// recoverable), NOT the ordinary "each tx saved-for-retry" copy (see
  /// [SendProposal.isTwoStepTex]). RESIDUAL: a ZERO-success two-step can ALSO be that race
  /// (both legs already landed → both read rejected), but reject codes are backend-specific
  /// and deliberately uninterpreted, so it reads as the ordinary saved-for-retry — the durable
  /// [WalletHandle.listInFlightSends] cue owns the honest "don't re-send" through that window.
  /// Every non-accepted TWO-STEP tx stays persisted and re-broadcasts on the next sync (the
  /// send is enrolled durably before broadcast); a failed SINGLE-step send instead self-heals
  /// by expiry (~40 blocks) freeing its notes for a fresh re-send. An ordinary
  /// pool-crossing send's txs are INDEPENDENT — position is broadcast order only, no leg meaning.
  ///
  /// PROPOSAL FRESHNESS (the confirm-screen host contract): a [SendProposal] is a one-shot
  /// token with a short, minutes-scale TTL (MONOTONIC — device suspend counts). If the user
  /// opens the confirm screen and resumes after a long background gap, `send` returns
  /// [WalletErrorKind.proposalStale]; the host MUST call `propose` AGAIN for a fresh
  /// [SendProposal] (the fee/anchor may have moved) and re-present the numbers — NEVER retry the
  /// same `proposalId`. `proposalStale` is also raised if the wallet is not yet anchorable.
  Future<List<TxSubmitResult>> send({required PlatformInt64 proposalId});

  /// **The duress force-sever** (FR-53): make the wallet at `config.dbDir`
  /// unrecoverable within `deadlineMs`, EVEN WHILE something still holds it
  /// open (a handle never closed, a straggler past `close`, a rescan or
  /// server switch mid-rebuild, an open in flight, another process) — the
  /// case where `wipe` refuses with [WalletErrorKind.walletOpen].
  ///
  /// Nothing holds the wallet → it is the ordinary `wipe` (key store first,
  /// then the files): `files: removed`, `holder: none`. Something holds it →
  /// the key-store custody is severed anyway, NO file is deleted
  /// (`files: leftForHost`), and every instance of the wallet in this
  /// process is poisoned: each later call answers `invalidState` (`wiped`),
  /// and a broadcast in flight does not go out. On a locked key store the
  /// sever deletes blind and answers `severedUnproven` with `leftForHost`,
  /// whether or not anything held the wallet.
  ///
  /// `deadlineMs` is whole milliseconds, clamped to `[0, 4000]` (the SDK's
  /// key-store budget for a wipe; a longer deadline gains nothing, and a
  /// small one is kept as given). It is a HARD bound on the WHOLE call: the
  /// answer comes by `deadlineMs + severAnswerGraceMs()` (250 ms) whatever
  /// stalls. An overrun answers the DISTINCT `notSevered(stillRunning)`,
  /// `files: stillInUse`, `holder: unknown`. The SDK's own sever cannot be
  /// cancelled and may still be deleting in `dbDir`, so on `stillRunning`
  /// do NOT purge or re-create at that `dbDir`. Call again with a backoff
  /// until the cause is not `stillRunning`, or exit the process. A call made
  /// while that sever runs answers `stillRunning` at once without reaching
  /// the store, so it never double-purges, and each overrun parks one
  /// uncancellable blocking task, so never call it in a tight loop. While it
  /// runs, every other door at that `dbDir` refuses before any work: `open`,
  /// the creates and `restore` answer `walletAlreadyOpen`, `wipe` and
  /// `wipeForce` answer `walletOpen`. "That `dbDir`" is the directory's real
  /// path, so a symlinked or `..` spelling of it counts (ADR-0566). The guard
  /// fails CLOSED: during a filesystem stall while a sever is in flight, those
  /// doors may refuse at any directory, and never hang. It is a check at the
  /// door, not a hold: a sever that STARTS after a door has passed it runs
  /// alongside that door's work, under the SDK's store lock and tombstone. `0`
  /// makes no key-store call and answers `notSevered(pastDeadline)`. A
  /// `dbDir` that never held a wallet, or a call after the sever ended,
  /// answers `alreadyGone`. The call never throws for a custody outcome. It
  /// throws [WalletApiError] only for a bad `dbDir` (the same door as `wipe`:
  /// pass the SAME absolute `dbDir` you opened with) or an I/O fault. It
  /// consumes ONLY `config.dbDir`. Like `wipe`, it sets the device log `Off`
  /// and closes the `watchDeviceLog` stream before anything else.
  ///
  /// **The host's four obligations:**
  ///
  /// 1. **Read `severed`, not the absence of an exception.** `severed` is
  ///    PROVEN. `severedUnproven(countUnreadable)`: the phone was locked; the
  ///    delete was issued but cannot be confirmed — a `wipe` after the next
  ///    unlock confirms it. `notSevered(timeout | busy)`: the key store was
  ///    occupied, by a custody write already in flight OR by ANY other
  ///    key-store call in this process (another open wallet's, or
  ///    `selftestSeedCustody`'s) — all of them share one worker. Call
  ///    `severCustody` again: no new custody write can land meanwhile, and
  ///    the retry succeeds once that other call returns, so a host keeping
  ///    several wallets open, or running the selftest, should not expect
  ///    `severed` within the first deadline. `notSevered(stillRunning)`: the
  ///    SDK stopped waiting, but its own sever still runs; call again (with a
  ///    backoff) until it is not. Any other `notSevered` (and `unknown`): the
  ///    custody may be live.
  /// 2. **Purge ONLY on `files: leftForHost`: you delete the directory
  ///    yourself**, after this call has answered. On `stillInUse`, NEVER:
  ///    the SDK is still working in it. On `unknown`, call again.
  /// 3. **Severed means the key that unlocks the files on disk is deleted from
  ///    the key store** (how strongly is `custodyDisclosure`'s
  ///    `eraseAssurance`), not that the live instance's memory is clean: its
  ///    seed and database key stay in RAM until the holder drops. A host that
  ///    must end that exits the process.
  /// 4. **Before creating a wallet at the same `dbDir` again in this
  ///    process**, run a plain `wipe` of it. Until then `create`/`open` there
  ///    answer `invalidState` (`wiped`). A process restart also clears that;
  ///    after a restart, an `open` at a severed directory you did NOT delete
  ///    answers the store's custody error, not `wiped` — the plain `wipe` is
  ///    still the remedy.
  static Future<SeverReport> severCustody({
    required WalletConfig config,
    required int deadlineMs,
  }) => ZecWalletRustLib.instance.api.crateApiWalletWalletHandleSeverCustody(
    config: config,
    deadlineMs: deadlineMs,
  );

  /// The on-resume cold snapshot (spec §3.3): everything a UI needs to
  /// re-render after a background gap — balance, sync status, Tor state,
  /// chain tip, and a monotonic `seq` that also stamps every live stream
  /// item (so a stale stream event can never beat a fresher snapshot in a UI
  /// race: keep the larger `seq`). Cheap; safe to call on resume before
  /// re-subscribing to the live streams.
  ///
  /// `lastSynced` is the PERSISTED stamp of the last completed sync pass
  /// (`{height, at}` — written before each `UpToDate`, surviving relaunches),
  /// so a cold resume renders "as of block H, time" immediately. `null`
  /// before the first completed pass and after a rescan (the rebuild resets
  /// it — a stale stamp would pair the old height/time with a rebuilding
  /// balance); always the recorded truth, never a fabricated age.
  Future<WalletState> snapshot();

  /// Start the background sync loop — required for the live `watchSyncStatus`
  /// stream (and balance progress) to advance; a freshly opened wallet does
  /// NOT auto-sync. The engine runs over the configured endpoint/Tor with
  /// retry/backoff + a stuck-sync watchdog, so a fault surfaces as a
  /// `SyncStatus.stalled` EVENT on the stream, never a thrown error or a dead
  /// stream. Idempotent (a second call while running is a no-op).
  ///
  /// Throws [WalletErrorKind.invalidState] if the handle is closed or the
  /// wallet is mid-teardown.
  Future<void> startSync();

  /// Stop the background sync loop and await clean teardown. Idempotent;
  /// durable progress is preserved (the chain is the source of truth), so
  /// stopping loses nothing. Prompt even mid-sync (cooperative cancel ≤ one
  /// batch scan). Use it to pause sync WITHOUT closing the wallet; `close`
  /// stops sync as part of its own teardown. A no-op on an already-closed
  /// handle (nothing to stop).
  Future<void> stopSync();

  /// #390 — the render-only coverage read for the "Check older swap addresses" sheet:
  /// how far the wallet has already checked, for the coverage line and the
  /// Check/Check-deeper affordance. COUNTS ONLY — no address or index crosses. Read-only,
  /// side-effect-free; safe to poll while the sheet is open. Throws
  /// [WalletErrorKind.invalidState] on a closed handle.
  Future<SwapAddressCoverage> swapAddressCheckCoverage();

  /// Execute a quote — register the swap intent with the provider and (for OutOfZec)
  /// queue the §4.4 ZEC deposit send (spec §2.6/§3.3). Pass back the [SwapQuote]
  /// `swapQuote` returned; this is LEAST-AUTHORITY-equivalent to the `send` token even
  /// though it carries the whole DTO: the SDK PEEKS its own durable record by `quote.id`,
  /// compares the DTO's terms and binding to it field-by-field — a difference is
  /// [SwapErrorKind.quoteTermsDiffer] with nothing consumed — then claims the record
  /// single-flight; EVERY execution term comes from that record, never this DTO
  /// (ADR-0555), so a tampered `depositAddress`/amount cannot redirect funds.
  /// Returns the SDK-minted `SwapId` as an opaque String (`quote.id` itself, never the
  /// provider's deposit address) — do NOT parse it; pass it to `watchSwapStatus` as-is.
  /// Idempotent against a double-tap / crash-retry: ONE deposit per quote, ever (§5.4: nothing logged).
  ///
  /// Throws a [SwapApiError]: [SwapErrorKind.swapDisabled] / [SwapErrorKind.swapStateUnavailable]
  /// as for `swapQuote`; [SwapErrorKind.quoteExpired] past the deposit deadline AND for a quote
  /// this wallet did not issue or already executed (re-quote, never retry the same DTO);
  /// [SwapErrorKind.quoteTermsDiffer] when the DTO differs from the issued record (get a fresh
  /// quote); [SwapErrorKind.depositSendFailed] if the deposit leg could not be queued (re-quote).
  Future<String> swapExecute({required SwapQuote quote});

  /// The dynamic source-asset list for the IntoZec picker (spec §3.3b D5/L6) — LAZY: the host
  /// calls this when the user opens the IntoZec form (NOT on launch, so an idle user emits no
  /// token traffic). The SDK fetches the provider's `/v0/tokens` on its OWN circuit (never the
  /// sync circuit), filters to real quotable foreign assets (the ZEC asset itself + any
  /// `$0`/null-price entry dropped), and returns the picker rows + a freshness flag. On a fetch
  /// fault it serves the LAST good list with [SwapTokenList.fresh] = false (the host shows a
  /// "couldn't refresh, showing cached" banner — honest degradation), never a blank picker; an
  /// empty fresh list is the honest "no assets available right now." The host maps each
  /// `(chain, symbol)` to a BUNDLED icon (never CDN-fetched). No token field is logged (§5.4).
  ///
  /// Throws a [SwapApiError]: [SwapErrorKind.swapDisabled] when no provider is attached (kill
  /// layer 2), [SwapErrorKind.swapStateUnavailable] on a closed handle, and
  /// [SwapErrorKind.providerUnavailable] on a first-ever fetch fault with nothing cached to serve.
  Future<SwapTokenList> swapListTokens();

  /// Request a bounds-checked swap quote (spec §2.6/§3.3) — the FIRST step of the
  /// on-ramp. `request` names the direction, the user's EXACT side (the anchor every
  /// returned number is bounds-checked against before anything is signed), the
  /// slippage tolerance, and the direction-specific destination/refund fields. The
  /// returned [SwapQuote] carries the provider deposit address, the min-out floor, the
  /// ZEC side in zatoshis, and the §2.6 privacy `disclosure` the host MUST render —
  /// funds NEVER move here. No amount/address is logged (§5.4).
  ///
  /// Throws a [SwapApiError]: [SwapErrorKind.swapDisabled] when no provider is attached
  /// (Dart `swap == null`; kill layer 2), [SwapErrorKind.swapStateUnavailable] on a
  /// closed handle, and the §2.6 quote errors ([SwapErrorKind.slippageToleranceTooHigh],
  /// [SwapErrorKind.quoteOutOfBounds], [SwapErrorKind.destinationInvalid],
  /// [SwapErrorKind.providerUnavailable], [SwapErrorKind.refundAddressUnavailable]).
  Future<SwapQuote> swapQuote({required QuoteRequest request});

  /// MANUALLY recover funds stranded on wallet-controlled *one-time* (ephemeral) transparent
  /// addresses into the wallet's own SHIELDED balance — the user-discoverable recovery for the funds
  /// `recoverableEphemeralFunds` surfaces, PLUS late exchange returns / a 2nd deposit / aggregate dust
  /// the automatic surface cannot see (it raw-enumerates each one-time address's on-chain UTXOs).
  /// MONEY-MOVING: it signs + broadcasts one consolidating transaction per funded address (each over
  /// its own circuit, never co-spent — so a recovery never links the one-time-address set on-chain).
  ///
  /// Returns an [EphemeralSweepSummary] (COUNTS-only; the one-time addresses NEVER cross the bridge).
  /// `recoveredZat` is the AGGREGATE that landed in the shielded balance, counted ONLY on endpoint
  /// acceptance (idempotent on re-run — the engine excludes already-spent UTXOs, so this can never
  /// double-spend). `failed > 0` ⇒ some funds stay on-chain + re-runnable (a flaky link, NOT a loss);
  /// `truncated > 0` ⇒ a heavy wallet hit the per-invocation cap — run it again. Throws
  /// [WalletErrorKind.seedRequired] when the wallet cannot sign (no seed/credential available),
  /// [WalletErrorKind.invalidState] on a closed handle. Live now that TEX two-step sends run in
  /// production (gate-removal, 2e-2b-v-5); on a wallet that has made no TEX send no one-time address is
  /// reserved ⇒ an empty no-op.
  Future<EphemeralSweepSummary> sweepEphemeralFunds();

  /// Probe, then switch the wallet onto `choice` and REMEMBER it (the row
  /// survives restarts and rescans; `default` forgets it). The session is
  /// swapped in place: the sync loop is stopped and joined, the choice
  /// written, the wallet rebuilt over the SAME database — no rescan, no
  /// re-download; funds, history, queued sends and the sync verdict are
  /// untouched. Afterwards call `startSync`, and re-subscribe the live
  /// streams the swap ends — the old session's `watchSyncStatus` stream
  /// ENDS (the reference UI swaps its whole session, as after a rescan).
  /// `watchTorState` and `watchIncomingFunds` are the exceptions: their
  /// channels are CARRIED into the rebuilt session, so those subscriptions
  /// keep delivering and start reporting the NEW session at once. A
  /// transport chip rendered from `watchTorState` must not go silent here,
  /// because the rebuilt session is exactly where the private path can
  /// change. The swap service is re-initialised: call `enableNearSwap`
  /// again if you use it.
  ///
  /// Refusals BEFORE the swap leave everything exactly as it was — the
  /// handle stays open and usable: [WalletErrorKind.syncServerUnreachable],
  /// [WalletErrorKind.networkMismatch], [WalletErrorKind.syncServerNotOffered],
  /// [WalletErrorKind.walletBusy]. A fault PAST the stop-join (rare — a
  /// storage fault writing the choice, a wedged pass) leaves the handle
  /// CLOSED, exactly like a failed `rescanFrom`: re-`open` (the choice is
  /// honoured if its write landed). [WalletErrorKind.invalidState] if the
  /// handle is already closed. Through THIS bridge a concurrent call QUEUES
  /// behind the switch (the handle's write lock is held for the whole swap,
  /// probe and quiesce included) and resolves after it; only a direct Rust
  /// host sees [WalletErrorKind.walletBusy] carrying
  /// [LifecyclePhase.switchingServer] mid-swap. A switch that resolves to
  /// the server already in use — `https://zec.rocks` for `…:443` counts as
  /// the same — remembers the choice WITHOUT swapping the session (no loop
  /// restart, the sync judgement kept).
  Future<void> switchSyncServer({required SyncServerChoice choice});

  /// Sync for at most `budgetMs` milliseconds, then report how far the
  /// wallet got — for a host that holds the process only briefly (a
  /// background wake, a pull-to-refresh). ONE pass runs; when the budget
  /// runs out it stops the way `stopSync` stops the loop (progress kept,
  /// nothing half-written) and the call returns a report with
  /// `finished: false`, never an error. The budget is always yours: the SDK
  /// has no default and schedules nothing.
  ///
  /// **The bound:** the call returns within `budgetMs` plus one network
  /// request's timeout (30 s) — a request already in flight is not cut.
  /// Queued and in-flight sends are resubmitted after the pass only when the
  /// budget left covers that step's worst case (two minutes); otherwise
  /// `resubmitted` is `false` and the next `startSync` pass carries them.
  ///
  /// Throws [WalletErrorKind.syncRunning] while the `startSync` loop runs or
  /// another `syncFor` is in progress (stop the loop first; nothing ran);
  /// [WalletErrorKind.invalidState] on a closed handle; a pass that faults
  /// throws its error ([WalletErrorKind.sync] and the rest) with the same
  /// reason the `watchSyncStatus` stream shows.
  Future<BoundedSync> syncFor({required int budgetMs});

  /// Which server the wallet dials, which remembered choice produced it,
  /// and whether a fallback is in force. Render the HOST of `effectiveUrl`
  /// on the sync sheet's Server row — the connection's own truth, so the
  /// display and the dial can never drift. Readable in every lifecycle
  /// phase. [WalletErrorKind.invalidState] if the handle is closed.
  Future<SyncServerStatus> syncServerStatus();

  /// The sync servers this host OFFERS (`WalletConfig.syncServers`, as
  /// validated) — WITHOUT their keys: `authValue` is always `null` on this
  /// list (the host supplied it and holds it); `authHeader` says whether an
  /// entry is gated. The picker, P3-13.
  /// [WalletErrorKind.invalidState] if the handle is closed.
  Future<List<SyncServer>> syncServers();

  /// The wallet's transaction history (FR-1 — the activity-history list), newest
  /// first and paginated by an OPAQUE keyset cursor. Pending (unmined) rows sort
  /// ABOVE confirmed ones; `after = None` is the first page, `after = Some(token)`
  /// the page after the cursor (the [`HistoryPage::next_cursor`] from the previous
  /// call — passed back VERBATIM; never parse it); `limit` caps the page. The keyset
  /// cursor (full `(height, tx_index, txid)` sort key) means a page boundary never
  /// drops a same-height row nor strands the confirmed history behind a full page of
  /// pending txs. Each row is a typed [`TxSummary`](crate::api::state::TxSummary) (txid hex in block-explorer
  /// order, SIGNED net amount, status, fee, memo flag) — no key material, amounts
  /// stay typed. Reads librustzcash's audited `v_transactions` view off the engine
  /// lock, so it never blocks sync.
  Future<HistoryPage> transactions({required int limit, String? after});

  /// Cheap probe: is a COMPLETED, openable wallet provisioned at
  /// `config.dbDir`? Drives the host's boot fork — `false` → offer create,
  /// `true` → `open` it (then gate on backup confirmation). It is LOCK-FREE
  /// and does NOT open the wallet: it reads only the on-disk provisioning
  /// marker, so it never contends the single-writer lock the subsequent `open`
  /// needs (an `open`-and-catch-`notFound` would, and then break that `open`).
  ///
  /// `true` ONLY for a COMPLETED wallet. An interrupted-create remnant reads
  /// `false` and routes to `createGenerated`, which RESUMES its repair from
  /// the sealed seed (never clobbers) — the only path that finishes it, since
  /// `open` cannot repair a remnant (it throws
  /// [WalletErrorKind.provisioningIncomplete], having no seed source to
  /// resume). A corrupt store (a completion marker with no manifest) throws
  /// [WalletErrorKind.storeCorrupt] — the honest recover-from-phrase path,
  /// NEVER silently reported as "no wallet". Unlike `createGenerated`/`open`
  /// this validates ONLY `dbDir` (existence is a path question), not the
  /// endpoint/Tor policy.
  ///
  /// PLACEMENT (a deliberate, reversible choice): this is a `Self`-less static
  /// even though it returns `bool`, not a handle. It lives on `WalletHandle`
  /// because it is the THIRD boot-fork entry — the host drives
  /// `walletExists → open`/`createGenerated` as one sequence — so grouping the
  /// trio on the handle the provisioner owns keeps that coupling visible in
  /// Dart (`WalletHandle.walletExists` → `WalletHandle.open`). It is NOT the
  /// `validate_wallet_config` case (a settings-form pre-check with no boot/open
  /// intent — correctly a free function). If a host prefers a free function
  /// here, the move is mechanical (convert/core unchanged). Manager-flagged.
  static Future<bool> walletExists({required WalletConfig config}) =>
      ZecWalletRustLib.instance.api.crateApiWalletWalletHandleWalletExists(
        config: config,
      );

  /// Stream incoming-funds events (ADR-0536 — the FR-1 "funds arrived" hook):
  /// ONE `replay` event first (arrivals already in history strictly above
  /// `sinceCursor`; a null cursor gets a count-0 baseline that hands you a
  /// cursor to persist), then a `live` event per scan batch that detected
  /// arrivals, and a `memoRefresh` nudge when a later enhancement pass changes how
  /// existing rows read — either decrypted tx data landed, or a transaction's chain
  /// status did. Treat `memoRefresh` as "re-pull", never as "new memo data exists".
  ///
  /// The payload is DELIBERATELY minimal — counts, heights, and an opaque
  /// cursor; no txid, amount, memo, or address — so it is safe to log or to
  /// forward toward a notification path without a sanitizing layer. Pull the
  /// details via `transactions` in the main app (never in a notification
  /// extension). Delivery is AT-LEAST-ONCE with latest-wins coalescing:
  /// `totalTxDetected` is the reliable monotonic; counts/spans are advisory.
  /// A rescan or seed-restore REPLAYS history with old spans — gate any
  /// notification on `spanToHeight > your persisted watermark` (and your own
  /// consumed-txid ledger for exactly-once). `live` spans cover SHIELDED
  /// arrivals; a transparent receive surfaces via `memoRefresh` + the
  /// ordinary balance/history pulls (see [IncomingFundsEvent]).
  ///
  /// LIFECYCLE (flutter-patterns § Stream Lifecycle): cancel on `paused`,
  /// re-subscribe on a REAL `resumed` passing your persisted cursor — the
  /// `replay` event then covers anything missed while backgrounded. Desktop
  /// never fires `paused`, so the stream stays live while hidden. The pump
  /// holds no lock for its lifetime, so a live subscription never blocks
  /// `close`.
  ///
  /// Errors: [WalletErrorKind.invalidState] if the handle is closed;
  /// [WalletErrorKind.storeCorrupt] on a malformed `sinceCursor` (including a
  /// [HistoryPage.nextCursor] keyset token passed here by mistake — the two
  /// cursor families are deliberately incompatible, so the mix-up rejects
  /// typed instead of silently suppressing a catch-up).
  Stream<IncomingFundsEvent> watchIncomingFunds({String? sinceCursor});

  /// The live [SwapStatus] stream for one in-flight swap (spec §3.3/§7) — the swap
  /// parallel of `watchSyncStatus`. `swapId` is the opaque id `swapExecute` returned.
  /// The stream emits the CURRENT status immediately, then polls at a bounded
  /// exponential cadence (5→60s; §7), coalescing onto each change. It NEVER completes
  /// on a transient provider fault (a stall is retried, never a dead stream) — it
  /// completes only on a TERMINAL status (success/refunded/failed), when the host
  /// cancels the subscription, or when the wallet is closed/swap is hard-killed (§3.5).
  ///
  /// LIFECYCLE (flutter-patterns § Stream Lifecycle): foreground-only — cancel on
  /// `AppLifecycleState.paused`, re-subscribe on a REAL `resumed` (it re-emits the
  /// current status at once). Desktop never fires `paused`, so it stays live while
  /// hidden. The core owns the detached poll pump and holds no lock for the stream's
  /// life, so a live subscription never blocks `close`. The `swapId` is NEVER logged
  /// (§5.4); an empty/over-bound id is rejected typed (a host bug), never a spinning
  /// stream.
  ///
  /// Errors (delivered as a stream error): [SwapErrorKind.swapDisabled] when no
  /// provider is attached, [SwapErrorKind.swapStateUnavailable] on a closed handle,
  /// [SwapErrorKind.requestInvalid] for an empty/over-bound id.
  Stream<SwapStatus> watchSwapStatus({required String swapId});

  /// The live `SyncStatus` stream (spec §3.3) — the host's honest sync
  /// indicator. The stream emits the CURRENT status immediately on subscribe
  /// (so re-subscribing after an `AppLifecycleState.paused` gap re-renders at
  /// once), then every change coalesced latest-wins (a burst never floods the
  /// UI). It NEVER completes on a transient fault — a stall is a
  /// `SyncStatus.stalled` EVENT, not an error or EOF; it completes only when
  /// the host cancels the subscription or the wallet is closed (a final status
  /// is drained first). Call `startSync` for it to advance past `idle`.
  ///
  /// LIFECYCLE (flutter-patterns § Stream Lifecycle): cancel this on `paused`
  /// and re-subscribe on a REAL `resumed` (re-fetch the cold balance via
  /// `snapshot`, then re-subscribe for live changes); a stream error or
  /// completion is itself a reconnect trigger, independent of lifecycle.
  /// Desktop never fires `paused`, so the stream stays live while hidden (the
  /// wanted behavior). The pump holds no lock for its lifetime, so a live
  /// subscription never blocks `close`.
  ///
  /// Errors (delivered as a stream error): [WalletErrorKind.invalidState] if
  /// the handle is already closed.
  Stream<SyncStatus> watchSyncStatus();

  /// The live [TorState] stream — the transport state as it changes, so a
  /// host renders the private path's truth without polling `snapshot`. The
  /// stream emits the CURRENT state immediately on subscribe, then every
  /// change coalesced latest-wins: the moment a `preferred` wallet leaves the
  /// private path ([TorState.fellBack] — the switch a user should be told
  /// about), and the moment a ready path has carried nothing for a minute
  /// ([TorState.unanswered]). It NEVER completes on a transient fault; it
  /// completes only when the host cancels the subscription, the wallet is
  /// closed, or `rescanFrom` rebuilds the session (which ends every live
  /// stream — re-subscribe after a rescan). A `switchSyncServer` does NOT
  /// end it: the stream is carried across the swap and reports the new
  /// session. Readable in every lifecycle phase, like `snapshot`'s `tor`.
  ///
  /// LIFECYCLE (flutter-patterns § Stream Lifecycle): cancel this on `paused`
  /// and re-subscribe on a REAL `resumed` — snapshot FIRST, then
  /// re-subscribe: a transition that happened while the sink was paused is
  /// not replayed (the clock keeps running while the app is backgrounded),
  /// and the snapshot is where it is read. The first event after
  /// re-subscribing is the state as of that call. The pump holds no lock for
  /// its lifetime, so a live subscription never blocks `close`.
  ///
  /// Errors (delivered as a stream error): [WalletErrorKind.invalidState] if
  /// the handle is already closed.
  Stream<TorState> watchTorState();

  /// Delete the wallet at `config.dbDir` (FR-14) — the host's "delete wallet" /
  /// panic-wipe primitive. Deletes the keychain wrap key FIRST (so on any crash
  /// point this key store can no longer open the on-disk seals or the DB
  /// ciphertext; how strong that is is `custodyDisclosure`'s `eraseAssurance`,
  /// ADR-0571), then removes the data directory. The seed NEVER crosses this bridge — only the
  /// config does.
  ///
  /// A `Self`-less static (like `walletExists`) because a wipe runs with no live
  /// handle — typically AFTER `close` (panic-wipe runs post-teardown). It
  /// **refuses while an instance is open** ([WalletErrorKind.walletOpen]): close
  /// the handle first, then wipe. Idempotent — a no-wallet `dbDir` is a no-op,
  /// and an interrupted wipe auto-converges on a plain re-run.
  ///
  /// **Fail-closed money safety:** if `config.dbDir` does not byte-match the
  /// create/open path, the per-wallet keychain namespace is mis-derived; rather
  /// than delete the files while the real wrap key survives, a non-empty store
  /// whose custody sever removed nothing fails CLOSED
  /// ([WalletErrorKind.keystoreInconsistent], files untouched). Pass the SAME
  /// `config` you opened with. The rare already-gone-item case is the
  /// `wipeForce` escape hatch.
  ///
  /// **Do NOT auto-escalate a `keystoreInconsistent` into `wipeForce`.** That
  /// would defeat the guard — `keystoreInconsistent` is the same signal a
  /// mis-derived `dbDir` raises, and forcing past it can downgrade a true
  /// crypto-erase to best-effort (deleting files while a real wrap key survives).
  /// Reach for `wipeForce` only deliberately, for a wallet you are CERTAIN is
  /// yours whose custody item is genuinely gone.
  ///
  /// **Erase strength is per-device** — render `custodyDisclosure` BEFORE this
  /// to tell the user honestly whether deletion removes a key held by secure
  /// hardware or is best-effort removal. Neither is a proven permanent erase
  /// (ADR-0571).
  ///
  /// **The device log goes Off.** Any call, a failed one included, first
  /// closes the `watchDeviceLog` stream and sets the device log `Off`. It
  /// stays Off until the host re-arms it with `setDeviceLog` and
  /// `watchDeviceLog`. A host must not re-arm on a duress path.
  static Future<void> wipe({required WalletConfig config}) => ZecWalletRustLib
      .instance
      .api
      .crateApiWalletWalletHandleWipe(config: config);

  /// Force-complete a `wipe` whose keychain custody item is ALREADY GONE — the
  /// escape hatch for the rare states where a plain `wipe` returns
  /// [WalletErrorKind.keystoreInconsistent] (a manually-deleted item, a
  /// pre-namespacing bare item, an iOS `ThisDeviceOnly` item that didn't migrate
  /// while `dbDir` did). It SKIPS the verify-real-sever guard, so the caller MUST
  /// be certain `config` matches the wallet's create/open config — a wrong config
  /// under force would delete the wrong files. Use ONLY after a plain `wipe`
  /// returned `keystoreInconsistent` on a wallet you are sure is yours.
  ///
  /// **HOST CONTRACT — run with the device UNLOCKED.** On Apple Secure-Enclave
  /// custody a locked-device key can be invisible to the purge; forcing past the
  /// guard while locked could delete the seals while the wrap key survives,
  /// silently downgrading the crypto-erase. Ensure protected data is available
  /// (device unlocked) before calling.
  ///
  /// **The device log goes Off**, as for `wipe`: any call, a failed one
  /// included, first closes the `watchDeviceLog` stream and sets the device
  /// log `Off` until the host re-arms it.
  static Future<void> wipeForce({required WalletConfig config}) =>
      ZecWalletRustLib.instance.api.crateApiWalletWalletHandleWipeForce(
        config: config,
      );
}

/// FR-14 H1 — the PRODUCTION per-tier custody honesty a host renders BEFORE a
/// [WalletHandle.wipe] (and as an ambient "your keys are protected by …" badge).
/// Non-secret by construction (a tier label + two booleans). Distinct from the
/// diagnostic `selftestSeedCustody` / `CustodyReport`, which provisions
/// selftest identities and must NOT drive shipped UX — this query touches no
/// seed and unseals nothing; it reads only the measured vault tier.
///
/// **HOST UX CONTRACT (branch on the right field).** `eraseAssurance` and
/// `degraded` are SEPARATE axes — do not collapse them:
/// - Gate the WIPE confirmation on `eraseAssurance` (a hardware-held key
///   deleted vs best-effort). NOT on `degraded` — `"apple_keychain"` (raw
///   fallback) is best-effort yet reports `degraded == false`.
/// - For a "your keys are protected by hardware" BADGE, require
///   `eraseAssurance == EraseAssurance.hardwareKeyDeleted` — do NOT gate it on
///   `!degraded`, because `tier == "none"` (no keystore at all — strictly worse
///   than a software keystore) ALSO reports `degraded == false`. Treat
///   `"none"`/`"unknown"` as NOT protected.
/// - Never tell the user a deleted key is "permanently unrecoverable": no value
///   of `eraseAssurance` establishes that (ADR-0571).
class CustodyDisclosure {
  /// Measured vault tier: `"strongbox"` | `"tee"` | `"software_keystore"` |
  /// `"apple_keychain"` | `"apple_secure_enclave"` | `"none"` | `"unknown"`.
  /// `"none"` = no platform key vault (a headless desktop); `"unknown"` is the
  /// forward arm for a newer core. The label is diagnostic — `eraseAssurance`
  /// and `degraded` are the load-bearing predicates a host branches on.
  final String tier;

  /// What [WalletHandle.wipe] does to this wallet's custody key on this
  /// device. `hardwareKeyDeleted` only for hardware-held custody (StrongBox /
  /// TEE / Apple Secure Enclave). `bestEffort` otherwise (incl.
  /// `"apple_keychain"` raw fallback, `"software_keystore"`, and `"none"`):
  /// render the honest "a forensic recovery window remains until the OS
  /// reclaims storage" disclosure (and, for full assurance, the device's own
  /// Erase-All-Content). THIS is the field the wipe confirmation branches on,
  /// not `degraded`.
  final EraseAssurance eraseAssurance;

  /// The §4.3a degraded-custody predicate — `true` ONLY when custody is rooted
  /// in a software keystore (Android `software_keystore`); the host renders a
  /// degraded-custody warning. NOTE it is `false` for BOTH the hardware tiers
  /// AND for `"none"` (no keystore) AND `"apple_keychain"` (raw best-effort) —
  /// so `!degraded` does NOT mean "protected". A "hardware-protected" badge must
  /// require `eraseAssurance == hardwareKeyDeleted`; `degraded` only
  /// distinguishes the software-keystore tier for an explicit "weaker custody"
  /// warning.
  final bool degraded;

  const CustodyDisclosure({
    required this.tier,
    required this.eraseAssurance,
    required this.degraded,
  });

  @override
  int get hashCode =>
      tier.hashCode ^ eraseAssurance.hashCode ^ degraded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustodyDisclosure &&
          runtimeType == other.runtimeType &&
          tier == other.tier &&
          eraseAssurance == other.eraseAssurance &&
          degraded == other.degraded;
}

/// What deleting a wallet's custody key does (ADR-0571). Neither value claims
/// the key can never come back: a platform establishes that only for a key it
/// keeps rollback-resistant, which this release does not request or check.
enum EraseAssurance {
  /// The key was held by secure hardware (StrongBox, TEE, Secure Enclave),
  /// never usable outside it, and the wipe deletes it.
  hardwareKeyDeleted,

  /// The key was stored as data, or there is no keystore; the wipe deletes it,
  /// and a copy may remain in storage until the device reclaims it.
  bestEffort,

  /// A value from a newer core this bridge does not know. Treat it as
  /// `bestEffort`: never render more custody than you can name. Always last.
  unknown,
}
