// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for rust/include/zec_wallet_tor.h. Regenerate with `dart run ffigen --config ffigen.yaml`; never edit by hand.
class ZecWalletTorBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ZecWalletTorBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ZecWalletTorBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// The version of this header's contract: ZWT_ABI_VERSION. Pure.
  int zec_wallet_tor_abi_version() {
    return _zec_wallet_tor_abi_version();
  }

  late final _zec_wallet_tor_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'zec_wallet_tor_abi_version',
      );
  late final _zec_wallet_tor_abi_version = _zec_wallet_tor_abi_versionPtr
      .asFunction<int Function()>();

  /// Build the runtime (first init only), check and build the arti config,
  /// resolve the wallet's verbs, REGISTER at readiness 0, then start the
  /// bootstrap. Idempotent: a second call answers ZWT_RC_OK and re-registers
  /// nothing. `on_status` may be NULL (no callback); `ctx` is passed back.
  /// ZWT_RC_STOPPING (nothing changed) while a client from before a dispose is
  /// still stopping: the new client would share its state directory;
  /// ZWT_RC_RESTART_REQUIRED if one did not finish shutting down in time.
  int zec_wallet_tor_init(
    ffi.Pointer<zwt_config> config,
    zwt_status_fn on_status,
    ffi.Pointer<ffi.Void> ctx,
  ) {
    return _zec_wallet_tor_init(config, on_status, ctx);
  }

  late final _zec_wallet_tor_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<zwt_config>,
            zwt_status_fn,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('zec_wallet_tor_init');
  late final _zec_wallet_tor_init = _zec_wallet_tor_initPtr
      .asFunction<
        int Function(
          ffi.Pointer<zwt_config>,
          zwt_status_fn,
          ffi.Pointer<ffi.Void>,
        )
      >();

  /// The current status, written into `*out`.
  int zec_wallet_tor_status(ffi.Pointer<zwt_status> out) {
    return _zec_wallet_tor_status(out);
  }

  late final _zec_wallet_tor_statusPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<zwt_status>)>>(
        'zec_wallet_tor_status',
      );
  late final _zec_wallet_tor_status = _zec_wallet_tor_statusPtr
      .asFunction<int Function(ffi.Pointer<zwt_status>)>();

  /// Replace the bridge lines ((NULL, 0) = none) and rebuild the client. A
  /// refused paste leaves the running client untouched. ZWT_RC_RESTART_REQUIRED
  /// (nothing changed, the current bridges stay in use) while an earlier client
  /// is stuck: no new client may start until the app restarts.
  int zec_wallet_tor_set_bridges(
    ffi.Pointer<ffi.Uint8> bridges,
    int bridges_len,
  ) {
    return _zec_wallet_tor_set_bridges(bridges, bridges_len);
  }

  late final _zec_wallet_tor_set_bridgesPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Uint8>, ffi.Size)>
      >('zec_wallet_tor_set_bridges');
  late final _zec_wallet_tor_set_bridges = _zec_wallet_tor_set_bridgesPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// A user-driven retry: cancels the backoff wait and bootstraps now. A no-op
  /// unless the phase is FAILED.
  int zec_wallet_tor_retry_bootstrap() {
    return _zec_wallet_tor_retry_bootstrap();
  }

  late final _zec_wallet_tor_retry_bootstrapPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'zec_wallet_tor_retry_bootstrap',
      );
  late final _zec_wallet_tor_retry_bootstrap =
      _zec_wallet_tor_retry_bootstrapPtr.asFunction<int Function()>();

  /// Remove the plugin's Tor state under `tor_dir` — the Tor-identity reset in a
  /// host's wipe flow (dispose -> wallet wipe -> clear_state). Removes ONLY the
  /// two subtrees the plugin creates, `<tor_dir>/state` and `<tor_dir>/cache`,
  /// then `tor_dir` itself if (and only if) it is left empty — never anything
  /// else under the path, so a host that passes the wrong directory (the
  /// wallet's db_dir, say) loses nothing of its own. Idempotent; safe after a
  /// wallet wipe and after a restart with no init; ZWT_RC_NOT_INITIALIZED while
  /// an engine runs; ZWT_RC_STOPPING (nothing removed) while an earlier client
  /// is still stopping, so a removal is never followed by that client's late
  /// state write — call again shortly. Each client runs on its own runtime,
  /// which is shut down when the client is retired; that shutdown ends every
  /// task arti started, its last state write included. ZWT_RC_OK means the state
  /// is gone and every client of this process has finished. If a shutdown does
  /// not finish in time, this answers ZWT_RC_RESTART_REQUIRED for the rest of
  /// the process: restart the app and clear before init. Do not call init until
  /// the wipe has finished. Either refusal means the reset is RECORDED on disk
  /// in tor_dir (unless tor_dir does not exist: nothing to reset), and the next
  /// init finishes it before Tor starts; a reset that cannot be recorded answers
  /// ZWT_RC_INVALID_DATA_DIR instead (nothing removed, nothing pending).
  int zec_wallet_tor_clear_state(
    ffi.Pointer<ffi.Uint8> tor_dir,
    int tor_dir_len,
  ) {
    return _zec_wallet_tor_clear_state(tor_dir, tor_dir_len);
  }

  late final _zec_wallet_tor_clear_statePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Uint8>, ffi.Size)>
      >('zec_wallet_tor_clear_state');
  late final _zec_wallet_tor_clear_state = _zec_wallet_tor_clear_statePtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// Retire the registration, drain the plugin's own outstanding operations
  /// (bounded), CLEAR the wallet's slot, drop the engine. After it the phase is
  /// NOT_REGISTERED; a later init registers afresh. The wait is bounded (it runs
  /// on the caller's thread), so a client can still be stopping when it returns
  /// ZWT_RC_OK: unregistered is not stopped. clear_state and init answer
  /// ZWT_RC_STOPPING until it has (ZWT_RC_RESTART_REQUIRED if it never does).
  int zec_wallet_tor_dispose() {
    return _zec_wallet_tor_dispose();
  }

  late final _zec_wallet_tor_disposePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'zec_wallet_tor_dispose',
      );
  late final _zec_wallet_tor_dispose = _zec_wallet_tor_disposePtr
      .asFunction<int Function()>();

  /// The app lifecycle, forwarded from the host's Dart: `paused` pushes
  /// readiness 0 and quiets arti; `resumed` wakes it (or rebuilds after a long
  /// pause).
  int zec_wallet_tor_on_paused() {
    return _zec_wallet_tor_on_paused();
  }

  late final _zec_wallet_tor_on_pausedPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'zec_wallet_tor_on_paused',
      );
  late final _zec_wallet_tor_on_paused = _zec_wallet_tor_on_pausedPtr
      .asFunction<int Function()>();

  int zec_wallet_tor_on_resumed() {
    return _zec_wallet_tor_on_resumed();
  }

  late final _zec_wallet_tor_on_resumedPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'zec_wallet_tor_on_resumed',
      );
  late final _zec_wallet_tor_on_resumed = _zec_wallet_tor_on_resumedPtr
      .asFunction<int Function()>();
}

/// The plugin's status, by value. Four closed integers — nothing else.
final class zwt_status extends ffi.Struct {
  /// ZWT_PHASE_*
  @ffi.Uint32()
  external int phase;

  /// 0..=100: the readiness LAST PUSHED to the wallet
  @ffi.Uint32()
  external int readiness;

  /// ZWT_BLOCKAGE_*
  @ffi.Uint32()
  external int blockage;

  /// ZWT_CLASS_*
  @ffi.Uint32()
  external int failure_class;
}

/// init's configuration: two byte spans, valid for the call only.
/// tor_dir: UTF-8, absolute, a SIBLING of the wallet's db_dir — never db_dir
/// itself nor inside it. Required (tor_dir_len > 0).
/// bridges: UTF-8 bridge lines as pasted; (NULL, 0) = no bridges.
final class zwt_config extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> tor_dir;

  @ffi.Size()
  external int tor_dir_len;

  external ffi.Pointer<ffi.Uint8> bridges;

  @ffi.Size()
  external int bridges_len;
}

typedef zwt_status_fnFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> ctx,
      ffi.Pointer<zwt_status> status,
    );
typedef Dartzwt_status_fnFunction =
    void Function(ffi.Pointer<ffi.Void> ctx, ffi.Pointer<zwt_status> status);

/// Called on every phase or readiness change, from ANY plugin thread; the Dart
/// side receives it through `NativeCallable.listener`. `status` is valid for
/// the call only.
typedef zwt_status_fn = ffi.Pointer<ffi.NativeFunction<zwt_status_fnFunction>>;

const int ZWT_ABI_VERSION = 1;

const int ZWT_RC_OK = 0;

const int ZWT_RC_WALLET_NOT_LOADED = -1;

const int ZWT_RC_ABI_MISMATCH = -2;

const int ZWT_RC_SLOT_OCCUPIED = -3;

const int ZWT_RC_REGISTRY_POISONED = -4;

const int ZWT_RC_DESCRIPTOR_REFUSED = -5;

const int ZWT_RC_INVALID_DATA_DIR = -6;

const int ZWT_RC_BRIDGES_REFUSED = -7;

const int ZWT_RC_ENGINE_SETUP = -8;

const int ZWT_RC_NOT_INITIALIZED = -9;

const int ZWT_RC_DISPOSED = -10;

const int ZWT_RC_NULL_ARG = -11;

const int ZWT_RC_PANICKED = -12;

const int ZWT_RC_STOPPING = -13;

const int ZWT_RC_RESTART_REQUIRED = -14;

const int ZWT_PHASE_IDLE = 0;

const int ZWT_PHASE_BOOTSTRAPPING = 1;

const int ZWT_PHASE_READY = 2;

const int ZWT_PHASE_FAILED = 3;

const int ZWT_PHASE_SUSPENDED = 4;

const int ZWT_PHASE_NOT_REGISTERED = 5;

const int ZWT_BLOCKAGE_NONE = 0;

const int ZWT_BLOCKAGE_DISABLED = 1;

const int ZWT_BLOCKAGE_OFFLINE = 2;

const int ZWT_BLOCKAGE_FILTERING = 3;

const int ZWT_BLOCKAGE_CANT_REACH_TOR = 4;

const int ZWT_BLOCKAGE_CLOCK_SKEWED = 5;

const int ZWT_BLOCKAGE_CANT_BOOTSTRAP = 6;

const int ZWT_BLOCKAGE_UNKNOWN = 7;

const int ZWT_CLASS_NONE = 0;

const int ZWT_CLASS_BOOTSTRAP_DEADLINE = 1;

const int ZWT_CLASS_NOT_REGISTERED = 2;

const int ZWT_CLASS_BOOTSTRAP_FAILED = 3;

const int ZWT_CLASS_SETUP = 4;

const int ZWT_CLASS_NOT_BOOTSTRAPPED = 5;

const int ZWT_CLASS_BRIDGE_CONFIG_TOO_LONG = 6;

const int ZWT_CLASS_BRIDGE_TOO_MANY_LINES = 7;

const int ZWT_CLASS_BRIDGE_LINE_TOO_LONG = 8;

const int ZWT_CLASS_BRIDGE_PT_UNSUPPORTED = 9;

const int ZWT_CLASS_BRIDGE_UNUSABLE = 10;

const int ZWT_CLASS_BRIDGE_LINE_EMPTY = 11;

const int ZWT_CLASS_BRIDGE_INVALID_TRANSPORT_OR_ADDRESS = 12;

const int ZWT_CLASS_BRIDGE_INVALID_ADDRESS = 13;

const int ZWT_CLASS_BRIDGE_INVALID_IDENTITY = 14;

const int ZWT_CLASS_BRIDGE_DUPLICATE_IDENTITY = 15;

const int ZWT_CLASS_BRIDGE_UNSUPPORTED_IDENTITY_TYPE = 16;

const int ZWT_CLASS_BRIDGE_UNSUPPORTED_CHANNEL_METHOD = 17;

const int ZWT_CLASS_BRIDGE_DIRECT_PARAMETERS_NOT_ALLOWED = 18;

const int ZWT_CLASS_BRIDGE_NO_RSA_IDENTITY = 19;

const int ZWT_CLASS_BRIDGE_SUPPORT_DISABLED = 20;

const int ZWT_CLASS_CIRCUITS_FAILING = 21;
