// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/config.dart';
import 'api/error.dart';
import 'api/meta.dart';
import 'api/payments.dart';
import 'api/restore.dart';
import 'api/selftest.dart';
import 'api/state.dart';
import 'api/swap.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class ZecWalletRustLibApiImplPlatform
    extends BaseApiImpl<ZecWalletRustLibWire> {
  ZecWalletRustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WalletHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  WalletHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    dynamic raw,
  );

  @protected
  WalletHandle
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    dynamic raw,
  );

  @protected
  WalletHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    dynamic raw,
  );

  @protected
  WalletHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    dynamic raw,
  );

  @protected
  RustStreamSink<DeviceLogLine> dco_decode_StreamSink_device_log_line_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<IncomingFundsEvent>
  dco_decode_StreamSink_incoming_funds_event_Sse(dynamic raw);

  @protected
  RustStreamSink<SwapStatus> dco_decode_StreamSink_swap_status_Sse(dynamic raw);

  @protected
  RustStreamSink<SyncStatus> dco_decode_StreamSink_sync_status_Sse(dynamic raw);

  @protected
  RustStreamSink<TorState> dco_decode_StreamSink_tor_state_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressKind dco_decode_address_kind(dynamic raw);

  @protected
  ArmCounts dco_decode_arm_counts(dynamic raw);

  @protected
  AssetId dco_decode_asset_id(dynamic raw);

  @protected
  BalanceSnapshot dco_decode_balance_snapshot(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BoundedSync dco_decode_bounded_sync(dynamic raw);

  @protected
  AssetId dco_decode_box_autoadd_asset_id(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DeliveryState dco_decode_box_autoadd_delivery_state(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LargeSendReason dco_decode_box_autoadd_large_send_reason(dynamic raw);

  @protected
  PoolServiceReport dco_decode_box_autoadd_pool_service_report(dynamic raw);

  @protected
  QuoteRequest dco_decode_box_autoadd_quote_request(dynamic raw);

  @protected
  SendProposal dco_decode_box_autoadd_send_proposal(dynamic raw);

  @protected
  SigningBlock dco_decode_box_autoadd_signing_block(dynamic raw);

  @protected
  SwapAmount dco_decode_box_autoadd_swap_amount(dynamic raw);

  @protected
  SwapKill dco_decode_box_autoadd_swap_kill(dynamic raw);

  @protected
  SwapOutcome dco_decode_box_autoadd_swap_outcome(dynamic raw);

  @protected
  SwapProviderConfig dco_decode_box_autoadd_swap_provider_config(dynamic raw);

  @protected
  SwapQuote dco_decode_box_autoadd_swap_quote(dynamic raw);

  @protected
  SyncServerChoice dco_decode_box_autoadd_sync_server_choice(dynamic raw);

  @protected
  SyncServerFallback dco_decode_box_autoadd_sync_server_fallback(dynamic raw);

  @protected
  SyncServerKey dco_decode_box_autoadd_sync_server_key(dynamic raw);

  @protected
  SyncStamp dco_decode_box_autoadd_sync_stamp(dynamic raw);

  @protected
  TorRuntimeConfig dco_decode_box_autoadd_tor_runtime_config(dynamic raw);

  @protected
  TorRuntimeKind dco_decode_box_autoadd_tor_runtime_kind(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UnknownBranchGrace dco_decode_box_autoadd_unknown_branch_grace(dynamic raw);

  @protected
  WalletConfig dco_decode_box_autoadd_wallet_config(dynamic raw);

  @protected
  CustodyDisclosure dco_decode_custody_disclosure(dynamic raw);

  @protected
  CustodyReport dco_decode_custody_report(dynamic raw);

  @protected
  DeliveryState dco_decode_delivery_state(dynamic raw);

  @protected
  DestinationInvalidReason dco_decode_destination_invalid_reason(dynamic raw);

  @protected
  DeviceLogLevel dco_decode_device_log_level(dynamic raw);

  @protected
  DeviceLogLine dco_decode_device_log_line(dynamic raw);

  @protected
  DeviceLogSeverity dco_decode_device_log_severity(dynamic raw);

  @protected
  DialCounts dco_decode_dial_counts(dynamic raw);

  @protected
  DisclosureItem dco_decode_disclosure_item(dynamic raw);

  @protected
  EphemeralSweepSummary dco_decode_ephemeral_sweep_summary(dynamic raw);

  @protected
  EraseAssurance dco_decode_erase_assurance(dynamic raw);

  @protected
  ExactSide dco_decode_exact_side(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FilesOutcome dco_decode_files_outcome(dynamic raw);

  @protected
  GraceExpiry dco_decode_grace_expiry(dynamic raw);

  @protected
  HistoryPage dco_decode_history_page(dynamic raw);

  @protected
  HolderSeen dco_decode_holder_seen(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InFlightSend dco_decode_in_flight_send(dynamic raw);

  @protected
  IncomingFundsEvent dco_decode_incoming_funds_event(dynamic raw);

  @protected
  IncomingFundsEventKind dco_decode_incoming_funds_event_kind(dynamic raw);

  @protected
  IsolationSupport dco_decode_isolation_support(dynamic raw);

  @protected
  JitterPolicy dco_decode_jitter_policy(dynamic raw);

  @protected
  LargeSendReason dco_decode_large_send_reason(dynamic raw);

  @protected
  LifecyclePhase dco_decode_lifecycle_phase(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DisclosureItem> dco_decode_list_disclosure_item(dynamic raw);

  @protected
  List<InFlightSend> dco_decode_list_in_flight_send(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ParkedSend> dco_decode_list_parked_send(dynamic raw);

  @protected
  List<ParsedPayment> dco_decode_list_parsed_payment(dynamic raw);

  @protected
  List<PaymentDraft> dco_decode_list_payment_draft(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProposalRecipient> dco_decode_list_proposal_recipient(dynamic raw);

  @protected
  List<ProposalStep> dco_decode_list_proposal_step(dynamic raw);

  @protected
  List<RecoverableEphemeralFunds> dco_decode_list_recoverable_ephemeral_funds(
    dynamic raw,
  );

  @protected
  List<SwapRecord> dco_decode_list_swap_record(dynamic raw);

  @protected
  List<SwapStatus> dco_decode_list_swap_status(dynamic raw);

  @protected
  List<SwapToken> dco_decode_list_swap_token(dynamic raw);

  @protected
  List<SyncServer> dco_decode_list_sync_server(dynamic raw);

  @protected
  List<SyncStatus> dco_decode_list_sync_status(dynamic raw);

  @protected
  List<TorState> dco_decode_list_tor_state(dynamic raw);

  @protected
  List<TxSubmitResult> dco_decode_list_tx_submit_result(dynamic raw);

  @protected
  List<TxSummary> dco_decode_list_tx_summary(dynamic raw);

  @protected
  MintedDiversifiedAddress dco_decode_minted_diversified_address(dynamic raw);

  @protected
  Network dco_decode_network(dynamic raw);

  @protected
  NotSeveredCause dco_decode_not_severed_cause(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  DeliveryState? dco_decode_opt_box_autoadd_delivery_state(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LargeSendReason? dco_decode_opt_box_autoadd_large_send_reason(dynamic raw);

  @protected
  PoolServiceReport? dco_decode_opt_box_autoadd_pool_service_report(
    dynamic raw,
  );

  @protected
  SendProposal? dco_decode_opt_box_autoadd_send_proposal(dynamic raw);

  @protected
  SigningBlock? dco_decode_opt_box_autoadd_signing_block(dynamic raw);

  @protected
  SwapKill? dco_decode_opt_box_autoadd_swap_kill(dynamic raw);

  @protected
  SwapOutcome? dco_decode_opt_box_autoadd_swap_outcome(dynamic raw);

  @protected
  SyncServerChoice? dco_decode_opt_box_autoadd_sync_server_choice(dynamic raw);

  @protected
  SyncServerFallback? dco_decode_opt_box_autoadd_sync_server_fallback(
    dynamic raw,
  );

  @protected
  SyncServerKey? dco_decode_opt_box_autoadd_sync_server_key(dynamic raw);

  @protected
  SyncStamp? dco_decode_opt_box_autoadd_sync_stamp(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SyncServer>? dco_decode_opt_list_sync_server(dynamic raw);

  @protected
  OutputPool dco_decode_output_pool(dynamic raw);

  @protected
  ParkedAuthorization dco_decode_parked_authorization(dynamic raw);

  @protected
  ParkedSend dco_decode_parked_send(dynamic raw);

  @protected
  ParkedSendKind dco_decode_parked_send_kind(dynamic raw);

  @protected
  ParsedMemo dco_decode_parsed_memo(dynamic raw);

  @protected
  ParsedPayment dco_decode_parsed_payment(dynamic raw);

  @protected
  PaymentDraft dco_decode_payment_draft(dynamic raw);

  @protected
  PoolService dco_decode_pool_service(dynamic raw);

  @protected
  PoolServiceReport dco_decode_pool_service_report(dynamic raw);

  @protected
  ProposalRecipient dco_decode_proposal_recipient(dynamic raw);

  @protected
  ProposalStep dco_decode_proposal_step(dynamic raw);

  @protected
  ProviderProtocolReason dco_decode_provider_protocol_reason(dynamic raw);

  @protected
  QuoteBoundSide dco_decode_quote_bound_side(dynamic raw);

  @protected
  QuoteRequest dco_decode_quote_request(dynamic raw);

  @protected
  ReclaimOutcome dco_decode_reclaim_outcome(dynamic raw);

  @protected
  RecoverableEphemeralFunds dco_decode_recoverable_ephemeral_funds(dynamic raw);

  @protected
  ReservationPressure dco_decode_reservation_pressure(dynamic raw);

  @protected
  SeedPersistence dco_decode_seed_persistence(dynamic raw);

  @protected
  SelftestBundle dco_decode_selftest_bundle(dynamic raw);

  @protected
  SendProposal dco_decode_send_proposal(dynamic raw);

  @protected
  SeverOutcome dco_decode_sever_outcome(dynamic raw);

  @protected
  SeverReport dco_decode_sever_report(dynamic raw);

  @protected
  SigningBlock dco_decode_signing_block(dynamic raw);

  @protected
  StallReason dco_decode_stall_reason(dynamic raw);

  @protected
  SwapAddressCheckRefusal dco_decode_swap_address_check_refusal(dynamic raw);

  @protected
  SwapAddressCheckReport dco_decode_swap_address_check_report(dynamic raw);

  @protected
  SwapAddressCoverage dco_decode_swap_address_coverage(dynamic raw);

  @protected
  SwapAmount dco_decode_swap_amount(dynamic raw);

  @protected
  SwapApiError dco_decode_swap_api_error(dynamic raw);

  @protected
  SwapDirection dco_decode_swap_direction(dynamic raw);

  @protected
  SwapErrorKind dco_decode_swap_error_kind(dynamic raw);

  @protected
  SwapFailureCode dco_decode_swap_failure_code(dynamic raw);

  @protected
  SwapKill dco_decode_swap_kill(dynamic raw);

  @protected
  SwapOutcome dco_decode_swap_outcome(dynamic raw);

  @protected
  SwapPrivacyDisclosure dco_decode_swap_privacy_disclosure(dynamic raw);

  @protected
  SwapProviderConfig dco_decode_swap_provider_config(dynamic raw);

  @protected
  SwapQuote dco_decode_swap_quote(dynamic raw);

  @protected
  SwapRecord dco_decode_swap_record(dynamic raw);

  @protected
  SwapRecordDirection dco_decode_swap_record_direction(dynamic raw);

  @protected
  SwapStatus dco_decode_swap_status(dynamic raw);

  @protected
  SwapToken dco_decode_swap_token(dynamic raw);

  @protected
  SwapTokenList dco_decode_swap_token_list(dynamic raw);

  @protected
  SyncServer dco_decode_sync_server(dynamic raw);

  @protected
  SyncServerChoice dco_decode_sync_server_choice(dynamic raw);

  @protected
  SyncServerFallback dco_decode_sync_server_fallback(dynamic raw);

  @protected
  SyncServerKey dco_decode_sync_server_key(dynamic raw);

  @protected
  SyncServerProbe dco_decode_sync_server_probe(dynamic raw);

  @protected
  SyncServerStatus dco_decode_sync_server_status(dynamic raw);

  @protected
  SyncStamp dco_decode_sync_stamp(dynamic raw);

  @protected
  SyncStatus dco_decode_sync_status(dynamic raw);

  @protected
  TorPolicy dco_decode_tor_policy(dynamic raw);

  @protected
  TorRuntimeConfig dco_decode_tor_runtime_config(dynamic raw);

  @protected
  TorRuntimeKind dco_decode_tor_runtime_kind(dynamic raw);

  @protected
  TorState dco_decode_tor_state(dynamic raw);

  @protected
  TransportExposure dco_decode_transport_exposure(dynamic raw);

  @protected
  TxStatus dco_decode_tx_status(dynamic raw);

  @protected
  TxSubmitResult dco_decode_tx_submit_result(dynamic raw);

  @protected
  TxSummary dco_decode_tx_summary(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnknownBranchGrace dco_decode_unknown_branch_grace(dynamic raw);

  @protected
  UnprovenReason dco_decode_unproven_reason(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ValidatedAddress dco_decode_validated_address(dynamic raw);

  @protected
  WalletApiError dco_decode_wallet_api_error(dynamic raw);

  @protected
  WalletConfig dco_decode_wallet_config(dynamic raw);

  @protected
  WalletErrorKind dco_decode_wallet_error_kind(dynamic raw);

  @protected
  WalletState dco_decode_wallet_state(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  WalletHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    SseDeserializer deserializer,
  );

  @protected
  WalletHandle
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    SseDeserializer deserializer,
  );

  @protected
  WalletHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    SseDeserializer deserializer,
  );

  @protected
  WalletHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DeviceLogLine> sse_decode_StreamSink_device_log_line_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<IncomingFundsEvent>
  sse_decode_StreamSink_incoming_funds_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<SwapStatus> sse_decode_StreamSink_swap_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncStatus> sse_decode_StreamSink_sync_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TorState> sse_decode_StreamSink_tor_state_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressKind sse_decode_address_kind(SseDeserializer deserializer);

  @protected
  ArmCounts sse_decode_arm_counts(SseDeserializer deserializer);

  @protected
  AssetId sse_decode_asset_id(SseDeserializer deserializer);

  @protected
  BalanceSnapshot sse_decode_balance_snapshot(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BoundedSync sse_decode_bounded_sync(SseDeserializer deserializer);

  @protected
  AssetId sse_decode_box_autoadd_asset_id(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DeliveryState sse_decode_box_autoadd_delivery_state(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LargeSendReason sse_decode_box_autoadd_large_send_reason(
    SseDeserializer deserializer,
  );

  @protected
  PoolServiceReport sse_decode_box_autoadd_pool_service_report(
    SseDeserializer deserializer,
  );

  @protected
  QuoteRequest sse_decode_box_autoadd_quote_request(
    SseDeserializer deserializer,
  );

  @protected
  SendProposal sse_decode_box_autoadd_send_proposal(
    SseDeserializer deserializer,
  );

  @protected
  SigningBlock sse_decode_box_autoadd_signing_block(
    SseDeserializer deserializer,
  );

  @protected
  SwapAmount sse_decode_box_autoadd_swap_amount(SseDeserializer deserializer);

  @protected
  SwapKill sse_decode_box_autoadd_swap_kill(SseDeserializer deserializer);

  @protected
  SwapOutcome sse_decode_box_autoadd_swap_outcome(SseDeserializer deserializer);

  @protected
  SwapProviderConfig sse_decode_box_autoadd_swap_provider_config(
    SseDeserializer deserializer,
  );

  @protected
  SwapQuote sse_decode_box_autoadd_swap_quote(SseDeserializer deserializer);

  @protected
  SyncServerChoice sse_decode_box_autoadd_sync_server_choice(
    SseDeserializer deserializer,
  );

  @protected
  SyncServerFallback sse_decode_box_autoadd_sync_server_fallback(
    SseDeserializer deserializer,
  );

  @protected
  SyncServerKey sse_decode_box_autoadd_sync_server_key(
    SseDeserializer deserializer,
  );

  @protected
  SyncStamp sse_decode_box_autoadd_sync_stamp(SseDeserializer deserializer);

  @protected
  TorRuntimeConfig sse_decode_box_autoadd_tor_runtime_config(
    SseDeserializer deserializer,
  );

  @protected
  TorRuntimeKind sse_decode_box_autoadd_tor_runtime_kind(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UnknownBranchGrace sse_decode_box_autoadd_unknown_branch_grace(
    SseDeserializer deserializer,
  );

  @protected
  WalletConfig sse_decode_box_autoadd_wallet_config(
    SseDeserializer deserializer,
  );

  @protected
  CustodyDisclosure sse_decode_custody_disclosure(SseDeserializer deserializer);

  @protected
  CustodyReport sse_decode_custody_report(SseDeserializer deserializer);

  @protected
  DeliveryState sse_decode_delivery_state(SseDeserializer deserializer);

  @protected
  DestinationInvalidReason sse_decode_destination_invalid_reason(
    SseDeserializer deserializer,
  );

  @protected
  DeviceLogLevel sse_decode_device_log_level(SseDeserializer deserializer);

  @protected
  DeviceLogLine sse_decode_device_log_line(SseDeserializer deserializer);

  @protected
  DeviceLogSeverity sse_decode_device_log_severity(
    SseDeserializer deserializer,
  );

  @protected
  DialCounts sse_decode_dial_counts(SseDeserializer deserializer);

  @protected
  DisclosureItem sse_decode_disclosure_item(SseDeserializer deserializer);

  @protected
  EphemeralSweepSummary sse_decode_ephemeral_sweep_summary(
    SseDeserializer deserializer,
  );

  @protected
  EraseAssurance sse_decode_erase_assurance(SseDeserializer deserializer);

  @protected
  ExactSide sse_decode_exact_side(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FilesOutcome sse_decode_files_outcome(SseDeserializer deserializer);

  @protected
  GraceExpiry sse_decode_grace_expiry(SseDeserializer deserializer);

  @protected
  HistoryPage sse_decode_history_page(SseDeserializer deserializer);

  @protected
  HolderSeen sse_decode_holder_seen(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InFlightSend sse_decode_in_flight_send(SseDeserializer deserializer);

  @protected
  IncomingFundsEvent sse_decode_incoming_funds_event(
    SseDeserializer deserializer,
  );

  @protected
  IncomingFundsEventKind sse_decode_incoming_funds_event_kind(
    SseDeserializer deserializer,
  );

  @protected
  IsolationSupport sse_decode_isolation_support(SseDeserializer deserializer);

  @protected
  JitterPolicy sse_decode_jitter_policy(SseDeserializer deserializer);

  @protected
  LargeSendReason sse_decode_large_send_reason(SseDeserializer deserializer);

  @protected
  LifecyclePhase sse_decode_lifecycle_phase(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DisclosureItem> sse_decode_list_disclosure_item(
    SseDeserializer deserializer,
  );

  @protected
  List<InFlightSend> sse_decode_list_in_flight_send(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<ParkedSend> sse_decode_list_parked_send(SseDeserializer deserializer);

  @protected
  List<ParsedPayment> sse_decode_list_parsed_payment(
    SseDeserializer deserializer,
  );

  @protected
  List<PaymentDraft> sse_decode_list_payment_draft(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProposalRecipient> sse_decode_list_proposal_recipient(
    SseDeserializer deserializer,
  );

  @protected
  List<ProposalStep> sse_decode_list_proposal_step(
    SseDeserializer deserializer,
  );

  @protected
  List<RecoverableEphemeralFunds> sse_decode_list_recoverable_ephemeral_funds(
    SseDeserializer deserializer,
  );

  @protected
  List<SwapRecord> sse_decode_list_swap_record(SseDeserializer deserializer);

  @protected
  List<SwapStatus> sse_decode_list_swap_status(SseDeserializer deserializer);

  @protected
  List<SwapToken> sse_decode_list_swap_token(SseDeserializer deserializer);

  @protected
  List<SyncServer> sse_decode_list_sync_server(SseDeserializer deserializer);

  @protected
  List<SyncStatus> sse_decode_list_sync_status(SseDeserializer deserializer);

  @protected
  List<TorState> sse_decode_list_tor_state(SseDeserializer deserializer);

  @protected
  List<TxSubmitResult> sse_decode_list_tx_submit_result(
    SseDeserializer deserializer,
  );

  @protected
  List<TxSummary> sse_decode_list_tx_summary(SseDeserializer deserializer);

  @protected
  MintedDiversifiedAddress sse_decode_minted_diversified_address(
    SseDeserializer deserializer,
  );

  @protected
  Network sse_decode_network(SseDeserializer deserializer);

  @protected
  NotSeveredCause sse_decode_not_severed_cause(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DeliveryState? sse_decode_opt_box_autoadd_delivery_state(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LargeSendReason? sse_decode_opt_box_autoadd_large_send_reason(
    SseDeserializer deserializer,
  );

  @protected
  PoolServiceReport? sse_decode_opt_box_autoadd_pool_service_report(
    SseDeserializer deserializer,
  );

  @protected
  SendProposal? sse_decode_opt_box_autoadd_send_proposal(
    SseDeserializer deserializer,
  );

  @protected
  SigningBlock? sse_decode_opt_box_autoadd_signing_block(
    SseDeserializer deserializer,
  );

  @protected
  SwapKill? sse_decode_opt_box_autoadd_swap_kill(SseDeserializer deserializer);

  @protected
  SwapOutcome? sse_decode_opt_box_autoadd_swap_outcome(
    SseDeserializer deserializer,
  );

  @protected
  SyncServerChoice? sse_decode_opt_box_autoadd_sync_server_choice(
    SseDeserializer deserializer,
  );

  @protected
  SyncServerFallback? sse_decode_opt_box_autoadd_sync_server_fallback(
    SseDeserializer deserializer,
  );

  @protected
  SyncServerKey? sse_decode_opt_box_autoadd_sync_server_key(
    SseDeserializer deserializer,
  );

  @protected
  SyncStamp? sse_decode_opt_box_autoadd_sync_stamp(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SyncServer>? sse_decode_opt_list_sync_server(
    SseDeserializer deserializer,
  );

  @protected
  OutputPool sse_decode_output_pool(SseDeserializer deserializer);

  @protected
  ParkedAuthorization sse_decode_parked_authorization(
    SseDeserializer deserializer,
  );

  @protected
  ParkedSend sse_decode_parked_send(SseDeserializer deserializer);

  @protected
  ParkedSendKind sse_decode_parked_send_kind(SseDeserializer deserializer);

  @protected
  ParsedMemo sse_decode_parsed_memo(SseDeserializer deserializer);

  @protected
  ParsedPayment sse_decode_parsed_payment(SseDeserializer deserializer);

  @protected
  PaymentDraft sse_decode_payment_draft(SseDeserializer deserializer);

  @protected
  PoolService sse_decode_pool_service(SseDeserializer deserializer);

  @protected
  PoolServiceReport sse_decode_pool_service_report(
    SseDeserializer deserializer,
  );

  @protected
  ProposalRecipient sse_decode_proposal_recipient(SseDeserializer deserializer);

  @protected
  ProposalStep sse_decode_proposal_step(SseDeserializer deserializer);

  @protected
  ProviderProtocolReason sse_decode_provider_protocol_reason(
    SseDeserializer deserializer,
  );

  @protected
  QuoteBoundSide sse_decode_quote_bound_side(SseDeserializer deserializer);

  @protected
  QuoteRequest sse_decode_quote_request(SseDeserializer deserializer);

  @protected
  ReclaimOutcome sse_decode_reclaim_outcome(SseDeserializer deserializer);

  @protected
  RecoverableEphemeralFunds sse_decode_recoverable_ephemeral_funds(
    SseDeserializer deserializer,
  );

  @protected
  ReservationPressure sse_decode_reservation_pressure(
    SseDeserializer deserializer,
  );

  @protected
  SeedPersistence sse_decode_seed_persistence(SseDeserializer deserializer);

  @protected
  SelftestBundle sse_decode_selftest_bundle(SseDeserializer deserializer);

  @protected
  SendProposal sse_decode_send_proposal(SseDeserializer deserializer);

  @protected
  SeverOutcome sse_decode_sever_outcome(SseDeserializer deserializer);

  @protected
  SeverReport sse_decode_sever_report(SseDeserializer deserializer);

  @protected
  SigningBlock sse_decode_signing_block(SseDeserializer deserializer);

  @protected
  StallReason sse_decode_stall_reason(SseDeserializer deserializer);

  @protected
  SwapAddressCheckRefusal sse_decode_swap_address_check_refusal(
    SseDeserializer deserializer,
  );

  @protected
  SwapAddressCheckReport sse_decode_swap_address_check_report(
    SseDeserializer deserializer,
  );

  @protected
  SwapAddressCoverage sse_decode_swap_address_coverage(
    SseDeserializer deserializer,
  );

  @protected
  SwapAmount sse_decode_swap_amount(SseDeserializer deserializer);

  @protected
  SwapApiError sse_decode_swap_api_error(SseDeserializer deserializer);

  @protected
  SwapDirection sse_decode_swap_direction(SseDeserializer deserializer);

  @protected
  SwapErrorKind sse_decode_swap_error_kind(SseDeserializer deserializer);

  @protected
  SwapFailureCode sse_decode_swap_failure_code(SseDeserializer deserializer);

  @protected
  SwapKill sse_decode_swap_kill(SseDeserializer deserializer);

  @protected
  SwapOutcome sse_decode_swap_outcome(SseDeserializer deserializer);

  @protected
  SwapPrivacyDisclosure sse_decode_swap_privacy_disclosure(
    SseDeserializer deserializer,
  );

  @protected
  SwapProviderConfig sse_decode_swap_provider_config(
    SseDeserializer deserializer,
  );

  @protected
  SwapQuote sse_decode_swap_quote(SseDeserializer deserializer);

  @protected
  SwapRecord sse_decode_swap_record(SseDeserializer deserializer);

  @protected
  SwapRecordDirection sse_decode_swap_record_direction(
    SseDeserializer deserializer,
  );

  @protected
  SwapStatus sse_decode_swap_status(SseDeserializer deserializer);

  @protected
  SwapToken sse_decode_swap_token(SseDeserializer deserializer);

  @protected
  SwapTokenList sse_decode_swap_token_list(SseDeserializer deserializer);

  @protected
  SyncServer sse_decode_sync_server(SseDeserializer deserializer);

  @protected
  SyncServerChoice sse_decode_sync_server_choice(SseDeserializer deserializer);

  @protected
  SyncServerFallback sse_decode_sync_server_fallback(
    SseDeserializer deserializer,
  );

  @protected
  SyncServerKey sse_decode_sync_server_key(SseDeserializer deserializer);

  @protected
  SyncServerProbe sse_decode_sync_server_probe(SseDeserializer deserializer);

  @protected
  SyncServerStatus sse_decode_sync_server_status(SseDeserializer deserializer);

  @protected
  SyncStamp sse_decode_sync_stamp(SseDeserializer deserializer);

  @protected
  SyncStatus sse_decode_sync_status(SseDeserializer deserializer);

  @protected
  TorPolicy sse_decode_tor_policy(SseDeserializer deserializer);

  @protected
  TorRuntimeConfig sse_decode_tor_runtime_config(SseDeserializer deserializer);

  @protected
  TorRuntimeKind sse_decode_tor_runtime_kind(SseDeserializer deserializer);

  @protected
  TorState sse_decode_tor_state(SseDeserializer deserializer);

  @protected
  TransportExposure sse_decode_transport_exposure(SseDeserializer deserializer);

  @protected
  TxStatus sse_decode_tx_status(SseDeserializer deserializer);

  @protected
  TxSubmitResult sse_decode_tx_submit_result(SseDeserializer deserializer);

  @protected
  TxSummary sse_decode_tx_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnknownBranchGrace sse_decode_unknown_branch_grace(
    SseDeserializer deserializer,
  );

  @protected
  UnprovenReason sse_decode_unproven_reason(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ValidatedAddress sse_decode_validated_address(SseDeserializer deserializer);

  @protected
  WalletApiError sse_decode_wallet_api_error(SseDeserializer deserializer);

  @protected
  WalletConfig sse_decode_wallet_config(SseDeserializer deserializer);

  @protected
  WalletErrorKind sse_decode_wallet_error_kind(SseDeserializer deserializer);

  @protected
  WalletState sse_decode_wallet_state(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    WalletHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    WalletHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    WalletHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    WalletHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_device_log_line_Sse(
    RustStreamSink<DeviceLogLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_incoming_funds_event_Sse(
    RustStreamSink<IncomingFundsEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_swap_status_Sse(
    RustStreamSink<SwapStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_status_Sse(
    RustStreamSink<SyncStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_tor_state_Sse(
    RustStreamSink<TorState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_kind(AddressKind self, SseSerializer serializer);

  @protected
  void sse_encode_arm_counts(ArmCounts self, SseSerializer serializer);

  @protected
  void sse_encode_asset_id(AssetId self, SseSerializer serializer);

  @protected
  void sse_encode_balance_snapshot(
    BalanceSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bounded_sync(BoundedSync self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_asset_id(AssetId self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_delivery_state(
    DeliveryState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_large_send_reason(
    LargeSendReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pool_service_report(
    PoolServiceReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_quote_request(
    QuoteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_send_proposal(
    SendProposal self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_signing_block(
    SigningBlock self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_swap_amount(
    SwapAmount self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_swap_kill(
    SwapKill self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_swap_outcome(
    SwapOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_swap_provider_config(
    SwapProviderConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_swap_quote(
    SwapQuote self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_server_choice(
    SyncServerChoice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_server_fallback(
    SyncServerFallback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_server_key(
    SyncServerKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_stamp(
    SyncStamp self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tor_runtime_config(
    TorRuntimeConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tor_runtime_kind(
    TorRuntimeKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_unknown_branch_grace(
    UnknownBranchGrace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wallet_config(
    WalletConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custody_disclosure(
    CustodyDisclosure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custody_report(CustodyReport self, SseSerializer serializer);

  @protected
  void sse_encode_delivery_state(DeliveryState self, SseSerializer serializer);

  @protected
  void sse_encode_destination_invalid_reason(
    DestinationInvalidReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_log_level(
    DeviceLogLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_log_line(DeviceLogLine self, SseSerializer serializer);

  @protected
  void sse_encode_device_log_severity(
    DeviceLogSeverity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dial_counts(DialCounts self, SseSerializer serializer);

  @protected
  void sse_encode_disclosure_item(
    DisclosureItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ephemeral_sweep_summary(
    EphemeralSweepSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_erase_assurance(
    EraseAssurance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exact_side(ExactSide self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_files_outcome(FilesOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_grace_expiry(GraceExpiry self, SseSerializer serializer);

  @protected
  void sse_encode_history_page(HistoryPage self, SseSerializer serializer);

  @protected
  void sse_encode_holder_seen(HolderSeen self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_in_flight_send(InFlightSend self, SseSerializer serializer);

  @protected
  void sse_encode_incoming_funds_event(
    IncomingFundsEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_incoming_funds_event_kind(
    IncomingFundsEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_isolation_support(
    IsolationSupport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_jitter_policy(JitterPolicy self, SseSerializer serializer);

  @protected
  void sse_encode_large_send_reason(
    LargeSendReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lifecycle_phase(
    LifecyclePhase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_disclosure_item(
    List<DisclosureItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_in_flight_send(
    List<InFlightSend> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_parked_send(
    List<ParkedSend> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_parsed_payment(
    List<ParsedPayment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_payment_draft(
    List<PaymentDraft> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proposal_recipient(
    List<ProposalRecipient> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proposal_step(
    List<ProposalStep> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recoverable_ephemeral_funds(
    List<RecoverableEphemeralFunds> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_swap_record(
    List<SwapRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_swap_status(
    List<SwapStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_swap_token(
    List<SwapToken> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sync_server(
    List<SyncServer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sync_status(
    List<SyncStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tor_state(List<TorState> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_submit_result(
    List<TxSubmitResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tx_summary(
    List<TxSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_minted_diversified_address(
    MintedDiversifiedAddress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network(Network self, SseSerializer serializer);

  @protected
  void sse_encode_not_severed_cause(
    NotSeveredCause self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_delivery_state(
    DeliveryState? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_large_send_reason(
    LargeSendReason? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pool_service_report(
    PoolServiceReport? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_send_proposal(
    SendProposal? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_signing_block(
    SigningBlock? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_swap_kill(
    SwapKill? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_swap_outcome(
    SwapOutcome? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_server_choice(
    SyncServerChoice? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_server_fallback(
    SyncServerFallback? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_server_key(
    SyncServerKey? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_stamp(
    SyncStamp? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_sync_server(
    List<SyncServer>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_pool(OutputPool self, SseSerializer serializer);

  @protected
  void sse_encode_parked_authorization(
    ParkedAuthorization self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parked_send(ParkedSend self, SseSerializer serializer);

  @protected
  void sse_encode_parked_send_kind(
    ParkedSendKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parsed_memo(ParsedMemo self, SseSerializer serializer);

  @protected
  void sse_encode_parsed_payment(ParsedPayment self, SseSerializer serializer);

  @protected
  void sse_encode_payment_draft(PaymentDraft self, SseSerializer serializer);

  @protected
  void sse_encode_pool_service(PoolService self, SseSerializer serializer);

  @protected
  void sse_encode_pool_service_report(
    PoolServiceReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proposal_recipient(
    ProposalRecipient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proposal_step(ProposalStep self, SseSerializer serializer);

  @protected
  void sse_encode_provider_protocol_reason(
    ProviderProtocolReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quote_bound_side(
    QuoteBoundSide self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quote_request(QuoteRequest self, SseSerializer serializer);

  @protected
  void sse_encode_reclaim_outcome(
    ReclaimOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recoverable_ephemeral_funds(
    RecoverableEphemeralFunds self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reservation_pressure(
    ReservationPressure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_seed_persistence(
    SeedPersistence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_selftest_bundle(
    SelftestBundle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_send_proposal(SendProposal self, SseSerializer serializer);

  @protected
  void sse_encode_sever_outcome(SeverOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_sever_report(SeverReport self, SseSerializer serializer);

  @protected
  void sse_encode_signing_block(SigningBlock self, SseSerializer serializer);

  @protected
  void sse_encode_stall_reason(StallReason self, SseSerializer serializer);

  @protected
  void sse_encode_swap_address_check_refusal(
    SwapAddressCheckRefusal self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap_address_check_report(
    SwapAddressCheckReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap_address_coverage(
    SwapAddressCoverage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap_amount(SwapAmount self, SseSerializer serializer);

  @protected
  void sse_encode_swap_api_error(SwapApiError self, SseSerializer serializer);

  @protected
  void sse_encode_swap_direction(SwapDirection self, SseSerializer serializer);

  @protected
  void sse_encode_swap_error_kind(SwapErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_swap_failure_code(
    SwapFailureCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap_kill(SwapKill self, SseSerializer serializer);

  @protected
  void sse_encode_swap_outcome(SwapOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_swap_privacy_disclosure(
    SwapPrivacyDisclosure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap_provider_config(
    SwapProviderConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap_quote(SwapQuote self, SseSerializer serializer);

  @protected
  void sse_encode_swap_record(SwapRecord self, SseSerializer serializer);

  @protected
  void sse_encode_swap_record_direction(
    SwapRecordDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap_status(SwapStatus self, SseSerializer serializer);

  @protected
  void sse_encode_swap_token(SwapToken self, SseSerializer serializer);

  @protected
  void sse_encode_swap_token_list(SwapTokenList self, SseSerializer serializer);

  @protected
  void sse_encode_sync_server(SyncServer self, SseSerializer serializer);

  @protected
  void sse_encode_sync_server_choice(
    SyncServerChoice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_server_fallback(
    SyncServerFallback self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_server_key(SyncServerKey self, SseSerializer serializer);

  @protected
  void sse_encode_sync_server_probe(
    SyncServerProbe self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_server_status(
    SyncServerStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_stamp(SyncStamp self, SseSerializer serializer);

  @protected
  void sse_encode_sync_status(SyncStatus self, SseSerializer serializer);

  @protected
  void sse_encode_tor_policy(TorPolicy self, SseSerializer serializer);

  @protected
  void sse_encode_tor_runtime_config(
    TorRuntimeConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tor_runtime_kind(
    TorRuntimeKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tor_state(TorState self, SseSerializer serializer);

  @protected
  void sse_encode_transport_exposure(
    TransportExposure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tx_status(TxStatus self, SseSerializer serializer);

  @protected
  void sse_encode_tx_submit_result(
    TxSubmitResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tx_summary(TxSummary self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unknown_branch_grace(
    UnknownBranchGrace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unproven_reason(
    UnprovenReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_validated_address(
    ValidatedAddress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_api_error(
    WalletApiError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_config(WalletConfig self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_error_kind(
    WalletErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_state(WalletState self, SseSerializer serializer);
}

// Section: wire_class

class ZecWalletRustLibWire implements BaseWire {
  ZecWalletRustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
        ptr,
      );
}

@JS('wasm_bindgen')
external ZecWalletRustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type ZecWalletRustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletHandle(
    int ptr,
  );
}
